[features]
seeds = false
skip-lint = false

[programs.localnet]
fermi_dex = "DX5fj2BMuLwWEvJgrB2Z4JHsCWPDkB3c4Ev8aatrK6d2"


[registry]
#url = "https://rpc-devnet.helius.xyz/?api-key=69bea66a-a716-416b-8a45-a9c7049b0731"
url = "http://localhost:8899/"

[provider]
#cluster ="devnet"
cluster="localnet"
wallet = "/Users/zero/.config/solana/id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/src/index.ts"
