[features]
seeds = false
skip-lint = false

[programs.localnet]
fermi_dex = "6NLPgU8qntruya2PMt1hwD1CCBX3dAgKWjRHSoi4yrS9"


[registry]
#url = "https://devnet.helius-rpc.com/?api-key=5163c3d1-8082-442e-8a15-c27bff3cfabb"
#url = "https://api.devnet.solana.com"
url = "http://localhost:8899/"

[provider]
#cluster ="devnet"
cluster="localnet"
wallet = "/Users/zero/.config/solana/id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/src/index.ts"
