// This file was generated by a script
export const programId = ASrtYDNReHLYmv9F72WVJ94v21cJNa2WKo3f2tGoAH7C;
export const market = undefined;
export const coinVault = undefined;
export const pcVault = undefined;
export const coinMint = RKgRA8Pub4aqUEbQftTKmMJgvBwQLCRQ6siWheQxJoE;
export const pcMint = 4uNWNApk5QrJPgryGXsGNXqFXTCAvh4MZGQaBsMHRCiD;
export const bids = undefined;
export const asks = undefined;
export const reqQ = undefined;
export const eventQ = undefined;
export const authority = DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W;
