// This file was generated by a script
export const programId = "DX5fj2BMuLwWEvJgrB2Z4JHsCWPDkB3c4Ev8aatrK6d2";
export const marketPda = "FU6gFstMWKVMyfttkThc8J2VB6GavEEsjSStirNmFU8Y";
export const coinVault = "76QHEdBhA7Zu7FUU22zsUsnpBP1ZMnq6RDAJZVrgLcPq";
export const pcVault = "8URt163auyF2S8xVgyfp4rUDVWgREm4K46AULyVYcUN3";
export const coinMint = "Bkbn4s5axpYkiTr3bUiVm4GkmwGre9kazybJKjeGtLUd";
export const pcMint = "uzgCSzHK7DaV7FmXi5JpD6id3tSLPx1dxutpztkRNmn";
export const bidsPda = "FKESsJ1RuvSQx1FpH1dFSPmD8pWEibpQ1rRyaNvvaivG";
export const asksPda = "4pNv5NifLEj7hJL2S5oRvG4y5UDGmeATK8Y3PzXcuBzq";
export const reqQPda = "Hy4cwKJDwb3cDfWfhk8p6XgXZ4tBfkn3kJCEr9bd1Jtn";
export const eventQPda = "76VBBSEvCEDm4iV8FrqeJEoW9e6DGaq9EQpT73PUApfm";
export const authority = "8oLBNnz2xWq6Mw5KX9PUELQEo92kBmkSoTZCBph5C5ju";
