// This file was generated by a script
export const programId = "6D8nP3TRrsT8FZNbhgZXGhyZz9SbnHHU2egsdJjeaHa7";
export const marketPda = "nvKx4Mew31U218r6uFTEMwaMX5hVo3qoB2tiwHjzdXF";
export const coinVault = "71wqmwACjkBJhGvmKpkBs7F25L2i2DdL8oPt9LbxnABE";
export const pcVault = "2D1hbNkk2uWfyDDDQxA7rERiofEtSrn5cSh5myeYAkfq";
export const coinMint = "4U8aZMFwjrjCS9ZUR7HyAvu8q26NkWx68eLBJJ6rZPSQ";
export const pcMint = "7KJoHrYycuBExfimvmW8tp7KxqAFhJ4jEEaEFmhW9c1a";
export const bidsPda = "2ZrPymF5VVe24RJPiGPw5f85guQWLE4S6WTjVh6gRP4c";
export const asksPda = "QqRwtonXSQk7mUQcQVTpzptPDj8WZkDP1f1c11NwiZS";
export const reqQPda = "9cKSsiNyM16ii3HCJYDCHXxTKonbNbgDYqGPWWkpx2xX";
export const eventQPda = "4fhoaDDLRGfSzoMuKgMpQQ9FbLD4HJpDttnhsnqRoMAN";
export const authority = "8oLBNnz2xWq6Mw5KX9PUELQEo92kBmkSoTZCBph5C5ju";
