// This file was generated by a script
  export const programId = "6n6jCxYgo4xg3z86L65NMgq677uos7aFgrntiiq5FrTi";
export const marketPda = "HSxysNP4XqvBXrrtwKktvpcd1245MZz4G36TJhK8we2y";
export const coinVault = "C33cCUBVgRysHeqzfPedx4MsrAonG18M3nnYSV3JMNL7";
export const pcVault = "B8yVLhhriv9EyL1FZhWjeRX1eeDhuSLEoupZtXE3BR7k";
export const coinMint = "HZwATekYAFbyTGshFkrz1EB4fWBMwYzXBBM8uCzVVxbz";
export const pcMint = "AztT8pxY9xatfDvUgEQBdB634xDd5iEpgKzFwkKmHYMk";
export const bidsPda = "35VU9PeYe9v4TSNuEjZow3tmNGZK8FB85SArJy8F8ucj";
export const asksPda = "GJqn3ZKevavZ2Uj4c9Zg5S75w2B17mh6xFcb2P91KUKq";
export const reqQPda = "CsUg8AMXoPY3TgubyKvUawcH7BqKmd8fP8zqeYsjvU77";
export const eventQPda = "CL4duFnWXem2TR44VNb3uC6qqYzeesprybVaCdbTsEya";
export const authority = "8oLBNnz2xWq6Mw5KX9PUELQEo92kBmkSoTZCBph5C5ju";
