// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "FKwrJqRQaomm7eYzkPPBJ6hvdAVM1ZU4hUBgX8n9LxMS";
export const coinVault = "FmfD6TwARg1YEKpJnFaF7TVKGnVx9H3kV4Pi2oFwaB6";
export const pcVault = "6aJPxuQNrJXGwwBRUAMbKamS8QSVa5vvUws6t8GPwE5a";
export const coinMint = "DrkLDbY8FNxajwqgYdQRAJFEYkSEBpjK3TDST3N4ndaS";
export const pcMint = "EHcGeSoQywGr6RHNqrEuuDVAcHek9kTx2KaZfawrtamQ";
export const bidsPda = "77Ly9jFtscEmLjkSs8PyfSKbfZ1bWKP8CDnQTbCDG6Kp";
export const asksPda = "9fapcEWRHM5dWqMvjGgZTzQNEd1rgQ4cufYnQmhr6amJ";
export const reqQPda = "5hTt7X8LhRrsnkfKLYEcmdyDyoZj96aF874cLVZWUJW2";
export const eventQPda = "9BMPe8mLKMpvYh9CAwXTj1RjcFtUkzruQEvyGSyFBxUv";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
