// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "2xRYwBKnxZjFRd23rtzz29kEAcP1mg3mNRBFzWZ1ayK4";
export const coinVault = "A5gS8tFHQAjrAGG7HgE1H15K962PwHWfYGjSsVC8vjsX";
export const pcVault = "2Svs2TkRXcTwcyAa1p6g1a9caqqCTkqEUpaM3mfSCXri";
export const coinMint = "7dhweXgAZNU15s7e14jRiVq6D6imGy59feLfbhybbqLi";
export const pcMint = "ApWsZZYJQttzguGdcf9pUKG8GCKsksAYCvadvNUKxcp4";
export const bidsPda = "CfT2agZhysK2GPq52m9AHQFMtkAX2sRq782EadWu4zet";
export const asksPda = "w8grEziu9wv4NDNRGfWJfiy6SzWGdJePoSWehUR4jv5";
export const reqQPda = "BDRGfq5GG2aHcmqEYkARtAVYjDM3c1Yc8dSKeZ7QXfap";
export const eventQPda = "6HwhAUkGcniY1qDFiq7BKPR7q67aFJc8K24cQjG5qT9R";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
