// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "BnUPA1NbG2LffnadvpuZnG1qtWMczFLac6mkcLU5yHA1";
export const coinVault = "2U7t3THuiRsJNGyUVK2rRorehDYyunGxG4VoHF91dZST";
export const pcVault = "44txzBWTL2NVePREojZZTfKj4UF4ViCp3XyoNzxP3sYv";
export const coinMint = "Db5eNHBm8JMfMvXYRZjQPjdr3PATZs3BdM4yc6qE7ZVZ";
export const pcMint = "8ehZBb1bPyw7ZDNzS49jteSQdd6zytrrKUMevXvtNsMF";
export const bidsPda = "5LSHYXJZHD8NJsmJd8tfW8ce2W4ZsxF7LCB2KyNfbxs5";
export const asksPda = "9ofQ2rFrtX9cwSDeXwTCHaRKioN3tbPYrmkBcujcvr7M";
export const reqQPda = "5gLLrfqZotoj4jiSuBLwaqUFgCzTDQNqJEds23srSjim";
export const eventQPda = "EqHGuvuWqpb6xcNGAFyNKxD3nUJjbXHjTMHkHH2tG2gC";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
