// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "CU7gqfsoBopXPCRSUnpxHcoy1wtMzUwJzqz9cZbvAn8j";
export const coinVault = "7CFd7mRz9toEYv1h5MeZLTD2F1UiPZwJRMYnJYZSGGSR";
export const pcVault = "FtiW8fM2fKi8e7u7gFXq8M9qbmnpRRSKDUU3o9zkWvKw";
export const coinMint = "HfkCr4dtkBYuRPQH7LhQ9HnfVPwgRRYBqbEuA2chMjHw";
export const pcMint = "FHpaFqFhwhsHbrf4RrWvLCij4X6e4ZEZVDcYwe8o5s7S";
export const bidsPda = "GdmHsPFsmHZ5ZwoKwFbfPoFH7T1ZPVT9vWbJtCvwUxq5";
export const asksPda = "uUkVhFDym8D57nHck3QV1BQwYy1F2Md69ET5UwKc7XR";
export const reqQPda = "3ChkEKdLZmJUqikiku3cM3t9mwNEpQoLz9pCKQXgcchi";
export const eventQPda = "9gBCb4z8dxhziqqv6GMnLiNhUkAnyGrTHqh2EaeS2K8v";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
