// This file was generated by a script
export const programId = "VGwPEHBUjxa1ZQyvCAJ166TsKPYCWKafJoDeqdXqvdJ";
export const marketPda = "9Tbc9mAXoKfuapdjcRduJt79TWHo23WnSiim3XiY7VY3";
export const coinVault = "9jpLcP26jTCYwLZnRBPfPeuruWLQfVTjwoKss34pGyyz";
export const pcVault = "689fY6ZUTuvWKn2Aw2eaVnXHPzqvfaPYUZHwzFrnjVh2";
export const coinMint = "iEzAKuxkGzDKCkpMhEK3kwKgjG2LGj1HkhNRMmY8ubH";
export const pcMint = "3vrsVDVw3WDpwuHowQeLUWTwuZuNBrwFHDQdQt6TXBST";
export const bidsPda = "F4BKqT48NwZdzoRtkMDVAFz6tNmzBpbXshSKu9maLRhP";
export const asksPda = "GoaEne5ALVKJAqkoKTCp5UYd6QTdCwryNGSJfx6jWEzV";
export const reqQPda = "FnCsRaoH5odcboEZVagRTuuy58uNLxqiGdUjdZDKwWpZ";
export const eventQPda = "GHoQmVw1R1fc9A9cecpKKPmqVs8ZQVpUBf2pryniGHM5";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
