// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "Eby5GG6ksHcZdyxdBUMdcs667ofj4P5evjs8rBy1ZmBi";
export const coinVault = "FhEWQiAm8ZWVnpFYFRDUzKcm8aXSML3qJDoiNThJJWgP";
export const pcVault = "4aGAHGZ4csjag97cuNQGwy6917TysiWrZQ7iSswT2B1u";
export const coinMint = "3rNRwAT7Dy2mHQ3RJobJbEWrPhMEaBUc1FPGk3obcAL6";
export const pcMint = "JC5YpniAAsRvi3nEaKAwUzxxQgB3n3PyZeJF5nYFWmGs";
export const bidsPda = "FqwPwiHiPoEByqNa9dxP2mMt8fKeavU3aSoZjCpMEQLU";
export const asksPda = "CPWr5weLqaiCiGY1NLFQs4Fa2GpEXC4qGSUMiBzfP6je";
export const reqQPda = "FfRMCPhH28SUKowkt2nk9QFdkYzztcCmdnz4vn2dbmUZ";
export const eventQPda = "ATxBsFCckHbPqJfHaWGLXtR61rHSQT2s68zA8fJrWxCx";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
