// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "79tbrwGbacGxk2LB4tsCQtDJu3gKMRWMgh35fDbRFcZC";
export const coinVault = "3v3mRute4PMP4t6yjU4MB9vdaLWHbKyyiLdp8NcMq1cT";
export const pcVault = "79uQSAAGZSY5iNY34nD2UsDN4RYySVfhcPo5jjCae4UH";
export const coinMint = "AZQvhAGjyGBRgkbrafURbXkSHiRMpQzGDHPhTdkL6i6M";
export const pcMint = "DnmKcaHgfjePbwmXgEZEte37BkxoiEGQqxSXt8H7Bq91";
export const bidsPda = "7cExnJTSuZs82P9EYxwKAihgV7fsoWwVEkBmhTouryre";
export const asksPda = "E1jzeUhVrqRHwkyFUzA6ctBRcLDu18xVytxtrPXeur4S";
export const reqQPda = "HPbarKXjcaHHfRrzbsMRtPGyqe97i1JHyWu3pLTAnQFF";
export const eventQPda = "BpW7vaUVD7NEy8nAZSqLrPtMmzrTYeaddJkTycGjUmbd";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
