// This file was generated by a script
export const programId = "GJsyZs9cr8agF6SLiLfxiS9A11Avioe3JVPie92N4SNw";
export const marketPda = "7crBWh9t2459n6yXfe132TWHwJ512UeYyGu6xxucEWct";
export const coinVault = "3NDZGb47d5EnDFjLRKr6AMCoif3wP2MnN3QgPGfhCwXy";
export const pcVault = "2GeLgCfgFkNYVN9NK5icPzgxZj47KUcVKFFwPssGQ2Js";
export const coinMint = "DW9tF8WgEeydr57bH7bpSNePQ3w9emdutE5TLa1kSUJR";
export const pcMint = "HiRYKfnfdGDKvjqNTHngLEAgYfPew5xSmwEXhaQMrpMr";
export const bidsPda = "9U6KnJiUWDt4Y8UHRG6w2hUTG2S7EV5Pu3ppdzEZyGg4";
export const asksPda = "AAb6eQjYu54q86wr3Rz6xiSoPrg6aBocp9Q4ud3mH8N1";
export const reqQPda = "FhiuyV1PPuwnmnTqHModBxbbGrbV9k4yfSHd345dsfkP";
export const eventQPda = "9oEZKT72V5Ph1th4xwebThRaiNZaeKKZEtAUQkGMHq5W";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
