// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "2XcYudaSaMrzEYMf5SxMuR6FaKdZjEQdKPxvWmDEaYXn";
export const coinVault = "8xkiifgU9sFu8BdeAGXgjpZmPSQfGX6M7kMXfy8owBsu";
export const pcVault = "8JSaX4CwNLYYKboqpovNoD4j8AdUC5FGCVjJ91qMRdPU";
export const coinMint = "5j1Tr6bD92DYT4fYPrSvHHkWtdqqAUbojbUtqLAWHU7U";
export const pcMint = "2MCWGAqY6UguvAod44hJ53ou4ux1MDoi33ZzK4hzBXmA";
export const bidsPda = "H4RXJRyYr49obHNQJd1KoU6G2G7Z4uBm66UzD2VhLTW8";
export const asksPda = "rLLGR3GzgWcmP75sXSCMiFDxFcdsAEgeqxt2xVfqt73";
export const reqQPda = "9LCzK8BYHUPXpRW766P39bEk4ZYQ6aWqWhpnAYwfeVvM";
export const eventQPda = "AxC5segcH4WLsgtQZ3VrQcjnipppjeBAWVdEB5dLw9mj";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
