// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "BJFaFSQ7KSjDA8f61DahAtFiMDYS8WiuzEcxctgRnZxf";
export const coinVault = "E7BCZqf1n3QX4WjBJgkx6S9dPk5USNt1mcvZr697h7J3";
export const pcVault = "2xH8CTYEZdenbhegHXnfmeh6stzdMAEJoAibjrhypJDK";
export const coinMint = "22jY5ABUneuAcn5EGXUVPMteDkoM8duPBt6u5LJHM9KT";
export const pcMint = "rmZeVb3NuDaTC57pyRbVAYoxrE8659J8UiLuV2i6Evi";
export const bidsPda = "5LnPFXLZuxAJKtbEw3q8Af7cXi8H19BFRvDqQqNBfqHi";
export const asksPda = "2Bjz9k7yFNvDz6fniXKimQbh4KsvmPHjTbQ8aw8uPD9W";
export const reqQPda = "EYbbki73Jj1NkDh4qrUucWysEAGyytEfh5KSR1jvVHkQ";
export const eventQPda = "Hjx5zMvZ5D4vXHRZGsw9r1aPMiEfLMArJTJuCnSkQ9Ws";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
