// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "NBAZJdZhWxrocjU2Xc3PkJSCe8R1i76GbtmSpsSR5gw";
export const coinVault = "6eXXdeAspSnXhe7LAmhiEVMrmRjrdn3ZScjGpm1yMSGe";
export const pcVault = "Djn9MXrtri3BmbA2ym9C7cjyjb7bgTiTGvcCX7QxMhBL";
export const coinMint = "5pMM7taoZJzE4LArzNB9HL4EALGZTHd7MSxn1yqXaa1K";
export const pcMint = "5Wbqid4vvMQ2As8SfYaECrXJ6Ew3LMk2G4AF9V9WrEgm";
export const bidsPda = "6AxnSwS2XNFv2Cg7cnF2Ks5Fz5TAHV5fsef5Qtz5XMpc";
export const asksPda = "ENjBkM4effaYRprcGTzv6qePoyd4gy7MFPNLPnPKgdPc";
export const reqQPda = "3FYzajdPrvjn8ppojQx4AKW1UzTrHZaSLTZnA85utqRJ";
export const eventQPda = "2A19cZ19grZmdfsrxEYwEDFMEJ3uFGi82pMxzwgMnBZ9";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
