// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "6qLoEhXjmfQyrcLQGuxqEpGJyqqVA5UmwK4UcgDgAZv6";
export const coinVault = "DjX3YbYGHceZVE1ZY7X5mesag5yEGdaJHjtEzoa1RnHV";
export const pcVault = "DAj5scMM7Zgy2mivxb5qeacmy2wDSkwvPwaVorgE3qLw";
export const coinMint = "5YTdYgqbsZBwNh6Y8aMGBjFYpZhzpZC4rauENb5o5TgX";
export const pcMint = "FcTMJQPMo9vRQktCMKR9uHHEFJTYsUL9UnnoeQZQi1Gk";
export const bidsPda = "EquNatrBtdhK1ZSPLPRB6anrGyMUzGBopmZdkEHwCpmt";
export const asksPda = "8mNAPEg4p5kPiwD5Mt4wgEtGKBJm64LnhSqPspLJAdyN";
export const reqQPda = "83cMGZmDDS13ub8Qx4vVeLeKeqcFUFkJ1mh1PQrn78b6";
export const eventQPda = "GnaD5bLy3H34oVYxxaFWGu36iCoABZrPNjHV4FELqGVz";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
