// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "3b4gtpBb5vRoECVtfBgLqv7LaZq4vVMFjDonEZijnWrv";
export const coinVault = "7k7eZrmRZbHfMwzoU2hMbcj9dqXwvsj1fjU3MgBSu9n4";
export const pcVault = "GhQ8gQoJ5Ej1YAYNfEmqz3SPVn3mSyknMy521eCG5db4";
export const coinMint = "4Lv5zKttnDXKAbawFxRRBXXDgxeBbiJ3qtrNYnpdKwjU";
export const pcMint = "J1Cm7udWt22rWH473nsqVergiaxs9Zg2tZS3Zq7k7o2m";
export const bidsPda = "397DiGdMuXWti9QGvSGgYmAk8zweMcpat9Ryvky6E73Z";
export const asksPda = "E6KQp4Av7YkBNXC4BVD81rCirkUJ56JtAFr9qCAJjoMr";
export const reqQPda = "554PjqP2TWJGLNJzfMPm4bN6kSgvg76d9k7Zj4bj9YLp";
export const eventQPda = "5Zb7XmMZXxxX4jWd4zxWKpmpnyi7DLs1e8r7fSoSCWKq";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
