// This file was generated by a script
export const programId = "VGwPEHBUjxa1ZQyvCAJ166TsKPYCWKafJoDeqdXqvdJ";
export const marketPda = "7cUNqonBv2iiPHi2LCi6N7aiQKCXgRZVdofxQbaswrZi";
export const coinVault = "FcpEpKpGpEzfgvUoD85B8J7tGZh8MQ6PyYsSnnX4dUfB";
export const pcVault = "FC96jKDKeQTsL2aHP45Gxxvbncj4717yHUYJGAGwvLC8";
export const coinMint = "6bQtnbRXgSePKVMbRwWX9y4qAiE46ZjmU2ViP27q9jgn";
export const pcMint = "5NHq9soptDwmFGkuZRqurxwndAzgPHT2f61HXQakbGsu";
export const bidsPda = "HZdoT9YUqTqZNPmjrYnbabqruMrEZCPSjbv73NiixPs7";
export const asksPda = "Htq3wpQ9gHVEUHuPuK52H2NjT45d2kAhHMGueYqNFztU";
export const reqQPda = "9fUZCoh8Vbhh64CxXfbHwhq2vQPcJYPDJShqrhTvpFfr";
export const eventQPda = "AGJoYbQpn5CawUjU7RJUf7rcQT474H87egvZnecVG4yN";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
