// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "JBSDnweyM5aLC8rEwjTS9dncGWAavzLuQ37dBzDJSWb5";
export const coinVault = "DqvenZGaWzTYcVZUzuuCgU7Rw8JkbT7rF4mdBkwq1otP";
export const pcVault = "HR6AkSGaFeZYrHEnf3PZ34rtKH8jqFjb8pdGw6EwHgHw";
export const coinMint = "4CxxLRcJh9HVLUzP1g8Qpz7LsqHYpDsR5BMQ9QtxkmSs";
export const pcMint = "HYxkHagEq9zXdsyK2ggrYnTXiu8bA3VCgufscsVdykHR";
export const bidsPda = "Bn6kFSvWrXogf47gk1mB74A9NeDXVvrnjWQkh6v7iX9W";
export const asksPda = "DB2qA6ucpNrBYkDHPu6fBapU9g6wTEQZbvhndXZiNGxr";
export const reqQPda = "3NWveNjs7hkqT5PxCVcmN5YECY4VaZswrshLEYhjELbG";
export const eventQPda = "8Fe5qpTzym3Zkvwy69oF2j2S9EmCJ9q4L4XPDp1s9gfN";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
