// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "2PkMNMAhj1v81uSyJfwcxGZePnyn7ueBejkzU2iszauJ";
export const coinVault = "EkYPjGPWS7xKCES5cyNzfNHWXKzGZCdxExCdaGCEfHHR";
export const pcVault = "FifPu2HqTTFYaXpHJ6X9DSSMC3dFdfciV6h2HfDogrcK";
export const coinMint = "5XGrUpiof4ejTR5KWV1ht8qNdCu7EvdWHiqghbTYLiL4";
export const pcMint = "5kBN5y6DMsBiHPcjrymDKZWxJSwTzBqwxzb8W4diNoDJ";
export const bidsPda = "3pkzNVbxSo1dFSFNH4uM1yuBzUHN5MkWW8LKdtd4LnSG";
export const asksPda = "p1xKTizrofgEM5XauMUBGbpDdyvWvsWTZx9S4Cmi5U8";
export const reqQPda = "9h48GWDHPbhfqTEAdfXbnvRcUddV4J5AcRDvE2HUS2Dn";
export const eventQPda = "AwEFbZGcBmCxApwXMKBvg4nDH8J7tsZV9VuKDAEZjDQp";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
