// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "CxgeZL91FbcuNRXuBRiA7zRyFVN3t9CKimKJx98UKFmk";
export const coinVault = "3kgyztEvFXTqiW3YxCo16KAWyzVUqrSAnq27A8sawqAD";
export const pcVault = "8Qd5x5TXqVQ6KsGRn7AXfJA8cZA86KJFN1faiBwgaVpp";
export const coinMint = "zD6PfkHpHNN2hMFiLFhjVp1YrEr3jfhSRAYCZVm1K8F";
export const pcMint = "GY6nyZWdvLrGJdPVF5GmJw3qd7Bu7Pa2V95tGck2GHZJ";
export const bidsPda = "9UkTM8kjJ3JfGKGGPXT1SbDWikBRgjBUdnWJUmR5bqfA";
export const asksPda = "DWWdX52SAH2SMHHEJZentDKVM5weNBoorPVvqwxyvFYS";
export const reqQPda = "W3bu3zsL8hK6ogphxsqZexXrv35B9yZEjxm3js9SHbD";
export const eventQPda = "3jurZgvQjhs3hjFnze3vcj6viC8SEcpYxFynNJ3QuBF7";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
