// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "HEf57PHk2FjnRWUGnE8d65MknhuQmDzZ3Qu3SNkusNo6";
export const coinVault = "7rXPJs85KyBHerPP9fR6ADxATM7agfPKtWFz773Z7x4B";
export const pcVault = "9Ae8ZmYPerHoWjWzvx7UEEDB1oj2BLcWDhZCf9a3XPVT";
export const coinMint = "HQRinf21UkCzvf7kExdj4eqyXt4rQKNJDvu9U4sR6UKX";
export const pcMint = "Gfui4x4aAMY7247J48iL16m173HXD2uVxDSTgZ3gN1PE";
export const bidsPda = "AVFqiCeaQmXmBQf4MhJiLpBcBPZob5VDeBjYMTD3kMzQ";
export const asksPda = "Frn7T3Jqb996CCozUPotjX6SXsoM9UKbW9zcqKpAbJFi";
export const reqQPda = "8Cbk2kqVYsJCjVXp8jTPFueeREXfUDMSNxrBis8kRBQX";
export const eventQPda = "6EXqcm7kxoiAi2bF37JW3H67Zzg8Ho9VZPTGmjZ1fC3Z";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
