// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "CMsUZbEhYZWS4jJXGie6dr6Gi83wNCaTAzkXhHjs8NKY";
export const coinVault = "4qD1TiX2rVhxLV9sZPKUTV95URkgRnD6fH3PccuUQ46T";
export const pcVault = "9JsDytMuGDu87kbWCb9iFPj3pMsbv2xUDE1fFnNZL1G6";
export const coinMint = "8ZKWauW4mGb742NUQtpraWRP1GiE7gLSAqmHuWWBiZLx";
export const pcMint = "4ymVafZpTbJ4FUzCuBPe16TG6SzhGb1zcLJ58d1asFEQ";
export const bidsPda = "EUb8ZqYkryLe6o3Z8y34MsPYwD6mmbFu8YbCnYzVjBcK";
export const asksPda = "BqAMrCDxjQ6vaNd9DpBmT5EesBg8DpsHVQi6zTLp9JtR";
export const reqQPda = "9vorLyCqABA4Sva7MmNkEXfreJN1z8q2djkqQEueisu1";
export const eventQPda = "7rQDbRPDTbqmt5zbtuubKFeN1kNrpuKghJHLoqkQJ2QW";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
