// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "BNXhryJQzmkkn5ZzxcXvx5w9u3fNqB6PiPZKQT7v8zie";
export const coinVault = "5sbDN54wuDBNzQ6YpbAYQvjDRAUmQNAsWwJhKfk3CbzZ";
export const pcVault = "E25bFCYQGdv9pBaRZSNymRyBDJLR8FMLbfzR9kxkFZ1P";
export const coinMint = "FBdkicEFsTtCd496zaP5nj78oR1GfQwME9Swghn8xwzg";
export const pcMint = "9pufZ75Prr1UvzDLGs7BWHhdchdo8b2Cas2mjMRGhLwp";
export const bidsPda = "CmfeU54KfebmrqQxZhcUyiz9FrZjZZZiHvXc9fX3qZBL";
export const asksPda = "2dnSJbkAkvfu7iBgfxDwjGJBEnzrQapW6vZSJdDrm5ry";
export const reqQPda = "CL1yxE7ke71BdSyT15M2pCv95eyX1BpH3sPjV3FQ5Gcs";
export const eventQPda = "6BN7HSeAgCDjGh7Mi1eBhh7ZzYbFJxBrMQJ4GW6oPzrZ";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
