// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "A9b4iT6LyGnpHG4oGeCEv8u2drQqLoTngw85Gbqha2o2";
export const coinVault = "32qqfwi75wt4g3wiyaAxrPmyGZx1gRH3jvvebEtup4dt";
export const pcVault = "29HE48AYb8hSqxFAHVnJS98dpFLZ2MJHGysthaziwytG";
export const coinMint = "4Jy36Dnt1mfgywd4WuSX9zqmX3FkpsPmPQPDKwEjGYvx";
export const pcMint = "4ak4YwEJSxDa7gkEDz8N21DsBMo3ZgYEAx92wAtYajbE";
export const bidsPda = "7aPiypFQ9xoNcowuAPmGM3hshXSvp8HFxQZK6g5e8jAk";
export const asksPda = "BL95G47icRxZT6krsg2Eh3Xz3izwsJpneF2Rkf53Bz1k";
export const reqQPda = "A2pN47ucrUyhx3yqiS8NsfbbdsjhHWHRfALzZvNeHeuC";
export const eventQPda = "AHsTA6qkAhkkN4dFasbGw1f7S1quBzVncTbnwPG51V77";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
