// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "23bS5o5WYbU99mUd7c2Yt92a5o81UyFeymHErCUxB9eA";
export const coinVault = "89EFwmnLDoubghx1tBKFcgfmrRCZhU75WDtsm3ZMzeTB";
export const pcVault = "9Ps4na4X9VL4qnGbP3tk6m2ccdTUGqjcLg1dHthszYsx";
export const coinMint = "8VUysxbGijQVFK1SpvBenJRk8Naizpg1ir6W31ViQRab";
export const pcMint = "9QWAZZJPhXjDV7JhKcParkYdxEk5xGCtYadqosJisfxQ";
export const bidsPda = "4eHuPkmCxA7VoDYPnnxsFMSjUnpuRDo4VHyNm86M3UBE";
export const asksPda = "6tKakDfmt3MWQ12jbn1Qz6MPVMe5dCaFAWv8QQtTQiBj";
export const reqQPda = "DFJGmQGPQpwTjWXwhbQ9o9qBZ1oGUrXLAkBdi5WpVFm6";
export const eventQPda = "FA16oNyPgjnqMUs3d4XALpeiPFav1kf73MFSnncgZLiv";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
