// This file was generated by a script
export const programId = "Aodrp8JRS1tCywT97x5ytaoJYczv44JYtyBHDJGLCx5m";
export const marketPda = "Bbj2xSxnWCBGdMtCGDHvH1qcHb52DT3diYAdYo5GfoVC";
export const coinVault = "6iDrBji1pHNfofsFr7znmsHC8JGu3ZByBAsYSXK4Rfez";
export const pcVault = "3yJXweguKNBFbGSEZMVA4yWHq8rhQoDaFkxpDn3GoJKZ";
export const coinMint = "7wp2RSMRAmxB4QNzQEUHCsxkYj9NiLJh6c4F2HuDVULk";
export const pcMint = "4pAdbVH4U379jEwsja1LkDfLrehyXQ4MwSNpoWQMf2ty";
export const bidsPda = "38DKMnpRLvmLsaeF39vQykQ2cCzxbTBRCcw5faVFEeYE";
export const asksPda = "8cpnt6QTBYXhcrMfeD4CDAyEfMJKKBvQCJZSN57pHWw1";
export const reqQPda = "3UR47ZHJUzxSJ9kfsUw8mUXgxgdccNJbYN9EfXtyTksA";
export const eventQPda = "FTgLTryQMjwUJcZ8N2sdWb1HR526XckrdBJqEAcTsh9o";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
