// This file was generated by a script
export const programId = "8yskqQf58n63JFYLPHhp2dtC98gNYYsjEp15XmBJV8u5";
export const marketPda = "81kkheVLthaJbzwNRGnJjZTrht7d3fhoWiUvZsMp2v5p";
export const coinVault = "GTpvmG6i49PQmkHyywEY52yCj8uh2WoJ5CiChfWZgxT3";
export const pcVault = "3KC98Q9JR8vs7q9SStSA8mPkPAY9jFr8qiTNyNLaBiqd";
export const coinMint = "ESNSm9zBTMEztkLWrMVAR588GgaMsnNVVHEXeud9ALyf";
export const pcMint = "umXrc1aLAwRaCHdxYVxxKnc72vAr1zhDzMFFr76iiGA";
export const bidsPda = "5gJ63yCqPkLqH8iVFQVEzgY1VvyxdVNNuEGhubVDSbZX";
export const asksPda = "Fto1czc1fN7uPQsZKhJBgmXyokR7YBVcFqrV6GQfPexg";
export const reqQPda = "C1NL2puGTkRvNk6M5oFr3pfd7vyY1RWCFmYcP5ewvYaz";
export const eventQPda = "C1c2R2NxKVeTDgQKHCJkrWUHAEnmQcRUZ8BnsDN5r5yW";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
