// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "3ozApw1KL9aeVKNsPaPxtExY6rn3CocRGADHaKkJxJW1";
export const coinVault = "4QmaukBaBQz8WHk8dVxk5wnfuwZiUazTRQWLSwooXJZH";
export const pcVault = "2rNBgNbNQqSpyyRqsXcNTG5j6p6aYV51bQ3KLjPCXY7x";
export const coinMint = "8tofKvCJoZUicWDj3aUvDr76WXhbdXVxpxLo6m5FDJhT";
export const pcMint = "AyXLtTwfQPX7BPggSZXCaiNtXGK1e22XFq2dRhpXJHLt";
export const bidsPda = "GFjF1rSHkkg38w27jcY5zZSPZrTQp5VaXJ6j2AuLG4fH";
export const asksPda = "CpWB2CL5KVhWPWgWjPx6MkjLsbB5DYEH459jrYLATXpc";
export const reqQPda = "2p4ABGUkaAMAXU9g8pFHMSq1AA4rGUmKGBV7ZqdyhrRD";
export const eventQPda = "7AsB5qMzeDGJ9qUt3Lr8cYT4gZCrJtJFG15yRVyD8rqk";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
