// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "4vUni4APU7dTxchkFoDNKMyGR4XafURv7py7VafothL5";
export const coinVault = "3uVDZG1Wy5ULG95VZrYf3QyGNQ7WGYFMQdncTc8BzRx7";
export const pcVault = "aSxaLL3V2y1ykYSh9et8SyuvKDxnWK5x9uYKqLAEJcR";
export const coinMint = "Cghdp31hhvHPpQZXTBW8jDxxv8s3NuYPJ8XZNsofabZx";
export const pcMint = "CzaVAo6E26rpG93ceeYnr7zBGtnCcH9C9q7PCMZ1mNWV";
export const bidsPda = "NniqtFAsjsxkBaQSzjrx5YuDSF74ohuGzDVvP7F7Wqz";
export const asksPda = "71MXu82kkjFMiwxREt4EFoHJiLtbG4EHmEZ9yKPcm6M9";
export const reqQPda = "9gww7DcPXoCS4VuVoKHgiCNxnmtcgRKGWsHTXEP34DWj";
export const eventQPda = "BsgjTXpkoR9edVBGCKGnk7bBavnZqq4uVNM3DBpLdxWj";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
