// This file was generated by a script
export const programId = "VGwPEHBUjxa1ZQyvCAJ166TsKPYCWKafJoDeqdXqvdJ";
export const marketPda = "vxLndpam7U2eYM1gjjWdqbrQCDZWDFieVj895eR2W6o";
export const coinVault = "9bZ6jRMDiV3kj2n2n93sQFduWymw8TaHon4CLY68ZJuj";
export const pcVault = "6r9SV54U2EKA7Erp6sZXdrUCqekPFtP5nEikpQtFKfKF";
export const coinMint = "CuTBEHStvq46fNTFUVbZ9QD8qk6LjeGumwSxCRCkWKiB";
export const pcMint = "DNnhs33xEdAuszrX1dNXmsRyZ5hJVwuiC7wT7qpANR8D";
export const bidsPda = "5fLysqt5Z8xdqCeuA9fthv4w38QpFFvwWNNmBDUb7bGn";
export const asksPda = "2XgVzDg5YFyri77uiQonCferBVhJQPbtTyvUhHib3xKQ";
export const reqQPda = "C3dVwbffsdJpT93r9MKFcQMXggDCZDG9hxKkynS38res";
export const eventQPda = "HjpvpchFCWtEbFYBtAe6hLvqbjgcgY2FM3xdj15ue5B2";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
