// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "DrZjEckGAsHwCYoMyek3Tv3piVF9UWozQjajxeq9Vxua";
export const coinVault = "FC3cKHqbLadeyvJbYs74Z7NB5DneHsgNp6LfVrQ3Yt4x";
export const pcVault = "3dqWxngmEeS9FBj3M4b7TYUuDCPXEekrswH8i6cGtvUC";
export const coinMint = "7p42bpaToHcRTShEVWmPHmNEd7gXPaQzauWaCC47dSeg";
export const pcMint = "5Z6f4Ep2KwgkzbmJmdykLVt5J3DyKh9MHBTP6LatJid7";
export const bidsPda = "5pAbVDwEVFsdyARBm6wEHPRZSiKYq4c67TNtcYW1jetu";
export const asksPda = "G9QHd7SbSKyJiheVqoYKnbDScGy2f9w99QvsyhhXWKE4";
export const reqQPda = "EbKcCzvasFVZs6BMCft3UqcfXxdB4vZFsYXRTkBYi6QQ";
export const eventQPda = "qctQsojswqe4CFZyTkZ8pUJuixwK9e8acAhuiLMiMyj";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
