// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "66wHpLw2s65guPHr7zgESZix4K8iHQqhVbTXrVYbdaAt";
export const coinVault = "51Yp1f4EUFmw29n4U88PhKqAEqGEYRWvgb15oiRSM9r5";
export const pcVault = "EJbcdNAa4h1Fr4C7UcPPjD7t5EStoG5pj7D1aHiKUD6y";
export const coinMint = "FKMBgmwbe6TA4DFRWsS1byw8C8sqdCabpeGmJDEQDimL";
export const pcMint = "982eiUsmcWsWyHoRrVXAfLzdRYjujsVLMFda3wxn9SAr";
export const bidsPda = "2yHbfycojXAVB6QoMdSHwL4hU42E1hT6X9YHEzFZAxmb";
export const asksPda = "An5LbAKUH3ht3gC6dgMAWAm2VEf7RFMxkNS1fNYhXvyr";
export const reqQPda = "2qtpW1tKcHrgxmzY3Tymrz76jzc5Pr9AhnoKjFiJToH9";
export const eventQPda = "J6yJyAm7T6J2JfX41xMQ3SpNLnKpQ7hsi786GyHdHFs4";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
