// This file was generated by a script
    export const programId = ASrtYDNReHLYmv9F72WVJ94v21cJNa2WKo3f2tGoAH7C;
export const market = Fd2CxZqgkeRkeMZk7UnU9ZhQrAkBAQVi5cDuvgvpLNvF;
export const coinVault = 7xpsBY6cMzm2UmdjvZouWtSPEu9Ney5bZyqMFqLbsfuA;
export const pcVault = 5T5Z1j7rhdwsNmtTq3ioZxp4VxFH3YhVp6Do1Nuf2CFP;
export const coinMint = 3Rs2whZCZJmTANyskDDQq78XRhKrV5GizpLRrA8bcCG2;
export const pcMint = 8hG3qX2ZJRk9gNd8tvmW3qAkjv1W7e6nT7jqMSb37KZy;
export const bids = GnQzGTx5oWXXsxUGRqbdr1Qr8tyyeQ51RafH5seR7sgV;
export const asks = 3P1aVLmNbW2Rf1urF9TYLH4qiKCNQLTm9nc51d6Jccac;
export const reqQ = 8P5jDPDwPvFnznkaZDiiKPbWnEcA47MDixQFaFXpKHyy;
export const eventQ = C2AQN3y1wsG8rSUwdo56Dk8kkkTQFn3BWMEvVNj1t62B;
export const authority = DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W;
    