// This file was generated by a script
export const programId = "8yskqQf58n63JFYLPHhp2dtC98gNYYsjEp15XmBJV8u5";
export const marketPda = "3XU2n4rp4zU7h2KBrzRZwX2RYfgMF8SCtRo31ukxsf9U";
export const coinVault = "2nNTtFD8s8JsnNLgRhx9oKcbNMCBGS1AyT6cVgKsAZK4";
export const pcVault = "Gr3M7bg9dyWfHE86wV99LDy5CooZe2jXJcaJjMJvee1";
export const coinMint = "52nWetiZxYuJJQBraMHeEQ9jQZ9v7G1YirLHXkfdMMow";
export const pcMint = "HjRkgqP5VFuR2kvXmdgV2T9QKAPw2q5cixjq5JXDUzGi";
export const bidsPda = "aR5pSJRBMXJfiNNVGDxhMXsj5KshUiq9Fbasu8uaX7w";
export const asksPda = "3LxCo9MWpVkG7em3vo6fBV28uFNVVko25vo7iB6SXVXs";
export const reqQPda = "4uPjSiQrAycXmvkqcu2JBDH8nFPwoC6qjCyBvc4K9HdQ";
export const eventQPda = "3z8ZWD2k1Go8wtVPFDnB4G2b3uAAHzd1SyN2Sahn737X";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
