// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "AB9bwhV6ae5zXEAq1yqqdy6K6xtGRLikkVpqaxDKRmqm";
export const coinVault = "Fc5vZbhjhzRJq1NGnmR3dNY2cNzNJFhVskqbYG9L8XD3";
export const pcVault = "ChAhqXtSGjRccRshBnac2fQ4KhLgQbaKHHg6He8Sh9Sr";
export const coinMint = "FL3zjugi59ByzM1K3WAV3ZyXRYUxUf7DSroKDyJPSBgD";
export const pcMint = "82NbtN2DRevzPYudDtbeghqx5VM9YecTwT7syJLZ1jJu";
export const bidsPda = "4ibrExUehgumoBHdQxpG7gtaYLydGP3RSM9gHunjxnzH";
export const asksPda = "9XejjhdRjDv24FwskVtnx7gxFgTJFAdDZGYnLPprtSAq";
export const reqQPda = "4AyAdtKfqSmeE7uWY7RWxwVkAoCSN9oNVRa1c3aVDszH";
export const eventQPda = "9tFrNDw8JuDt3KZbsrd5HLJXgGP1eoPN7wQNpGsovUDo";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
