// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "75ZB3Td7qB3qdfMLv1fD2HYSfcf3sFmQvQ6YdYjBpaMy";
export const coinVault = "DZmBZ1X4cK7RX9ZEdVdRYswmE5wEJU8K6yjFnesQF3jD";
export const pcVault = "5jwXz6R1rjP9QLCWpGHedtGEgqhGraai6ZQnJDMp2TFw";
export const coinMint = "AEYMT7Dbjh7fiZSWFTWxvVH8EXaF3RjJn7zdgJnumtkQ";
export const pcMint = "HD8CByNHUiMfhzzM5BTLjsrRYKo3TBWHZ59rLzv6Gp6c";
export const bidsPda = "AhKqVdrrmkQUxnS6ZAULSzaPUAC7qZQqJSoQfERyfyL8";
export const asksPda = "9HR7QSFLXfjx7TmF7AVNryz3sjC4E3wYyoPq1dN8HDpE";
export const reqQPda = "4kdSfcQYESvUGnPyvnnZzkkKAxCiNNheNiFZkYqev8BJ";
export const eventQPda = "5H2QbRx2yAZaxiPy7AEMCr23CXjkP4efLpUmTiWw9n7F";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
