// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "8TbBqkRCAbiMkLRSnUp5R3cFqopoZ4gdydkJZ8Y3WaqV";
export const coinVault = "HLXRjKG98dBw2v7tukVDGT4o9uwSD8MJRRfojbud9rkG";
export const pcVault = "7ZxrrrbS8JPwFgEFxpoPwhSonF9cn8wfhKRqA8gVwq6j";
export const coinMint = "B8BPzHxhQrYMyhib16aLQMdgEYQMaKChxTa4yKgcP8GC";
export const pcMint = "2Voy51zvFALJutK1bxRefuJBXK9WdmDwB8ovKuY8ZfBU";
export const bidsPda = "BYieW7WMS9tNoZoxX49Yu82Y6HpJ6NTd1LkQ1dvPJXbZ";
export const asksPda = "2bZPZohouDEdEroFyHbufFDErQqKPrpfvFpUNLeMAMpz";
export const reqQPda = "DAojWZfpSDbi1pt5tyzBvRSyPq8Q4NMNcEkhgh9x5eCE";
export const eventQPda = "CJE6DMqJwXf8usiptXGniSoMcqzZrJ7MRDTosBh6Gndj";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
