// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "7kAWjUfy9Aev2eAPjvCo7NjDhYo4DgV1AgPZDXSLHpTc";
export const coinVault = "DjY5ZbgoVoEHaMao8yfxueAPvtLumUTEGWf573CRcvJc";
export const pcVault = "DoMiQjsm3G4Bq8YGetMDvcTW6o2tCKftPhGeroSxzjtA";
export const coinMint = "ARiDP7gx24v8oVfpjWs2xmb5MCC2dzVDiAkwajECB9tQ";
export const pcMint = "4nEvfVW3ox6Yi2QBwGKqxBSLBJVbB2fumufmFSp4dahc";
export const bidsPda = "DcsnseWnCgfoKPLLCuF5R99KbRasWv6Tieor4e9NPdzr";
export const asksPda = "5yRgc2tyz6A57dCK5hucfZvn2Dc8vr8YDnvD2tQaK7Ee";
export const reqQPda = "FVhHrkVnMqqHpKxb2PdfbdXyQW9SbmDgkz4aCLMfj7zJ";
export const eventQPda = "8cpbVgYus7GU9hbW6EaUrFg4JTgKRndSJPj6SsyYwRsm";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
