// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "CqXTbAnZcoz6WRFsN3bCe5f5HeWeKyAtmSUhpaTTmxzb";
export const coinVault = "2L9bgd2ygFv34Nb4r2SmYWn69CMhTFoPByNcF2DzZdkb";
export const pcVault = "A17j1YFw3RRDmrBkio5U69xMFo4SJzLEJC5dYCkbayCk";
export const coinMint = "ZU15VAb8TJJVryTWX3sAraCT7zDFA7t8EPhX6uvJEru";
export const pcMint = "51ypTSjAebcwqswgBDGuQjNqMzuQJkSTEXSUF1R1Lptw";
export const bidsPda = "CrQJ4FZhgjiptCvi6txAjzkfbeypzT2yjHk1mTxwBDK4";
export const asksPda = "632mEPvmycqGuB9dKXdm9bRbmiEYedW6WjKNYwpxkC2Y";
export const reqQPda = "57MWF9hTt8UF8t1HdPPDyVwN8d8y4CtCRK3vPEsAVkuw";
export const eventQPda = "4AcBgQcorSdFPLZ4LnR99LvFMgsBaKb9DWnc3HTP3iA4";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
