// This file was generated by a script
export const programId = "8yskqQf58n63JFYLPHhp2dtC98gNYYsjEp15XmBJV8u5";
export const marketPda = "5pjdSkZFEiTVrpQ9d2wWjGizQakKgUYYiC99MiAQEEE1";
export const coinVault = "14SNsEEVFGSSDpVeuzaG4XmVrJkJTvnvM8aVVGKNdCPs";
export const pcVault = "7yYtUVSyqBG6aBYBAhHTtNkF2oh6VTX2HaMHU6nVBoDP";
export const coinMint = "AJddMoRhQyMFyXsQJdybHBJXGniRUf539uTXbiNkpmRm";
export const pcMint = "67GQSF65vt2fJA52TRCnFxUy2nyX2u9DSp4vVqJ9NoZb";
export const bidsPda = "59DY9XvemCRKCaJnjaJkPc9Jau4uHgYsuuXMGryPiGjH";
export const asksPda = "7paXTi9AvfHTkDkLPqEwBJZdFuhBovZcrCYJvNqTGC8F";
export const reqQPda = "6M1CyFyv1QTwNSM5ZQRuXS7Z1d3CxsHrKiouwoHTEuQ9";
export const eventQPda = "CV1Wy6zaMVC16C3demTwWSrf9qyW74H4aMNDdSddMmyc";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
