// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "Atj35sTUnakdpmHcjJ1zMwfmwV36osWArQ6T1nwvXAXg";
export const coinVault = "CoVc22ag2GHhUXP6h2pvH44mMZSjkT5c71yQGjs1xrs6";
export const pcVault = "ALWdxcpDSgWkzTnL6RwhQ7yWZYHMKJXbCF7e66GAu761";
export const coinMint = "42tfqYuiMhqq2cC2h4eLMcA94s1r9jqMwfXgK4U7uisG";
export const pcMint = "F6gn358BcfGLYcF9tT3Gv7u2vz8dTzmq8FkYdpXtuymr";
export const bidsPda = "FLcMjRZevfsPoA8Gxf2SNAd5m1phBKAde72bToL8h7wL";
export const asksPda = "DSK1ReYc8NarAoeUeZF7EVSNgeLof7VMErNxQfhWvHTx";
export const reqQPda = "9ZaMTXuup7fSC5gkJ17pAytya8U5RR9dgxb7JwecjCjd";
export const eventQPda = "FBBUB4zgfwfLvbQbuEUbZsfTmJV98MzzAK2NEnn1hjjF";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
