// This file was generated by a script
export const programId = Aodrp8JRS1tCywT97x5ytaoJYczv44JYtyBHDJGLCx5m;
export const market = E75V3pZ3ppjw1ihWeqtan5KE4xbH9nJKS7odEYMFomzE;
export const coinVault = DQ77ATkR7vYLBCDZt4Tsncbbys82W1vyXwQaFfCVScRv;
export const pcVault = 4TtMp16uxLjdSYFTG8MFWqcvpjchPQ92bmC8WopekKn5;
export const coinMint = J2nP3a8YLGvstPECt4o8uAKeuscACfdCFVaNFCzvgWaC;
export const pcMint = 6AT6WTVs8AELU3MgU4zrMhsuQqS92gCpc4WeCASMbPLL;
export const bids = 6qhSwE1Ecf24K44UJqSYWBiKTJu9VmQCJ9CJBpbTMo71;
export const asks = BYqgEoRqcHqAGV99gsEEV7ZeQLQ6Kx56mLPUt5DsqbX9;
export const reqQ = HTkMT8NsfgivufcDGw2oZuhwtkLLfuAc5eUF1ZxumuTA;
export const eventQ = G1z7DpoZJWbBhb9e2Aw7LE4Qa33StowhHv2axJzjioCN;
export const authority = DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W;
