// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "7WNaRMPVP84kHWyML85Re2k16GRHhZfpJH66tRvMvgab";
export const coinVault = "HP7Q5i6GNo1upwMVSHnuY6373U2Y8QPWzWNqHgGU3e5B";
export const pcVault = "JCLc8fZWHnvta5FKrFfBtwHWMGryvEkkWgpbbzZV8Cc2";
export const coinMint = "9yveyTX7JU9dnDgK4NHbVmEm66r1hWD6Wod12mRDfbrC";
export const pcMint = "4YkcadxcjwMF7xPxqegmNqv2uCw9zmacC5JMFZCjNyMK";
export const bidsPda = "6vzSDV7HXapT4DGi2C7Mh4iTheehhoeUqV4r7tGrbgmf";
export const asksPda = "Gbn7A8Lr1VUHbfmjn8BrgRwSddXgvz5z9ugP8enddZL7";
export const reqQPda = "8gcG8riXRGfEget2NY8fWaLLMAszN5kj5UdvDVbL76TQ";
export const eventQPda = "2fcCnqaV5F1FTCxKmtKrpMtEVEF2vZEauNpZFzakBdXw";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
