// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "3UexmFPn8efUk35jVxZPj1FtKKU1MJDCXPbX1a6GV1eJ";
export const coinVault = "9VfxEi65yC6ZWUaVYY4RycXPgwB7yjTvRCdxgpBHHFYQ";
export const pcVault = "2qPqedFMQsnjL3Vt12cmAE4EMvAvNx4d8pzgCcU8DMwa";
export const coinMint = "74yzkshhUbJfGS3bcyBoz9WG78aLAHm6sLjFtzQBzEnR";
export const pcMint = "6TWjDgb6E1LGVdefJzSCbUa5GSjcAGvr7pgqhHAUpoJH";
export const bidsPda = "CkB2r75Mzo1WUPwJMz6k68VNuzV5x4jc2DqMaUd9Erxj";
export const asksPda = "GJZrLnFZS2aDctBUghJDyDuvJ2GB5uDGhGkR4xy5tM6V";
export const reqQPda = "EzdbVyuaNJUSYQXAg7BvWajgXX2Z911BFSGaZs5arDWv";
export const eventQPda = "D9FGgW2Eyv8fArrMH2V77amjcEfSFWuoJqKqf9mp2Gto";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
