// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "4B7EBAQiH56So9JdkLBTsRvhcPCu8inxv1ErcEw3vZ9P";
export const coinVault = "Exn55k2CwLfjANw9bCXBuBzGX5ddiVKHxWEdc1tkx68D";
export const pcVault = "5U84EA35nD7y3AucwDiLHVXLAmuCxq33aa9gEswDGLdw";
export const coinMint = "7mny2LkxX8xpaJ4cMkUeMseUmwTw8diMFZAYQ8cUjJBo";
export const pcMint = "7VjE1kfAY7XJcnRLsWxsrrrbbqyz5AYr3K8MCix4afQ1";
export const bidsPda = "Gxd5ZhMC7XzZQCmYQDti3b3SGngVf1Te2tMBc1PAVHoU";
export const asksPda = "53HztYZTiMAw3gDjPEp36dv76uLsmwxHRZVC4fmQntVq";
export const reqQPda = "E2VmWSiQbtvwK2fkv9CapfKwqRXdqhdhvRHDUgApS4WL";
export const eventQPda = "FcRoa9PUq5cNYEBY5hS8zWqmMNc7YJdgscFqjZ4sG4fS";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
