// This file was generated by a script
export const programId = "Aodrp8JRS1tCywT97x5ytaoJYczv44JYtyBHDJGLCx5m";
export const marketPda = "6Qknv2ErTKihBPh62LyCEyn64kzF6RGqUrH3oaD5UNrU";
export const coinVault = "6xKYz1KdNd93owUFMb3zpki3aQCJiyRVMusXYRwLJxpp";
export const pcVault = "HJ1KREWnfBB3UCRqKeyqCGba3PNaEnU74NXkZ4SPLwXz";
export const coinMint = "5pWfwdhVfSuvC69F8f4DNyrE5cCH3hKzD4LoBPJFswLH";
export const pcMint = "EMTgXX32cUDCrHcohW36o4RCFUXs16RTeDBjBsNMNLst";
export const bidsPda = "3ymaZiwhBCH432bneXf6QTArzFfCj9sLbeNjTwPgkD4E";
export const asksPda = "8suWucwJL7vSUw55XWZhNVsKjoHXaGr5af7FRtmPGWv2";
export const reqQPda = "AcwzJuoQnwWcjhYpQvPsX3FQDMkoZBfFGrStd8ZhGkVt";
export const eventQPda = "EGRvmgxJDXtQ9BYxccFnNsFD6ZG2SpQF8u5i2ck3D4tv";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
