// This file was generated by a script
export const programId = "Aodrp8JRS1tCywT97x5ytaoJYczv44JYtyBHDJGLCx5m";
export const marketPda = "DqMA24rZPuj8eVEdphhHbxHpgJhqvQCGUVpYJvTPMf9g";
export const coinVault = "58PeHwuFozGTjVTPQYaN1kcV7iZMUfHtBkN3Q9Sx4qkG";
export const pcVault = "GjamS7tVWHExnMPtyysePTmrxoZa4UfXsSHypPKqHgm6";
export const coinMint = "BvJCsGVKvtuXswdFAVxAK6ZXToiiEZQBdgKgLigRqEsE";
export const pcMint = "EWcvacstXd7wqLCDhy9mKyvkmuoWPeMPgFXve4WdMWVf";
export const bidsPda = "7wdhjFVduoRzJioLcjonqCZjCHJNnEo7mnojV9pysSgW";
export const asksPda = "DCZKmksiAWF6w8aP9xwgrgdmX7crd9hdNN9xMJLvuLt1";
export const reqQPda = "zgY83D47HF4KdJqYM2kWakP7aQBfjQrzytK4F9M8eAG";
export const eventQPda = "AtQ78kq4odjP6caTZqQhvCAm2EqJBQ1TwhobzjPTJvdt";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
