// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "FJw4F9RmwYTijM95SGY5qkhwvmB7xPL9LgaFNH7iC53E";
export const coinVault = "HrymsiEF66QWHBdcZ1s5jjun3a17hRE87ZknX9x5B9WA";
export const pcVault = "BESqvZ5DvcWLJGLcA1TpYpRGwZNLQN2nKrkKZ11ZYiqC";
export const coinMint = "3XJXoh2qai73mGzKxBLZjm1f4gRm5d8LAK65G6qh1t7L";
export const pcMint = "HS7uUGTAtd3aBguQsKix41sbQVkdTu47fcDr8W1i5KPC";
export const bidsPda = "3UR7LNjoZ3qw2jUPD4v5XtpQKtXPaVtZxvgPZA4etZ55";
export const asksPda = "CHxAWfVqkot15C7ysMhwYZd7VrPEWqScozxFTeDhWb94";
export const reqQPda = "ukWXoVjdHpo68BiC94FTVVGqC1hvdXJ86tJPtKWADLm";
export const eventQPda = "BCiVb5msvxWYZJjdGjheXoJtSwnwp2QbmUSeAEocRgKS";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
