// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "C2mUtJr8TpuUC4KnJhBLGUgpSBG659Mg5p7i4JXEPTnW";
export const coinVault = "87dd8XG1QhnSamm2ftCtmPkHLz33BvVLo1Eqchw7AmBK";
export const pcVault = "5UWosBEVgBTrxxUmwffcCRT1XfNo7tpXoGzpmoBrCQJS";
export const coinMint = "6HYreYp3wGYbcWTbVPUVM8azPDZCNoXq5hL9csNtwzbP";
export const pcMint = "82GyKDGGL4xuY29jMqkawVY77aZuwrhC3VTCcGqo9s9z";
export const bidsPda = "AVP73uBHhUXLuNV64JVPnjGdgYZyh5eeuCGqzbBqzCp4";
export const asksPda = "HSp3FMnRRNi3bCfqj1usAXN1ecYqfPsejWRcouziE3N6";
export const reqQPda = "7dyYZJzxyvkMEbJoMAF65DLyGHADpvVg4dK5fHzjoWke";
export const eventQPda = "HFKYJwaqZwAwcWXhxfXS3TVK4JQoVmM3XvkwA14Da2T9";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
