// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "ESJtymTM5RTEoiiByiYyfUxJhG6YKSEKn5E7UQgYwDHD";
export const coinVault = "BoZ8XjviFo4sVeMftitmXPyQCLkUHwEfCF3CpxHLLmYe";
export const pcVault = "1MPSPZN8FyL8Ya1NLTXgnQcWapQXJZL8mZHMyna3xJY";
export const coinMint = "Db9hA6KkBkvrFS5iRuzhojfW4hitrDA9zbvRxk8FXbYz";
export const pcMint = "GDyR6A5Vh73uS1TuAtbsbADLiqzLSYuHD15EExNKjPJZ";
export const bidsPda = "8Kgpe232i6RdnUn1Jk1ShP5rAZ9vY85BnsfxZSfYX9T2";
export const asksPda = "8gYoeuvWBKoWerWvJgKFPUooNYwVcupbmNXgoYJhUoid";
export const reqQPda = "49yrGDwUYHUMvuo4a5KnF7WJC3P3sNpoizrghvY2A9v3";
export const eventQPda = "13MM8yEtuUvrM3qybScRGUTUEsifYRiaMQqQ7dLnM8Ef";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
