// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "2Nc3AdpECCxX6qQkqLg2TRCh9He1THXxGNJBDgpezxW2";
export const coinVault = "HWaXQUq9tCAgPoawJ4sfCQsioXskUr84h1nuWgpZF4st";
export const pcVault = "EvFLPwUKLtyAhkzadzr15BUPN3RBDJtk8foevWfxRzuS";
export const coinMint = "3CY4Hzyhnf8Hpdh8tY1kdqLAXGqxTDjKivHQQDcbqTJz";
export const pcMint = "5qV1t3sFa8qReK4wKdfzsPZUZ9kuDMacDs2Kz4XifH5u";
export const bidsPda = "9Bb12g1oDVH5P4GrZhxgwv23fgdCQizB2TJJbTuDZ9G5";
export const asksPda = "3X3FkQ5ofWwJUXusGFwZdeNLuCUPD4N9hs5BHuSHbJ21";
export const reqQPda = "59TyuvuCFqy6hV8mgYELt5W8EaJkS8sK1Yt8buY6MwM2";
export const eventQPda = "4TSKHHjQmoKJQi57q4EgS9gaMgeP6dcimMGhnbwvMpSP";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
