// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "CcjHZznD3BKJw3mErMYDqLgz7PUXMZAJYwhY8uss9GcN";
export const coinVault = "9TJty2B6JxNiemaHxzbsH3NU8umizrXeaLhem5TfrXQv";
export const pcVault = "5YkxZVzSDEeyGk567mqofMRtaSVrRWBUzotZRXaduEFm";
export const coinMint = "5ZCYuog8PUtjgFDez8FqcsYC3yQdetTDHQ1zkFdPyYD7";
export const pcMint = "3AZkRLmSvvzegxGWkJkWhpE3FB89RFujCh1irH5T6TFb";
export const bidsPda = "BqHefPc76owfVShVtiyCyCVG66wYUetocALgCBocSNFb";
export const asksPda = "FAQujwifAYDa7zUpKdJJMf7hVpRFiVm1hFRfXbG8XRK5";
export const reqQPda = "3LUkyuo5yGnDdCmqzWJk9wj1FddcrbWT9gLqS2iCjRdv";
export const eventQPda = "44WTnJsN41hP45RakbyThVzSwDDYftTJTraj5HhpDjLX";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
