// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "5d9Dw69zKDVX75Ch3nnkeQxYT7oQ17pqfBXbhMKBR7Le";
export const coinVault = "FFCnPUku2RvovJ1gfCn5GTbGGtFs3CmyKg9Qb9hxjUNN";
export const pcVault = "5uGexpoNXHiMuuyNd9wU5QD4s8GLf28cAii2ikbmf7jQ";
export const coinMint = "A3a36z4VBEjHZ8ygrgxnCfigA8JkmvzwdeXzTQCAC4NB";
export const pcMint = "3zWHeaWYcGvK23ebYeco6xtz7BoMVFHKDShv4wv99HAT";
export const bidsPda = "H41xkekPCJdbw9s2ZivSfikcy9YCN3FcTgooociwDn3b";
export const asksPda = "5ERGzVPS3YzFdcmV3ELhYZXnUD3EDfdc2aZRD27HkLtG";
export const reqQPda = "98sRpc5bohbSycvXxZXY8CGQhEMBZxSovBKxPXPh5kud";
export const eventQPda = "12yeKZ1Y76FpvEowRr9yLY2f6LpTykMmK9rQ4QJWCsmF";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
