// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "7s8e25mghpbpr3LpWpubvDvmCyDpNBM7Fj3bjuehXWPx";
export const coinVault = "G8QsCMRfrwVtQTDUVrSF8z8bCeEL3WwEYUfL71P7rdL2";
export const pcVault = "61DVEz66JyY9ytRjfssQCHPeXRDs5zm2rVLKabUSAUWF";
export const coinMint = "3yPpoGa3YGMZANnhJdbXbFqNVHxXXXqwy4EDuMcQexnk";
export const pcMint = "JDeq46FriSHJhiPKKtduzgzAc8UHHax4KRU1j1DJMnGP";
export const bidsPda = "Euh7wHNtrwouRckt5vQiuo3QtkatrSqdbzQSmQPoEDa9";
export const asksPda = "HGN9wBYD3rJw8J1s7NpJDNbbPHVD6FGC6HVWhmuexonB";
export const reqQPda = "9RsWSgQwMUSvV1GgUmbjpmnbyTCG9Uc4yPhsh84R2tf6";
export const eventQPda = "9FdhGfeVcQvZCRc8ZzKVtShTHVa9CpYMYqYdHTMUxfAb";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
