// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "H5DsMGa6tUFNV366jBUat2mhpgWkXwGu1wE6oL1es7PF";
export const coinVault = "Fw2j2z1kv96qKDXH52qS6Ygh4rxTtYVWKuzKQ5gv4Tun";
export const pcVault = "E8vH7v1vpJCYsVAy5CkvQiuMDVk9BnYz2qw4R9PfU8FW";
export const coinMint = "FUVddByvaL7xmFxAh1kEXqs1n69wTBXjtXAheExDET5t";
export const pcMint = "4A6Civ7r7iBywHdf5tSb4DMnVyRCi7r6r4GScWA6XDm4";
export const bidsPda = "EUKxEJ9TYu8rVsmFCvJoeqbeUsTwccXPZgNrX98uzXqe";
export const asksPda = "G6321QXfkpFmv43WSFGdUhRaTieYe4EsMTrb1QmvcEJF";
export const reqQPda = "34pf4bXyF6C8WiVfcg81YoLVv4E78nsiR2zVuH2RXt8X";
export const eventQPda = "AEYqHUd2SrnQ9quzPEziAVRE6QuvHLU4538ddku3fSsA";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
