// This file was generated by a script
export const programId = "Bk7e6ygLwT1FoMu19HRoe99BSE5yf3WATXUVzvQGj8Un";
export const marketPda = "HA1eBxzTUDZijbnH9HbY4f8p427HEghV6GfdeJgWNaoH";
export const coinVault = "AuEtbfnMhtB14eiFMGdoAwwMtgDjH59bJ382hb74EWXJ";
export const pcVault = "GaMimKMPPPY9BF45s8KpY5bgZsdz4Jnvp3zpJF867rv7";
export const coinMint = "2fzCkhZeHguoFhaV7cXLAeucJXnHhyCR3muCqNVghzjJ";
export const pcMint = "CdwgfXzgfV7U77bd9vUkGJa8HoSZWaA1tEBWjWCugTAJ";
export const bidsPda = "HUdEdEpjdGKErGmAkiapZC2HrhCwJ3WXA95VQkw54oZB";
export const asksPda = "DvmDmaGiAycKyoTps4zJLf3rT6FwPbYmW7J3DiizmA6D";
export const reqQPda = "BqUU4tQcD6XSmqWzbXnE3wWbwhQqN3RM7B5f3ETMZnUx";
export const eventQPda = "6sVuNW9gf7RG9aZPvLYbFnAKQE3FnihhFixnLDJ7yawk";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
