// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "otYuGd4znEHwo1LFAE9m6DbYsNHpV8354eqihCgA9B8";
export const coinVault = "5KXhryq2vZiBYgtSpSCPJnb4EcZy5ts4N4DtRQAbJ76E";
export const pcVault = "DBvuTGNWvmPNdr8nDyAZH4zgsumG3xHX6YnV2rs8UFYn";
export const coinMint = "AX2fW79uRw6ywk8NX8gjwDcRnPUEqWXogyuBc3NsTRyo";
export const pcMint = "GeF8JCEg8aDxHmueKgUGadVR7XmaNtHAWjpKMZMpWCXC";
export const bidsPda = "BNEPgyRNd6uCtJc1UwpU1oKUxWQttCHvJPxNgpZmJoiS";
export const asksPda = "5KCVExEAgjx1gsesefUhQD49PJZHXtx9sLLyRjrBNj43";
export const reqQPda = "CTfNqy6gm4ChMKujtoJET2Cu8Vmez7yEshNPemQ6MJVh";
export const eventQPda = "3nAXVbJ8WgLE42kaHbhaxfxNSooRogvaqE7VqUzyu1Zx";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
