// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "7AX9b6gtpfRjZBgUhCWWuhnpRdvGdj7ZjYqxeD8UXdy1";
export const coinVault = "AJ4PmxehU9daStke1t8segFJb73pND6bnHRy4jR8oFyH";
export const pcVault = "8sXa4WYXByEytKTm7kj833hL2tJUZyi2j9LqWav7sTEa";
export const coinMint = "DHwc2234i8HLtNS8jbFWPcCdc4vUib7vqT5grsXRJM6u";
export const pcMint = "HADMsUvZHy8bV1EvghgEvvp3NJpTPP1hKYubUqMVszCo";
export const bidsPda = "2Wsp8Z3kyoawPJkoSeAyTNNB2vFNDVkWXGdcKH3y652g";
export const asksPda = "FVjAjhmR759NAwdDSSnvsgnCJoBJuht54Y4ZZtcg6nba";
export const reqQPda = "4JubyP7HLzYPKa3qazufKffo8wYgvjzcZNJYu1ucfa4x";
export const eventQPda = "5CYmtqZGJV1YoSCFCJmKYJ6ZnDGgNHbrHfhYXD4UpgTB";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
