// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "7qnwZAwnL5CVg6P94Upcx4iX71NWcaxMazKBWk9H2o52";
export const coinVault = "Cvs3SxQ7o6ZwkPNApoUtYuTDz9umZzSFdVYURyDMckjN";
export const pcVault = "ECfq3PvSarLuYcBEhBJUNGvm4qmDRFDgDizGYat1uUWU";
export const coinMint = "2JCtvLDbDqSv2WSrSnk2UybmzQJq3FditwwSMtCwXQSL";
export const pcMint = "23UCrwGA9ixYCJa9U4cQjmsFosDHwf5awuHwJpM2JVFY";
export const bidsPda = "3U1Z5er4wcdCB8NdJJiEjsjcbKMVZvxcPpBdu47V7iqB";
export const asksPda = "HauWuPfv8pc6e9dTg2UhvAJsZ9ekpXZxVedpEaSPcbPg";
export const reqQPda = "FxDwynbZF74ifgx5ZH8DfTMCcMwrRA5Kc1HGbEeeRBsc";
export const eventQPda = "A525xNjN7geGDMuuVCokLrNitS1ZjJ7ngtYEtCM6zqnN";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
