// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "38WSWUdSzMfuWgbmif5k9ouqDpyT9JoJX7PYPiECjDro";
export const coinVault = "4LAbnttpy4BMDMYEJkEdm5qFn9kzqeFCDhQULbAivdxY";
export const pcVault = "GFHc12biVNjiJhcdSqqLYZL2zxN3KgBBqpJzUgEAMFXn";
export const coinMint = "23wmJHvpzyQVS1uvNHGdfSKB5G5ktdxSMCbZBf9tEjni";
export const pcMint = "C1xxAmwZZtnNxU8wwb2nSLWmaYs4z8GMRjk83UyQcWGC";
export const bidsPda = "89SbSj8zNzLgXK79vSM1oYsdmgCtDoNX5Y3ajH8cRBmP";
export const asksPda = "2hXp4Cwzn9Nu8VVtH5pz9JbyexdEgZPugLRkKgYNpov7";
export const reqQPda = "BNGW8XLC6ygpcojvi1QZsYc7uZKvY31LKMkgEvMimQs8";
export const eventQPda = "2SBXdRQhZ8967TJRg5StTtympDKqtd3hu2zn7EHzbYFi";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
