// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "3vLES2X7JN4ie9yxyoo4Hz8ewi9BaZrMdxh1GutdbjrY";
export const coinVault = "B4ck24mRhd9XBprX4tDMVQg4QNFGkRTjUS6mZ6q2W3me";
export const pcVault = "G63cxh85kSku4Beyr3hFkE4ehjQgEhiKBXpgdmqVYr6V";
export const coinMint = "CevixCRU5ArFYUV1N6o8Vzd2pWJgyaz3jQAqC2Nb8fSt";
export const pcMint = "687Yy8WFCD32cWfKmGkCWT6FCh1G2kdNB9GbVcUyzRBT";
export const bidsPda = "Ci6EthfF5e9Zequ3aURU3pjzVBsWa4JrrnZoUjtPQ6B5";
export const asksPda = "2U6D1o26Sb9JYSTNyDkjrn1a2ZH1X69xC6AoB9nGP1dF";
export const reqQPda = "HfvQXqnp87uJy9YxpyLYJRVd9RmUHVzzhL2k5K8w5gTC";
export const eventQPda = "EKUwdyKPM4xGVQwYfgRaj3RnrZQiMMxumRuAeZyipxxr";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
