// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "2rvFphPDeRstRxk91PkSf3emVeuRCmrHNXQZ6bJhcvML";
export const coinVault = "Fn2anu7B2wrR9VbLokRuhft8PHk6vMZL3wpHHRiLqoQf";
export const pcVault = "7eXVR5mV2HJXNeBGJpep1qq7KB66hXV93LtArUjyJQx8";
export const coinMint = "9VsLsqXsvsX9eq9Xm5bcCZGrh3at6Bc8LXR9d7FZKmDv";
export const pcMint = "BRsw3XRZ2kCNqL1s5ZuRKJo6kht7rE2UsdE7MoSGyNDF";
export const bidsPda = "66iUErP1Ld2QwSPQXW5eSfojDXHe3ScH9RT89zwwm2SV";
export const asksPda = "4Sszq4D2srLd8EpNkfxzan2Dq2iGDSkmFw6DJv4Grrg2";
export const reqQPda = "VWwG6X1hAqX6m2BRGAr1Y4aatMhroNyAhjbz5kc1R5u";
export const eventQPda = "4xRgPEYv4fbGp1vNqaXqYS8zN5QjyzUXY8Y7f2woCxwK";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
