// This file was generated by a script
export const programId = "GJsyZs9cr8agF6SLiLfxiS9A11Avioe3JVPie92N4SNw";
export const marketPda = "BAx9CsjCTXUo76BGkphHaVQzGrRmdLWMA3HeW3f6Qna5";
export const coinVault = "BQBdQssdG7CCHkaG5fvE5yzY1fPnSYabmFeSgRdC7617";
export const pcVault = "8k4noyvBZCEFxEpdTJa1U3bUXyTXGgnkrQkZqxenhFa3";
export const coinMint = "5NquvG7Xxw4Ff2MY6D7Ac16WoX7K3c4UmQoBWktkoJpZ";
export const pcMint = "F3nkzSGfG5k52aFwVrNA1UBhVfTRmjoph4HB1WnBSQAY";
export const bidsPda = "5RwwkJNJvcpdBCydf7MhaN9QEmjin2V7y4BiTEbYbt8M";
export const asksPda = "84jjnEvE2CfC1xNUbTKyaK8MmSxtEBBdgkPM3K799Ybi";
export const reqQPda = "ECs8M3wNj83frbGU5d1aCoPPToU6vXHt9dezQWkubkdG";
export const eventQPda = "DayqAmMnxhtN9VAcjKK2PVDqKPYYuAyQZbsVmGXKYUms";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
