// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "7Etjj6jwZG2jeyCwq7o6aMsRvHQA7Fmuszow43nyTqL8";
export const coinVault = "8fG7CMwtjEkLZyFzcJkyD2ycjRuPTwU25mQw3g12fVcJ";
export const pcVault = "146n3EDKWS8cRudYHLeuxnsm4NKi7T1cFyYp5eyUsu4T";
export const coinMint = "CP1RarcEpG7ZB65zAfLyPYb35YsFKCvMdN5FEtxMqHNz";
export const pcMint = "Bbs63cKrzBrdyQgYvdggoZeUhc12p78WTLrtXh9ky1qa";
export const bidsPda = "6y8mfo4rg9CCzaJk5mF7EG7JVnYNFzV1Lr4SZKmAS1GU";
export const asksPda = "AQKwyQ3eVZTErrnzaW98kbCAJvwkod3U8HHAKgLzMpCL";
export const reqQPda = "CL4GoTjs9dJh5HxUFFoSv8KvL23dMRYFaYJWMpJxk1Fb";
export const eventQPda = "BiHVgmJcgzxkx13ZY87B2RxMhsdxRjypsYKMCee4uiFH";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
