// This file was generated by a script
export const programId = "Aodrp8JRS1tCywT97x5ytaoJYczv44JYtyBHDJGLCx5m";
export const marketPda = "BVA9cAT6DW8guBeELxkcZuXkMtuetGGwNruabU7wdxaM";
export const coinVault = "C4WcBxa9H3vWK61nSzXdTatPJgxbN1PpsWYxaL4fhx6F";
export const pcVault = "Djj4PD48ExYQzRXPeL3s6rmZkyyoV5Ns2VvSnK6Z2ms8";
export const coinMint = "G6syvovEQ2G3wg8TuzZMPWJbxPsh8sLUsbupmAyREJER";
export const pcMint = "HAsQbM2v7yoPwRFagCHoWd58K7WsCaPoA7vQFoL5AUmJ";
export const bidsPda = "5WjH1TctP5CoguPQXnq3MaoAjMy4v68z88M6wcZo7HWV";
export const asksPda = "6a6rZ4ThTZYjeoT6715Ukm47GssJtsMraM8BmGfb2iX4";
export const reqQPda = "21J11XQkaie79urBX9yfH2SzgDgWT5CEeQztTX2Qryjm";
export const eventQPda = "MJHBby98JJvLNx4s846kBxwgsJvZPgrSDT8BjTEQ7iR";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
