// This file was generated by a script
export const programId = "VGwPEHBUjxa1ZQyvCAJ166TsKPYCWKafJoDeqdXqvdJ";
export const marketPda = "6B2WdpXZrDXKCDcQR2SnVGwaDUfEM1p1CLNamx11vwjh";
export const coinVault = "83YDYVzWm4qp3LuGXUBuHbYqFP5rB3rroTr7M4of6Xjq";
export const pcVault = "8A1hZLwMTVGR3Y6GtYm92fbeeJLkjobkU1GqivQz8N2C";
export const coinMint = "G64hrevYeR5sVM98N2LEzXt8vuTEGZYmoo3tALPsJWS1";
export const pcMint = "Bvu1zcRxwzZmMeVTU6VdGvQeArvz1RFDFrNrBSVtddDH";
export const bidsPda = "8eirqjEhAq2EAthL9TiY4QZbwHRZn5mQHuUnAiqtCBML";
export const asksPda = "F49PYUDqTcR8ZyFEvouFj9YTjvwajnxcbLQ7nrVMGMeA";
export const reqQPda = "91S54ySFCePjU2qgusm5zayDLBMcyVxp2cdQJdhRX7Kk";
export const eventQPda = "eRyjCiG5JLGQACtxH1icBdXPTFdoktEundJT3VxYruu";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
