// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "5b83QkmsTe4nKZe3R5Uz8uEx2Aj2uyE6FekeSVba4NXM";
export const coinVault = "4GtTYTvFtVjs8Hbz5uvshu8CDbgeBic1He7x2kvjjU9b";
export const pcVault = "8LCUcFxNFqkjSzhgFoLTiL7g3nrPD1jyYMSf9BRu4837";
export const coinMint = "A2Mr2BWT46ooJD8u8sGP63n6yaDH5FhyPLRbRjkdjYZm";
export const pcMint = "FTfbtBjx4Znz4u3zoVrUCADPCnn9w36xozAnweU1TjHJ";
export const bidsPda = "2WSaFhDno9SWjH6Psz6gTR6CJKf6PDc4cJqXoot9TfrE";
export const asksPda = "8eQWaHUT4gc3JALtS1YXeMswN7fUSFz7fHsQ97cZodCM";
export const reqQPda = "Cb15xxPXKN5Y3o79nMxtVrpDMwADK2iB1Wy4McKtBZaM";
export const eventQPda = "7tEdCHmQmEssNWuz7Sxw4SqrTJEJp9pR7oj8fSMLhoRC";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
