// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "3qxU6DLiKym5mHXJwADoJjJ2YTb1Jrooe4gJskV3TShi";
export const coinVault = "ASyHDCYCTahpamf6BZLn9Z3jL6ovVk4qZa8j34TeNhPk";
export const pcVault = "7R3v89cVSsdQdawwf8ZmLEa3GKEpyEypsK5ZJ9dPmJVv";
export const coinMint = "gmBsPVxSYFCcj5Cy15eWp4J7zC8dmXahEs6YhTBF6N2";
export const pcMint = "4WjhiU9pTnk3L5zoDxN1PGAXTREDPbKfkVKgvGHzWvMV";
export const bidsPda = "BjJabE4z4DoVPZzBb4ucnhwokTcZAKZoaAZKeEYSVArA";
export const asksPda = "2deWrHmiDipq9zQwxi3kTHuL6KxQLEi71eBCzkSAiwsf";
export const reqQPda = "6ZjHjKyQy7cQeZQgo8z4GyR6hd8rSeGVsrvL2ZJrzJnz";
export const eventQPda = "GCS38762bmqSjy26GPmCHPgab6akeCHX1jFZy9Lcj1rj";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
