// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "6Lr7VzzeC8jRBjBtk9J7s2Z553sAuvpENvV8PWH9dF56";
export const coinVault = "HaasihRdhKmDAXoVtPCXh2oxsBLkZrqCNazwjwW3wYnY";
export const pcVault = "BB1FDzfvjYVmbnd1GAinDJftEH5LEjgH8iZSRKyTBDE1";
export const coinMint = "HnHMKWf3Pw7iTqRFkayGhG25mehRf2sZMrRXQzRGuGRu";
export const pcMint = "FP5GAgz4PctV1V8oKzQZ63ustxaTQyppbN5uVNWmLAHN";
export const bidsPda = "9bH2kmxPHrSj7HgBNBNN8W1yj2CmhQBAttQS4oZ95RQo";
export const asksPda = "tJjrLV8qpq8CAxLm5t9YcqENtvQ3akRRtH7Y1y4y4SQ";
export const reqQPda = "2uHXqbwetPVkFAgD195P2GivRsisZPMUGquNydf5sftM";
export const eventQPda = "GCKqmy4JjSEz5HkqFeRBEmyE164b6XZSQhiUnjVD3HAr";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
