// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "E89ATM7ueWks9kDgTCiXRZ5bRy5MWdwGykPbgUY5dKSx";
export const coinVault = "14fA5C7g2A9UyAQwzpjAC8yZnUH55iTQPwVp7mXsu4UQ";
export const pcVault = "4UK2AnAR6VGQcxxjKgjvemqMbJxNTHqdLkakjvV9WbSh";
export const coinMint = "AvRuA9gD9DZq8JUKXCMhwNQqnZg2fQdbceBSqK1rfoqF";
export const pcMint = "9YooE1RXb7gYysNKihQxVhzYTetLeT7TUkF2A12xnHKE";
export const bidsPda = "Dioez5CArPFJL9BmqmF2CUnn45U7gUfydg47ay1LiK82";
export const asksPda = "C6gqSKSFGBnDwVcRV62DpRKU1xnVQ7cPKGwarRf4XLJP";
export const reqQPda = "8CLFMtTMRBTLcKnQdg6QteM8K7h9DCJ8HYoDrZn56u3n";
export const eventQPda = "38XCCMCidc9BTQivpTLbxMHp3pakhX24TBrS5EVBxHNN";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
