// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "D36a6FjXZ72WDHS174sQy9yxavfr49jQuZ7w2k2j7vwx";
export const coinVault = "61kQR4k7TCEgqDPuqYDxifxQzhycitPrstPUWzHzaRW5";
export const pcVault = "EKjvS9uihyATaiyQSFQoYoFZaPguiUAmuPfm5dUhYCXd";
export const coinMint = "4Y68MxAgYjmZHWrfGo44MTLcy3AQNbS99tqsWcNbxHn6";
export const pcMint = "526NvKiApZQ6VpZmRUBLYhB9fgH5LcUi24SfFAZjkPLV";
export const bidsPda = "DqRmF1P29f43DEf9zXer9rAifJdpkkKbkMvC913F2aH1";
export const asksPda = "7dWfcejmekAEfnCCTy4K5qBKkUBjtWpHuXfeaWoevYb4";
export const reqQPda = "9qbfiEEd2ASgwjAFhxhLjR4g1CxdcsALAHiUPbHCU6hG";
export const eventQPda = "E3ase3CB9WzQkmwhKbZQbAWqafE3bHfe8ZuwA31DJuS3";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
