// This file was generated by a script
export const programId = "Aodrp8JRS1tCywT97x5ytaoJYczv44JYtyBHDJGLCx5m";
export const marketPda = "F2M38rHFVsxqs7y7BbrrRnHbFak55APTegVcPwkC8A54";
export const coinVault = "GfUneUQViTs2xL4kiU8WPctDgJfZrL6MziV2Y22gfgME";
export const pcVault = "2rS5Lv39QJj4W71fD3AGQdrJHh9R5oqVQ4nMvQu3ZvkY";
export const coinMint = "7a5Ra2QXKJYThXfdpNjqwdzXJEbCS3qgMvuzcA5NtK28";
export const pcMint = "BNoBedxad31AM98RjmPSW31rJv8crLj9i56UYYXtdUdY";
export const bidsPda = "BVXUGC5CmJ1GQ1jEaXq549q4CAp1sHqZJheucgRYp1ci";
export const asksPda = "B2uWowTcf46zUfk3Tq5GfqmUFAt9VE5g8P4pUFab1g8k";
export const reqQPda = "2pkYhhS1SCpiJDPsUhr1LayBVfviKQjZWiC85wTuqYpg";
export const eventQPda = "HKtkSCmLzqotZfNwLhuxZPwQFrV2Fvpw8pCJLVdAhDUH";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
