// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "DpSP5iWDavHqvdNMtAgt2B2EeNa7BG3vKn6MnfTW27bB";
export const coinVault = "bTDdssLLq21eJoicB22XoThaMnPAFdHaxnhocrPHEi4";
export const pcVault = "8veH7eiuV8rSYWaFcDHK4LN6vHP9q8PRV2yt1Y9MbqTV";
export const coinMint = "J7Q7E3crPqP3LBKYYFRy7FUTiUjbPEqGsQ1ahF35gCv8";
export const pcMint = "76QpcywkA9gnPiTawEwA3P1szH731DZJN3nUfzbDKK1n";
export const bidsPda = "2ZUqXQc8YTEKh6xVK8HPJNiHnEJ8aZa3D3XXV7eNRQbo";
export const asksPda = "HsMYt5hinKDmqGEz9RdRcUS6um24n2pnoftF3V6zLCXf";
export const reqQPda = "BDZZT5xuka85iFvXoa8QoWCeuL79M3bSwXhxb36TAG1U";
export const eventQPda = "45vj9bMbXL4HTEgG6F3QvrPFrq7ZJkKtAy6FpuJFs5YL";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
