// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "EF6ha3Qut5cH9FwAPs9KxjhQyTinBcJToAyecos7Z34f";
export const coinVault = "6yd6nbejWqxPnN5NAvDv5Bj3VQyKbBTpmwormEqGLwbi";
export const pcVault = "J1sJ1HZdN9QnUhv2f1FZtVn2Jg9roNxo8LsZursute4T";
export const coinMint = "BzdbRBPqMV9dozyZQ4cdpC7wAfWcDT2GSzN53hcrra9m";
export const pcMint = "y4p3JvvzPCZxKsSSWANR3iZG8MomvNT31y1Z34nN6Uo";
export const bidsPda = "2bQN8CpNZgFJXegyeNLjttrhcBa3NYCYxeTFR5h3rUPV";
export const asksPda = "Ftvj4iNU5JTbgLVGb1NvHYeX9tLKpMmz9NHGvCCJbYyh";
export const reqQPda = "4KzKQNfKYLDRyJQ5Q84Vqxx1XVs8fkXbSqd8CBt6gAWB";
export const eventQPda = "CjWAwkMdAfH3E8sL5AKmLt8RF8WoUSFsU4Q1hgjcKy8s";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
