// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "V2F17bxsPCjzftfetwcAHdr5LqwPTQ48gabGXRA6Cf8";
export const coinVault = "GckyrMDTjNwDm7oRv6JehBW8dTzFpc5R3xSzWFTGNV7b";
export const pcVault = "9HDYJQpAPoxwiTZKEydrGh5ixAeZeDrNF3rU9cAmQq57";
export const coinMint = "GLxcRg6iv9kTdKeMvXmRooEHJ4vTG3TKsahe5ABsFgFJ";
export const pcMint = "GGioBSdSu7GZjVZm3o7V9UGUswr6XjCHFzgXLizUqNyy";
export const bidsPda = "2Tc8AqLbAKUvC96bQqyJCR2Y7kfAWiZqfeRosfqmRsXC";
export const asksPda = "BgttUcXitqTHw3DNVx8tWbExMUJZ5DHPYEyGWaFa4yQH";
export const reqQPda = "7whPhoxt9uVbZXXuFD5tDJ2duncZi7uYNCStN2Km8MXr";
export const eventQPda = "63WUY5Ezj218cmokcnn7KEyxiX12bFqxEPQN9HMpRATr";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
