// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "21nF3xdA58gH8QwV41P1MbukeXuyzArit98rjYxZg711";
export const coinVault = "857YHSvQBDgNQ4LaAYztCKzZjHpKpsswPwDNv519Dwa5";
export const pcVault = "66Zf9ZFXAHMjjrCbUxJYGbhaee7dGpr1RKTcHe4Sb9xW";
export const coinMint = "8yDVQHZ7ivwXeq9zkomHjpjDZqDqKAZeoxXC75Yp3rzb";
export const pcMint = "DShx29FrVXUmxKVk8RKhvJGdhaj8R8Ac2PU9aBgKujze";
export const bidsPda = "4DT49aAQDuYrCdoU1vkE8ZZdaH1iGWj7pWewni9H5E11";
export const asksPda = "GzPSEhLzgmraEg9RqNCGkwJptRft4i5ynyCQzyaJChYE";
export const reqQPda = "8VRFtv3oiRKocY5XNKMY9tN7vfxgfuCBQw1Fi6xgSfsK";
export const eventQPda = "A5BZYpU1NQnF13FGzX96c7P284g18GfVZ6eQLbsvZL2s";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
