// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "C5uLtF4o74c34BxhvUjBuAvRwo4t2dF8GY6TWtHbwY1i";
export const coinVault = "EViZzWNMmtEMgSsAV7vLNzoaZbHK6qRNfenpdQivFPWc";
export const pcVault = "A4RbmtBUbF3m31umJzSfjbfN6w2y5C4QP6jEyPMmQC6z";
export const coinMint = "9WxiUszEbZJVyYE7e6av3gcmGjoJNpz2qnPx2mo6LYab";
export const pcMint = "Ez59rbcmMx2C1gwLrtwCaidcnzZKU5qCXLHKHkemH5z8";
export const bidsPda = "5cbhq7EorkB3NuD1kkDGgyJnen72apWbnJKAjRCdzYYz";
export const asksPda = "8pcbv7YetEbF6Gy3iPd8rJwhB1HsW2RL85teBaUcYwKW";
export const reqQPda = "GQ1Wkn7smnnGMsy5DANiakhXdmpegQ77fzkd8D2obYVz";
export const eventQPda = "2kxYnskahU818FSjBE76z4TFdCohoyjgoj7wZo2e86Zt";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
