// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "9g15u6UyYBXbY7u51XuzkwQrtqunoRjn6mSNYuQ9JdC3";
export const coinVault = "FHF77RrcQSeQBYD4Wouj6c5SqnuQ7V9R1NQxicS1uqQz";
export const pcVault = "5uc4EsqLd47APJkXfDsVrdETgDToV9fTwYrRU1aUm4j6";
export const coinMint = "2hVctP3DKfSWuGFSBteBFiXK39U8yywhqNrRsEcPNerR";
export const pcMint = "AWF4wYujeP4G82Z5kyGA1LViM4SiU6kC9XqSXf4J7fWk";
export const bidsPda = "8dxsoU5HL16uFdm8LoMWrS4waWDuUurSkgXqX7B4y43u";
export const asksPda = "HK5AsGkXjzDSfKMYLA42fxpXbaMxQe9c2JvN7FLMi99Z";
export const reqQPda = "AUFC62DZAxpn9RasFGzZbSaTzkc3cEGjAuiF1PfWxsah";
export const eventQPda = "DFvw9cdXUw8f7P6sEQKaSsoembsLU3aiNg4gGCHUDPdH";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
