// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "2eYFkdBbvKrggvZ47EwRLqkf2RSzK3hGWbh2GsqHLeXg";
export const coinVault = "Edv5e2z6LR3aEnHjQdW7XBjF3L8FVekqXG4YH2qvvcgx";
export const pcVault = "CYpoyjFLGCcWNJZJjQ8TjuWP8DmFGtSyiJenmWUDzWZy";
export const coinMint = "AYKzLVeiZWqPAVVH5uLHqXLkAxYg4f8kMt3jKFTu1kqA";
export const pcMint = "8s99xFZPTUrShx5p1b84uadLbgCiPPWFcDSpHrP7yyvQ";
export const bidsPda = "A1AsECVLqpArxy5GpwVWzzvoat8fRobVAa3ntgV7MJMd";
export const asksPda = "Eqxi79tVJaA3ARxX2fFDdty7jPuCTdDzi7NF4k5LbxEQ";
export const reqQPda = "3cr5auh6qxfK8B5ktLRu21BkGXgNQBj7qdCEJKdFw8bo";
export const eventQPda = "51PWd3r9Kr3hgpQSL723HMp4jZC92cXCmzjVFa8bGu7L";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
