// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "2bmtE4SxZr7GqoW3ZEswpZE6zsBDxtYbFob9mshaEZgu";
export const coinVault = "2p4Wk62FVHa2PEjmU1fcE31a3qv4FJ2CqrUUQZcGytey";
export const pcVault = "J5y2CMNpbR8XeMRunN6eGXAFDW2VrrbCCUWUVPPJNAxH";
export const coinMint = "5wZ2KfZCDrMEB1iGRzqu6KSTjs12hNW9i4ZSe9qveDSz";
export const pcMint = "DEZWRH9rsZ66kfRN4t3od25rwztxEtjVjwbxhSiAkVvR";
export const bidsPda = "4T4zNFmYQy75Fi6NRwggBDGZjSBvrhkeSrHsMbePMW8D";
export const asksPda = "2g1AfD9Ns8mPkzDR6KpPCdzKdz8zW7J2UpYm81evT1yy";
export const reqQPda = "GpBLcpAZFpodkeWhLMJdp26guj5Dnq2Y1Xi3Ubecwd3v";
export const eventQPda = "7xXEjqFEgoT2ChheGJ25XXmNJvEobL9vA2X27d9iiSYC";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
