// This file was generated by a script
export const programId = "VGwPEHBUjxa1ZQyvCAJ166TsKPYCWKafJoDeqdXqvdJ";
export const marketPda = "CyQPypmGR4kZAH9Nyar7nmxidXvQruSpwi7YsLSV7z6u";
export const coinVault = "BvxaftaEuhoSpYZSNFsFRHiZ8hFWuxGrNCFD7xBgXGZx";
export const pcVault = "AHcvC1ifNBn7Y7iVKp3LHHSAJEBzcJ6GyUu7YRa7iVo";
export const coinMint = "Cobwg6cStS6XxYDJefne6zLN6fXhagphF9A529biC6wh";
export const pcMint = "2WYeXKDVPSHhKAxDwXT48BxrYPaMmv6hWdgVLWaZqdqZ";
export const bidsPda = "Y5Jj19Cddxfd9TwdvNkU9dr78gK7GY3sqq5XZzttSRK";
export const asksPda = "A1aTAkAjQVtxcd4G95XKgc1CYDx9bNb6yFMhAWoThcfF";
export const reqQPda = "4Vm5Qnf324n631dwgMaRsKXRBMoUixTq4jr6as2HS6zX";
export const eventQPda = "DFi2p9vdJWvziLmQsrHxTeYFbhYxACu3Uy8pzSWt4MHe";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
