// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "Ec5k97MrYjN3C5bVfWwV1xfGfRJSz4Q7TiVtwTpRNQHg";
export const coinVault = "Fz3AGgPLm71zoQMxdfdkydMNUaTRGZyGrDJo52aHo3SS";
export const pcVault = "5Z2nNRGdAR4f1HG1q6KYA4qW6KnNjyGJihhJSHtgvTd5";
export const coinMint = "ZBsFC8Ft3JMrwgH8jnpv4DukPMDYQAkyLrWUUEAFePh";
export const pcMint = "Hb5AKpxanhbXDUXekwEYC2Jo3AmEEt4nXxp5RVNfXVi3";
export const bidsPda = "4oQ1rLL9mbva6WXjgb1DdBykXtKin5gjPCRMXx9ScGGN";
export const asksPda = "9utXCQD8M29EP7SRUqhmMbVYbmAMfRWS5YFAaMC9MAtt";
export const reqQPda = "Bo8zKUSrNGFSKnTsemo8DFBikMPdra8LEUgm3wG8SvpG";
export const eventQPda = "92KG9mkyJENvgsj2tGTewY8nSFovLT18uvk2M4BEQSzC";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
