// This file was generated by a script
export const programId = "Aodrp8JRS1tCywT97x5ytaoJYczv44JYtyBHDJGLCx5m";
export const marketPda = "54yY5gutLu8Bf6cLPR83j4VT5ncaHqLMKMe8f2GWSaeh";
export const coinVault = "Cy1QJqnNcjsYrm33Trs4xJKFakZrmHHBJb4oczbu8QsA";
export const pcVault = "BdgR1oiLJay3axb4szz5ZSBxTarF4vesfNnxq74MdcEm";
export const coinMint = "5cj45T4zXJP5RvSwY6JSf9Lp2bvGDHBVQChpBxMSN45d";
export const pcMint = "hoRMQWLHbndEai2e7B2QNrguUTPwAL8nEBZ2U6ehAt9";
export const bidsPda = "4Uxmv1HFDK2CDpA2tME5jHtf8z1ybnzETexZydu5RxkD";
export const asksPda = "EDHBqd1YyYGD3QuoXfaxsXXjpJMPWPw6cEvT9Rxxk482";
export const reqQPda = "6UzJiyi8khkCxGMPir2fkT9yu8wibXWKuJrhtEyVmryc";
export const eventQPda = "8QL4R7u9n3ya2A3jUdcFLB4CAnvsCfEGztT4hJz7fu3H";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
