// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "DZHRB7DeJHt7VEnu1PQtkWiuW2AQKsLGMJ87fdtSDk7k";
export const coinVault = "H5sZ3RJkUgSkmP8QnRvEh5HmmXsGuh9sE8Gi4YMdLjWd";
export const pcVault = "Fyc82xd22DVUNfxmDUhN3ruLeTxJLSioUgUrJngbJBuy";
export const coinMint = "8ZfVSSKnTEMkTpsLTga1u97k9FVhHZgMHuzrQr8MCrtH";
export const pcMint = "pDXUAZPT4FTDMCZKpNBjLpgenzAQwaxycwcUNL6CxyH";
export const bidsPda = "9RCKwpDR9dTQUo9vdUgqRi41Fo9S2bR457KCphTooBir";
export const asksPda = "EjGamSfdgA8KfAa9scS9trmqDDunKnYprpDivwFb6eCR";
export const reqQPda = "7dY5Eo2PizFCasiJWtMaWZyF2cxro6XAUgSsMGrhHUop";
export const eventQPda = "2Bqzq8nGmkFAsfw41ZuJjaVtG3ru4MqjvNzmW7YaiLfV";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
