// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "GQjwgLnW8wWmX1ShTrtDE2LUQ7t9Vt53FHMovQh4ykb3";
export const coinVault = "AKk6ayGh7h14g9S7QPbUH6qeV92SbZ6L1CHuHcJ7b5bh";
export const pcVault = "HursS1LLZsMnrRGk17biietDzcZSh8UcunfHkJXNzfQ9";
export const coinMint = "9erNjYZfJEC9vmkR5JJwTEs5rP8hGCxgWHSoCsE1WY2Q";
export const pcMint = "BERqHuEUrd2qth3vpeKfqc8K7yNRzEbHXL8MugZvvPDP";
export const bidsPda = "GrEEayK6M3fgWxHbRW9fFLtcNHd2JoEWZFspoqcf2V7W";
export const asksPda = "4Gxd5qmWTc4ycGHtfsBftCkUWuKiw6W8Pznz5z9F9en9";
export const reqQPda = "73pQ2C414pu2b2nsMfL41snXUbAAbnF6RjuUsiDGSyPz";
export const eventQPda = "CZfUxLNzKjsjDTRcDvNYeZcNrcyfLtXSzbzsX3kiUiKh";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
