// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "77ux4bmcdBAuiCVBH28kftwfFZisZhKBVMUTADixwwJx";
export const coinVault = "FE8K4W7gZnNjW18fLzFmAG983bo2itVp31bdHrALTthe";
export const pcVault = "46a2FTVqRmrZgjdY2ts9xLBzuPfWjdotKsHos4AindxY";
export const coinMint = "DcqRsjJnERH6WA5Zncj5xC6Uoetvbn5ZKiBs8fkDscTk";
export const pcMint = "85B5wVRZytbLjsDP1s1hXBbVV7EDq2ELCQHmPf1TYzQE";
export const bidsPda = "G5nBfmGuSZERywP2QGAPmpX3GMcF3GtkD7oLfSXC7wTX";
export const asksPda = "Gww7aatZ6WnKYAURccsWvVak5SyF2VSuiv7tiZxUP6pB";
export const reqQPda = "7t3yewuDS8NEyipH1BsRpunicGJ4qdZJYN27m8zjDqXx";
export const eventQPda = "EjVohzRwPQbjwU3TZFJbtMgPvMrEC45R79yPBrgDVxqC";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
