// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "DGWqQy2sFryz79JCpHUKZ25VWaJ3RC5x6pw1ni5TZ24y";
export const coinVault = "8Q5gtnMvY4ShjKRieos4skkBYny4xFMnJGjg7TkiFYM";
export const pcVault = "E4y76LR1zKrYt2muFm7fkjgTYu4Juvepmrvv3arJ8uco";
export const coinMint = "GecR18xWRN2tnU5obgPbeXA8uDwBsBgoHXxPaJ5VCKtV";
export const pcMint = "HxFC5P9ubWUAru9TuziBCVfY6yHSQj2XmkRppKkqEAhn";
export const bidsPda = "2cYjpfy1H5aGR8qMbUEb37hxkwRLx4Cq11L9mArkj8sz";
export const asksPda = "2HfJPHVqSWWTm2bcDHbqXqou7G9fpKxE8wMCQsJV7XXh";
export const reqQPda = "DCUrWJGYPUheJbrzPA6cWsmLDvaXbeyiALfSco6Kx5Mz";
export const eventQPda = "9YM2HcWt1vxvQ3CxhuTnVPaYdv1yUxrkNxbr9LV7Q1B1";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
