// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "DVPgXapiy7vhZBdFwmj1LD1ovj14s3s9ymFvaNojAW5d";
export const coinVault = "AA4H1vPGqkLQ1S9df6MUkfU3u15cVvjfcTsNSfT7NwYd";
export const pcVault = "76S767vNepLPAgmevmifCZuW1iDxezdEoRVFEm5Xy5JN";
export const coinMint = "E3ajGjn5UF3Fq9J5QDd6kmEXp9RAhqEFsTu5rhz5W3CB";
export const pcMint = "2156GGSKLV4uSqPpgkiaMTuA3PxbF6u2jib9DYsMKyoP";
export const bidsPda = "3VkN3yzqXoRNmimBC1i5LT5FCAWmMZ6iBz6UxnkNAoz7";
export const asksPda = "CGHSMQy7yvDfYEybUDdRHKZzcUdHDcdue2sV9RHGv5rc";
export const reqQPda = "DSKUKSgBfBfZ1pnpyUHsyVUgDhifE1Zj3XGt2gFnDrbW";
export const eventQPda = "6U3MAMSfPavg4fsoWZFrr4WjDePKB4reYpqen1GAMBfm";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
