// This file was generated by a script
export const programId = "3Ek56WB263s9WH7bhGtjpNkFk8V2UDXmvsKxDJ9RzmGR";
export const marketPda = "EZ4uBwPZjV3SDA7gNiWZgTwdk3PeA9ESGk2Ja2dEUogi";
export const coinVault = "55tj2oK8133rCF4AJ7tV1Xwq5in7BtWAjDR83QEVjFxu";
export const pcVault = "ExBHJXkJJDcz5fsM5iemfpKiXHkE8U8E2GpXqHBqNnfE";
export const coinMint = "BDftYgsWjNv8UmnADPPt5LWX245VUw9C7adCgKyyPMrz";
export const pcMint = "6yDVYMQX6f3ySJaPGJuXW4rQHbWKX4JgwAndRZNxYUtd";
export const bidsPda = "H6PAp3NBW7yZoPCs9p14YZPzbJNKa8ZMaheEUkSRSxoD";
export const asksPda = "9KRpQPZVbv2cDFWLbJj9Aged1QJF2YRfGXgPTQKYq953";
export const reqQPda = "HXD2cN6bzvQasSAcUM2edwhBByHhHhhsJK2N5EMSh2e5";
export const eventQPda = "B5bqPt4fArDZbMpbDXp55P2h34FzBrGMYma1Fz7dFLtX";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
