// This file was generated by a script
export const programId = "Bk7e6ygLwT1FoMu19HRoe99BSE5yf3WATXUVzvQGj8Un";
export const marketPda = "3pSGZYYmnaoGjpevkzT67A7knzTaegMe5W62MGYEjVDQ";
export const coinVault = "6NeX7rAU72kucdpFb6PmkrKmUBfedRcJ7NGRXSRXBbng";
export const pcVault = "aQaNfktSsFghnroqwyop6PbtgmsmkkG92t2aAxF3Jsm";
export const coinMint = "DkeUibsbZ1uWZAhj7cGPGgowJyzvkh7yokBRwr1XXmPX";
export const pcMint = "UmjFCx7kiNhSbu8FeFXSmTEzez3ny9TWgZPzx54sx4k";
export const bidsPda = "8uYhX1993YuSdqsKcPYV3pooEatFFzTjTJQxNxmVR6CK";
export const asksPda = "8e5FZaRSgLrXXTArHbCK6FyJf2CQeYwGKQ28UtUDY9EH";
export const reqQPda = "GSkVqtm8azmc13hhXpDDaJiL7qhJWc74WNUkjcnUDwU8";
export const eventQPda = "H9C26aHaafVirSAouxu6BHccoeoWwvzLcY1aV8kPZ9sx";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
