// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "14NnWkHxrq4XcJXFBQU833i1pN9n3VoYzUAnsyGCP2sP";
export const coinVault = "4d2zqiAdDzaZwyMtRetexRhDetsVrNKDmMaaJGc8KFfx";
export const pcVault = "H4MDvzFnTaqqRweBrQSD36URt5eYk2Y8aM3uPD9pkRgA";
export const coinMint = "DyJai3mBCbgy8Q56G5zenfdVJSaSXdECbJHo6PDTKFBJ";
export const pcMint = "CXDKE5Wh7cVmbJrHnmWRaaUcvtpvZU9hi26Vt95NeANu";
export const bidsPda = "XuLdgBS9CXGFNcQqzjTw6mhLFEB3vNYwNuTV2DFGDtf";
export const asksPda = "B7YtknPA3XebDWHegwRnbpHZU6bRStZ16kggHbM4ti9N";
export const reqQPda = "BimJSQ8sqmSTeTxk98bnRJz2B9vLrHkuW19tQgysyRCy";
export const eventQPda = "31H9VUVCLdvSEtP1ss1dKgB6L3HbJC1jTSzhVrR8kFY4";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
