// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "GR1Q3RpcKi2sqDu7cApk5mc2oyfXT3QpJCnxeSXCuKCk";
export const coinVault = "8vqd6iZRuPfsZ5W5MnfBWcGJ9uCnjwcX6oSgmestTP3W";
export const pcVault = "Bwk2DMeG49wtJpUoq3zzmggZmu6dEHLBvf6iTyZnqegP";
export const coinMint = "75GGaKz4Ncfa868Zkh4E8Hz298kYnbooSWZWrj6cktjN";
export const pcMint = "AM2b1v4aSMfgkUoRDskosK9EEG7becXxAyUPsjtVLMXg";
export const bidsPda = "2xAegyw4jVxNa4VvNFdpjo9HGD1cZaDoZhn5oAhzNeN6";
export const asksPda = "4CcbsafNm6sbvt5G6Hs8vBTWdV9zN8UtQ7LY6XS88uNc";
export const reqQPda = "9PT6T8aYn7Nd8U6rZHbqwBZj6jvg7EnRpob5HroBaDLB";
export const eventQPda = "EemPv2GMMNkCyxXYvTsK3SPwLKmib54X7vsQx4mjJ3mg";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
