// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "GZG8Ai8E5KXaN6rAG2Nm7TEjzTDKsKt36oeV2HFzLpXS";
export const coinVault = "DfoHJ5x5tm1dvqyrQSMaDeM8LGidbcLynHrZRA9MzaR9";
export const pcVault = "AoFrwaB6ofxFHv9D1ryd3hZrfeZpabaXZn5uFmiWmFKx";
export const coinMint = "7VVJN2z4NjaiGko2TJPkW3WXPz1BSDt2hU8gnnWCUcoL";
export const pcMint = "4GeosxhUJoAtm2qdG7UN33483hBhXyPpo8YsMUvP3obG";
export const bidsPda = "7sXDfm9XejRNzHumeBnLnaJoZCYUExGv3varKZTBWKuq";
export const asksPda = "71XowkaiCaMKtPwVkZNzWkzp8U4XXo9iiC2TYdDxvBSV";
export const reqQPda = "AYJP9MsbFvTDjHFBCceqkqztQqQk7SZVThZpwnNttrvk";
export const eventQPda = "rew5vRdj89tavGwSbWPjLZKNVGs3ZmsiiE2C5Ex42P8";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
