// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "Ft3JTUSmhXaic9P84Nyc6DGrwYNCVyxP4iojScR5M1KR";
export const coinVault = "6zFhSLzJ7gCSt2gZy2RT4CSthBjt2ihkDEkShx5upUmp";
export const pcVault = "5rYMfqkpkzFzpvJkKM5fnH8YwHEqiu9RS5AzYmX6BLXt";
export const coinMint = "EmJUpiABayS31RpFNiiPtxuaiqdDA6MVHemVesCLQPLJ";
export const pcMint = "BQA1GJL4fnWfQhRRqMfRXwbx7buurJ1U4E5ibBwFLWw4";
export const bidsPda = "F1qgjyduYHe8hqJgErVK57Uk3iWQfx3K4A8GpM6vxs2P";
export const asksPda = "EqenNNfaE65z32UPZbBzNJD3txsg8ACuJdkmpK6HCQqa";
export const reqQPda = "3pMCqqazCQHNeGEnw5k8g96kfWEVYKXxqgT5i2ByKUcn";
export const eventQPda = "85wNd4XQxqniDPohbJzQ24bfgJ7RkGXyNnUpLg8JKiwM";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
