// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "8MKx6ecQ632D7zjWm597vrYLmSM7boX8V7CbnxJ1rUHw";
export const coinVault = "7nGyKPpipnhWgvqVZrDmebWVF1wuzAzuqndWDUuafyd";
export const pcVault = "5B9WKL3bA3iyQDe8Gf6Y8JJEaGGYF2Z6go8Z6tXtLzyZ";
export const coinMint = "C9LjZ8duqDtGbQ3tcSVv2CiKnTppAaTUMKJkrmiMhXcy";
export const pcMint = "HTZK94bgzUzUvhN8zELtQsxDZNxAEYxq17oeeqgKRrPn";
export const bidsPda = "2mZHKnjexu53xTwva27JBEdm4KM5XBirJHQArbRNjQFz";
export const asksPda = "3DWCQbHf4rcLSi9yjgwmJtxJfnQwbyHLmU5qJCdNf4kb";
export const reqQPda = "92TGPvKwZEn1vQMhREe9EWwqkwEWuLVQtEysuJQMMLkk";
export const eventQPda = "GsVZFMsTNGSgVRSZj7hJ8Temvfm1XquJj6jpAijkkckT";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
