// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "CbRNq8U1ntYwzTdrWwMD2xohLtkNSSYrDd9YrnRx37k5";
export const coinVault = "3SAZDJvv9JmV6wsELf4es2vDXjmrZ67PT6k7Q1MDHQoL";
export const pcVault = "7Qe28pUYHB6i5VJRvT2bysvZyDrMccCEv5FjJhwMn9Yf";
export const coinMint = "6bCECJkuBnpt2m6ntJ6Q2BddaCiEuSt7xhT7QipozLo";
export const pcMint = "FFt4TAcU8TJpQXY9CTqsKE3e9cWZAf9jZHCTkuFWFVfV";
export const bidsPda = "3fFCcYcrqSEDP1wp1BJJf1GfexG1JLDLMhAvoeyVZfBj";
export const asksPda = "7eV5xCPKeFJvQWjhL1ybBqiuB5vXs5emr8bCjzgXrppq";
export const reqQPda = "uixTCCmqqF2brkHSurzcP94yJ2kuU6EkxS7tNPAWtKT";
export const eventQPda = "CS2nrkj6ib4Z5mCHUQJyApiLyRkGGCn8it3wvjDNtHMD";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
