// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "YjmjG754G9bdwZDXDffwzBCcuDga6sCB4vW44ztivKf";
export const coinVault = "D1pgcBQeyw1xh5zFbXe9tuMJyVHQSny2dZui76uFFhbR";
export const pcVault = "H5FjN7EqhLSN5VbZVsBgc9nWkYb9yR8TonYHktkYGL9N";
export const coinMint = "CwSHzNzkhVmzXFuE7YjBKCEVxC85wnP9VqiuARTHxpEN";
export const pcMint = "7EZyQ6LriPD94DMkAPB7CFeTuCnj42aeKh2QEW9GorCK";
export const bidsPda = "AKUkaMyZyuw85aihk5egMWzWYzhyG7uTCddFKTojq5A";
export const asksPda = "Ev5QrzMuvx84DQPJUnG9hC79Gbsux4awm2NM4pj5KuUH";
export const reqQPda = "DARcCqsNtJAsaKhxav6UqC6c6KPv97hBv28zQuFjtsG5";
export const eventQPda = "6FiBZ1D4S5qS4C7Qrh4T3YU9cGVRNYVUTkZdrkY7bcSr";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
