// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "8X4qqhQVoNvomG6b85Zfq6AAtrDYSCSScZcm8pDTGpjR";
export const coinVault = "66sjqhvKtBfNMjruVf7xGUQC8gqWHr729jqkP4dqsJFf";
export const pcVault = "AM197frvQ4c8Ac5V1PjPF5h8PYYMhTPTuPKKtctS3fee";
export const coinMint = "Eiz33YM7xXQD9M8CbYh1h4HTH6WBYdQvJBXgopdTEtcw";
export const pcMint = "DKaabwQNrqEtBNEtgVZU8iwSzZCQgQEcDPrMdQQrzG2H";
export const bidsPda = "6GFDiuZrL2Dp8bi8kD3YFJrq6oQ3FPnXbqE7ukNngkA3";
export const asksPda = "3CybKXqvXGT6FQa7a1XEU8hVVPFM6oLxn66oPXum6Tba";
export const reqQPda = "BdCgHtALz3eLuJKNzcj3ux46aLJw3CizhEpA8fdgbH3T";
export const eventQPda = "APKo36xdAuPjj6So2PEdj7eY1ERQdCkN8QUbsnL3kyW4";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
