// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "91KzPgehcWMPdnPr1We363wgXbBiiE5fZUSKCM5dov4p";
export const coinVault = "2ap2QQkXbcc7fwqcGfiPwG9ELM9hsFL1XmSuoAFQqee3";
export const pcVault = "DSJifz1QaWpVpP2Tn2anoyQFFahqczAHBWzPrwdwYn6G";
export const coinMint = "EdSryKzr4iZ6kaT2oSjpPJ58TXUvoTVTxfxQWZcjcRuL";
export const pcMint = "HtfdfnWNVkdV2Mwdy4WDA5Tocau7s1B6mKTuZyQStrtu";
export const bidsPda = "5UAPrfncYg9Lq4512UmLcryxAMijRhn5hDw2KovmtVFS";
export const asksPda = "6voLrn5DHeY5S671jWhWYMprdZe7fpxv3fGkrw3ye2Qm";
export const reqQPda = "9L2abrjNTUiTBupGYBTySDBKQUvH5hY32cowNxx1cgAu";
export const eventQPda = "3DW5cQDDZmxL4yENyN72D6H3KxSeQq6EivBQm12kZRd4";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
