// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "HyXhG7WcKETTu2c46dzN2geRGUmHjkHXx3TgxXkMgPUZ";
export const coinVault = "BEd1NsDsdp1cQXCNWidd1wnF4Dm1WNCT2SAWLqFHHEsZ";
export const pcVault = "KhcoEXBhwDQ4hkCqQcu1yby6qQLsXsjBahGTze2pgmt";
export const coinMint = "6vp2xYbccXf487cJHC5GEUj1FXV5oouJRbzKpkCKfXmA";
export const pcMint = "FjY8jTEhcDpzcNZNGiMjU9ih1PCkWmNc9vmZxwZJWDiu";
export const bidsPda = "HbVXbDZMgRhtfaZ9GKCwLDACz5ZBvLUdJRiJQrJn1awD";
export const asksPda = "B8k4BRmUyW32YDBi2QJAm11pR8UWwrWMR697cg4qVGgj";
export const reqQPda = "2NmgKMkzSWn8FnxH9tC4mLenQUxRFUkDcoj5bwCrb1KE";
export const eventQPda = "oyJan4jQbqy1kSvdQBhTWZfRsyrq2WGkTiPhq2KBbHw";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
