// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "4k8cGqpVo185RJaBBgoh1yWjDpgBbx1JvmmRQMZQaVES";
export const coinVault = "GSsak4ic19PJWvRqa9ssK63mn2fLvwwBP1rHv4SLJNiJ";
export const pcVault = "7EQR8fFPJbeBUMZpfcVfA7aN1WPR8EbkHhotqgwVfZjL";
export const coinMint = "BgtkiEXdJxirwQDcjwEQAKtXnrVeQHs2T4wU8AXCCMdp";
export const pcMint = "Ex4eeaPukLA1dGCk3vJGXpyfwM7KxBFV3Fn3CzB4P9un";
export const bidsPda = "5e5We1MJFM5udcaVGRbsEbUVyrza9kpLf3EmdgLY1U5g";
export const asksPda = "GkukyXBsh1qa2nMDkPnSxJeRs7ou5b4HK6nAjF5pJs4L";
export const reqQPda = "GCUV9j9tMeeuCrqgMwTNTtcdsaUMreQMmkzi3vFUtcPc";
export const eventQPda = "FHRm1fSwc2ubqMRE4gvYfJcHkqn6mdj7aM3iSG1aJfEa";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
