// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "8hnahnqCwV9eyUnNEsVLQwedNFNgByeaq7uCh9AfurVZ";
export const coinVault = "ELtSWq7vgV5oHp4SVosWr9jGVAzUhTs5W4HcnPMumxNx";
export const pcVault = "Ax92GEpACf8Rbs2oR5WknttKKSEyaZpvaLyN8mhZmb9E";
export const coinMint = "Hedstg5nFqk4iQN3qjRAMsUQ677kSXbSi36G57E6UycR";
export const pcMint = "3c6oqC5EHZ5tgtZeXY6VsiU1cd8sYypxew9vPbDVKRsd";
export const bidsPda = "5ZSq2YvDjDENvnXQQQKPKfecXSQ2rcJbtzjZDTPu7Yfi";
export const asksPda = "9JoHWRRRTQDBfQHoUKchb5n4URQmvcgPp2GiZveC2KcL";
export const reqQPda = "GJCt23V2vJmGaNnTZp7BrcZuk1E6ZePZ67jMnVqmwcaS";
export const eventQPda = "F8EvBk5UsrCGthJJNyT2xUKCr5MF5QNzbneari5Xr9Js";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
