// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "9uxYNU1noxQNRikwVmgGfLTLdScdYc8w8m9iT9Z4LJUg";
export const coinVault = "Hbs8XZqLZuHimovDWx17AwxAMfp6HhsjApiGhBWvMtfS";
export const pcVault = "HWiC3c7c8yHFYJCPCyyJt1qLbJG1Rq8sMR2rniPuweH9";
export const coinMint = "37DaFzy355oNJrde9gKKzc6iAdafoeHUTNjncg7DNXa5";
export const pcMint = "BojAs6uEUMP7zh8zksaSh8wPqjDAAx7z8iRrz2X7g8Lq";
export const bidsPda = "2BRbsw96XFwQV7CR3zzVr6sTTvptqdK4hxHLz97CmEmW";
export const asksPda = "2JxuTWFiKPodGnjiRk2nUgs8GjxRCWVJ9JKznFcU7FcK";
export const reqQPda = "FmcZYPUQiSvLduTBJFu2Ap5Bajk4RmJSmiXivJ4qAc3F";
export const eventQPda = "AfW3zj66hKAu3L291zDmnVUryptNaXFTwTnrdUFgEjX9";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
