// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "D7HwRUwwEX5TVNZuZvsa1afBigMpvocKjBnz9oR2g4dp";
export const coinVault = "CBaRUhxhLnt9sFVYCvJnRi4PTa1LVqfkbN9NxiR5dmb";
export const pcVault = "FCuNz3wATDDysAEmVu31Qk1dDJdPVNz5rnHufpB56c7K";
export const coinMint = "E37RWzpQQQZPnGBWRXwrs9JNaMCqZsQ4WSrE2NSb35bG";
export const pcMint = "53neSKL31Yyz3YBhnH41StfKWefgoRtC4M2Wucv1mQLT";
export const bidsPda = "B6NwJEbfzakEGUTHDckUCeAV2AvUtCHGUzQ56cY7dkRN";
export const asksPda = "7BZyceoZLumgVgjy6KwEAD8RHs9bSzxeFSDd6B1TFJtU";
export const reqQPda = "J4o2hU2LvZE9BWyVjfqzjg9jPQYCtbvFgUo8L4dX6LbD";
export const eventQPda = "AfwJhZpYLMugq3Ca3346fX2KQb9Zbfe1KrVQ82W2nnEE";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
