// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "4W3ySCjvFFxwz8jgFZTuPLQkbdNFmdWX4J7QUqE2zdkq";
export const coinVault = "eVSpSoyNqXLUwHx412CnXFarAh5iA2qEbj3PprEuupd";
export const pcVault = "C8gM86CYS6YRGRaaD76f1Jf1cjUEg5kA5HkMP49vrQ8o";
export const coinMint = "FBeYNG6uGHKcj1YwEx9BAQNZTH7n4LyvQhp6HnLYbHUV";
export const pcMint = "3YsWu1N9HZwUoV8TZtnyix6FMhJfAgUP3vhg2hLHuKM8";
export const bidsPda = "9xCpcEJj22QNCVxqVavBH8eKyn8xyWNLRgaMJNiyGqA8";
export const asksPda = "9rucoYNobiqkohrKWekGdCaFYcV9HhZ6UXXhRnH8vRMS";
export const reqQPda = "2TUCqutQzBSf6NgqXRgKz2co5JBAY41PUgZU3XpYrosf";
export const eventQPda = "7LQh5gRcMB8RqWpjBXW2175kWEzuwxnUiVXoEwL8va6C";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
