// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "GFSpdMptmBnAenCwwaGeq8L6rUqMJVraieDh3gteWczj";
export const coinVault = "BfZEfcjvvz1ufzLaeH2P2FG4o1Geo2qh3j13HxxDuYSw";
export const pcVault = "DCyLQneoQRmokfSRvfGfD7rh3UAHQQ96LEDNT2UaiLFW";
export const coinMint = "Bk5YbxzgBAHdcPKuXREoRyngJqir9mko9vYzujVwruWv";
export const pcMint = "DnudRRkPKVnqAfLoBfLQ3UB65L7PqUCo85y8cnRiVBRd";
export const bidsPda = "AB96EwtJRAYD4eMpM29LbbLeDRoDGKqXoREhcYeN7PQ3";
export const asksPda = "GEczXrvtRqGdEXSG2X9rR8A1iVVhkd72ga32YoCC6Na9";
export const reqQPda = "7mFRzgvY5cs8ASogHpWg9ogWhYxnkJ7DWfKkHzqQRB7X";
export const eventQPda = "J1gLo1ruKUvCzEywAPZ8zrHSgSbpYkp1MpbnsQ92N314";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
