// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "2DuiVVKmT7k2cQhAhfZo6vEQowbYpECExqQSpnP7a7zA";
export const coinVault = "2VoSxL3u2nnYkDFk1XZPnAAFvwEvy2wzjLjjsDbwAjp9";
export const pcVault = "2z2PSWVHkoPhKV3U5hdtQ8QngYQV4brEgzi6w1EubBqh";
export const coinMint = "8My2GKwCyYv3oRWQ7sQRiQix6Py4m7XATzDHfzZ2WSyA";
export const pcMint = "GjKhApk8ky6Sj4Bdn5LMFRAhW8BG68d1sFdFsEMPCQDJ";
export const bidsPda = "917BqQpdit493QdWMthYHF773miUfzj8txN8nS6Zw2EL";
export const asksPda = "8rJTdAHfoXx1kPWk1Eo7A7wwBHCjxRsmdQBX6g5G8uLg";
export const reqQPda = "5gAmUiPU8QmiapqqD9ycKg5v57v1ZjHyNtrbX7bU8kQ2";
export const eventQPda = "DqLdWgeUvpi8QHpi4qqKy4LKZDKrk27mjmyAWW6BaYhd";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
