// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "GsHxjw6HD23DbBg6sxXNKN7JqeHMAUfp8zuAoz66EByu";
export const coinVault = "J74dBcQ1Vuizw1eb24FQJ8bnkagFDN4rzBf6fyoxyTjM";
export const pcVault = "27rQAvfVERHQWeUTL8JdAENV6FTzgshu94BkGava74vy";
export const coinMint = "AnoKKAA5nTxmnAxu9LzS3touzngRJSFLFzuik5nzapk9";
export const pcMint = "CkSmZRE1khtXCXgRRgePSvkmPsNM1cbFvh4JuGQ4jiUW";
export const bidsPda = "Bc57TqAAVYzjHtNkg3mo9gkHzEKkmfqq694oqqt6i3CG";
export const asksPda = "B2vCwtbZeLK1nMkaCrcnN4Np7RFqxfiF6TBGpZvHMWBu";
export const reqQPda = "CSf4q3t6gyofjArVd6oZ9zR8ZBkgGgcEcn6NBdyQYFZg";
export const eventQPda = "J1vXMD1sWfpCgjNKq3EoGTtkNy89YvA6EPtktgb5j43S";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
