// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "F9hxSrVkyAMZ9WDm42hKy68LEnQ6zwe9RfjpPUVjntm9";
export const coinVault = "BSmJJWmxC1s3SbfLvmR89GJr7nSVbtxnuHCfywZfoVNQ";
export const pcVault = "RGo94WZyV3Fosx5fN4qu23Jv4U9e8vVWgzguJHp16zy";
export const coinMint = "31bpxcyEzDAMFyX3ogo4EdfVVdw78ABbehUZXGTBW8ja";
export const pcMint = "9L7sWTF2xi3zGZLqdNBEXSD86ZKyLEzrosJPZfC3pJCj";
export const bidsPda = "3zp9Ha4HCL7rUij2xTfPU7FgdHjy3jgjq9kKJMRi9eWx";
export const asksPda = "GeyypKxPq7JaduDFQ4dgnUd2q3ddGEqRQYFewAREJrsX";
export const reqQPda = "7eyFdtJmsdmyNPUE1DyxUBP9dpoEhAxh9h9pSt4JgH8W";
export const eventQPda = "DyRsR1e58FuLg3GgLpdTchAdAV8RCezrhy6ewdTMWb7Q";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
