// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "E23tG4kuBdo41yd335rAc87jfJQKbJ7H7a2u3mgjeBN3";
export const coinVault = "NHx6Yo18LeZ7re6vZVq6VamfWvtb7LXeeWyFvNWSH42";
export const pcVault = "F6rVy23XCaeqtaS4Gm9S9LGvL78LywPA2eWrDUhaGT81";
export const coinMint = "CgvTVjS1FcPYYVz5UrxTfiPZpuGoyoyVSAAP5vDNipV2";
export const pcMint = "GgqaeaWJNnZZaJVLXTXprBFPLaYcW4XaogjUGvYitJ8w";
export const bidsPda = "9peMgVzMwM83nSnig4gdyz7Mw4aKtr1RjYykTg3JFt9m";
export const asksPda = "ChTjLm9cNAH5ZiDXaa4Khf2DnR83bi2X3FHscecepWxv";
export const reqQPda = "69cdYiF1fRBteEtzQY9jWtHg8KwppuaoERa1bPAQPdrx";
export const eventQPda = "CufWQnKTK4HHQCFVnDXp8FYtD456WCh7vSXhmxVDXi44";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
