// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "5cReErHb3cP5unsNnnh5VH3hRoA7JV6kcjQLTZnVXWQK";
export const coinVault = "94hcw5LboeoijqQ9te3Jb9eMmNgJgSJFjK477aA8ya1b";
export const pcVault = "8TujiK1Gr3BLjGrESpoC18eJ1R83o2VX3UhfLMpQu1DL";
export const coinMint = "9LwHuC4UVZkRnaCWUqXARq2LHPEXTJ9jJyoxNgweng8P";
export const pcMint = "CJstPh9ycoABTPdh3TLRriiPftRRwK2TnWDMJrSSmgxv";
export const bidsPda = "kmeSwGdM1ACBp8XTzzZGrfybGhnehve5aRSVUbd2rZc";
export const asksPda = "DFsb6iHPBebkYMADda32PmjXRYdtz6eeu1QhvX5KNjS8";
export const reqQPda = "EaSKmrhJ1Bn5LwiomErCBSeoLLSQrtTkRScafLdmTKAx";
export const eventQPda = "ayaWyJU3WPm21CdbnWFDWVBz7XXuuSqosbm53tNcgyX";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
