// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "HarAu1mMRaao8vXgKASd1RRJeqaHFFx2DiUqpNNUuifc";
export const coinVault = "8tWpb3cgfkvYRd1nXEWsET2CxErjUwv826ijyj4KbmAD";
export const pcVault = "6WgNJ6nbpv2SjBWbLqYyVFz1ZJ9m65p7tGbm5iXWpZnj";
export const coinMint = "7xZZ8s98YFMje6NQvGzYYkhZpAWDMvfUk1ujyp9QwukC";
export const pcMint = "D539XGuFyyNr6LqWWNKEXrdsPM13vVVZDSCo8zSUYcGK";
export const bidsPda = "47xp8DxLYGNmFqhFszDjBDp33UVe37b1ANQQv93f3Sfj";
export const asksPda = "3fLyXuA9bZvhqy8tBrWh3pc1wnGqgwAQnXvY8f6XUypu";
export const reqQPda = "D2aLKn11VRcGRmtpdpEoR4K21R9UEXQ6qJrrps97GZt6";
export const eventQPda = "CrTLyH3F5hTsoPKp3ztsRTqkTjfhMLthqQRxB3PUJnoY";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
