// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "BNJknJ6cTZVUzVAUA6xuZbrxxwu8zfzqjvbYNM12jC83";
export const coinVault = "5oXZDwV4RUAUJRzeWwGxtgTbvE19TcHaii4jSNPLVPuo";
export const pcVault = "8fAEe3J2tJh4dgkUWs4df56rHT9TSyo1Roa2r2LBsn1o";
export const coinMint = "4YrTJKGdxs2otvy15H8V1LNtXthvViBpRLBYfrzCGxpq";
export const pcMint = "4sjgE8nWnPvJc1vFsK3k7T3DiRSNxqMhdCYjHLVqd3gq";
export const bidsPda = "FL7yBB5AhL4DFU188SUxHth4hX1mYhcq4V6QCV7R3NUa";
export const asksPda = "GosD9SziEzPrcw2PnLqN9si9foLgmiuEiqmuyXfKSuM6";
export const reqQPda = "HmvRPBUSfJCfifND3HtnxZLgRbwYRh2PmtKA4yo3u4m9";
export const eventQPda = "DxjgbqFBQTAD8cgdoWoBrcRQnyksPGeQJtQWUGJC5VU8";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
