// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "GUoKRskf2S8x6P4CnPFznXWJomikxxFGqQbnfasS7Gxw";
export const coinVault = "CxwuVyj8q8QiSXPbEsYgtz9zQ6D5N8cDJVWDyr4wYQwn";
export const pcVault = "76RuWvcYrkGWhCuMAo16hj7zUGcgu5DbGoem85486nMY";
export const coinMint = "5QV8NA6AmPs7epaWkz5N2XBkXks5KPsq7MEhXAFAkj2X";
export const pcMint = "8Dngo2L9szYzqbGEgidxCyXFJFZPgqZkbqEVd46frTtG";
export const bidsPda = "2tzZ6VStiNigXHejSNHRpJ7Bw2EP8TdEQHNPo6oY6PSa";
export const asksPda = "8hyd9DhyJ46XbAzZ7koD495RpvwktPCd4vD5yESX7NwE";
export const reqQPda = "D8DZg7RY5MaqrGzJph9b2yjUTE7L4ANjBXjZmtaTrcUA";
export const eventQPda = "6qKUbNGQ2pApi9rJvjLE5BxmjTpPA9v3RJ4SiVRqyzR";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
