// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "EAjM56sG8ERamRUXJb1GH4PwCffMRVUKnbvqcSEzpJ97";
export const coinVault = "3qz2vjPyRFYZuWDWZ7ttTCZAiXM9aeDVGG6N8yPvAMyg";
export const pcVault = "4ok277DXH4MkbUAPyDZH8t8x4Q3HtKKmfjU333bsM7rn";
export const coinMint = "6TyBToSMCKRCF3ZSivcMMFSAJsUebCqT1dxsPDfcnkk3";
export const pcMint = "H2yQjvLN9LhiCgt7nH9bFBjeooHLyHAKggB34kDMZZa9";
export const bidsPda = "bbZSeYgYHuU71ePV3JVy5Cwr5wyGcRFujR1ywy2361r";
export const asksPda = "83qtx5At2xHngDopuxVmayaqhuv7vWfWukdLqZLY2UCR";
export const reqQPda = "5ed6zra5JE3XYVw2qCYsMYzsegtfEdcVWySBE7JsBxL7";
export const eventQPda = "FducacwHVoVLSZNPMhkQHLxpktiqX17YGpChjtXFxJk7";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
