// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "3AWKuo9q9Xx6MKsXQH5DB76S79kaHEvg5RSWhvZ5qfdp";
export const coinVault = "GuKLbPiU4ezBP3tGoJRQdstiHa2CbkMaW9ZK2k6MPTAA";
export const pcVault = "G1iVfRa1aTAru6GxWrPm1tyEGDQ4NsM5JY6ZXwx6unaB";
export const coinMint = "2UcdUtntQ7kdQbNYZSdhEcfxQk5dCuN8eFub77hVwsoG";
export const pcMint = "3viXK7w6U3PpyG7LL4dfD8zeu3ZqmYV6fbeQehW6UDc3";
export const bidsPda = "FyTDXWP9K6G7bJLwddZKmp45GBxcSxipzwmPBv2Y46iD";
export const asksPda = "8FAPW5GkgRvXBwkTcQuz89aXAeWE6jU9nu7Phm1TeEbN";
export const reqQPda = "6Z2jeRPTUB54eHwb7v7LEvDHSEFD2bk8jVfSwfkgfqGH";
export const eventQPda = "5jXEMJQv9HWxAqVkVdan7sPjqhNk7tqD7nDeFgtmbxXa";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
