// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "5Hmh8MfQDQaRuT86JVoZsiZWgWPKMkx5HvbMdAaTR2wq";
export const coinVault = "3p33Q3Uc73SL77wsYeEJkcERu2kjQGNiDvAFdTeX16zh";
export const pcVault = "5TTtFQa1GMFMjyqtwjDuL1KXLopLtae1nrCeu8ryQyZD";
export const coinMint = "89oCW27mNfEG67PNyhAhuAXGz5t4AzeA95N1WstqJUcG";
export const pcMint = "9jcbQk7uWAhv5vujDVxYHRNUkijPFCGFuyLy8FVy1gEs";
export const bidsPda = "6jEETeVkJq8i8isKm2qAQq5ZqVbT2HJ9iwjDhEQNZypt";
export const asksPda = "HDnMCiKca8RgEMjWWoTntrUzRMSGbMnA1myVurbwmZA1";
export const reqQPda = "CuY4wcwxjeMRsXT5qLwbfq22jkFnb3g4bDdfsQrvWw5F";
export const eventQPda = "5qH95eNTdQiEA8QAPgYezsTH2QWmuuV5Q8iKodh5yPHq";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
