// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "5yTazNMkSYSuFTysLd3CDFHp48E5z9XFfNYq4ZWjbh64";
export const coinVault = "hekyQYf95YadzRsxaQVoFNWwfPWdgHMbG1mprzBezXc";
export const pcVault = "Dskmq7NsA5U7AHFiG7YoMK2SF4MC87GybJZ4ZR5JXVaE";
export const coinMint = "59BbDYPNtJ8pvryVU1Do6y79tiNowhSUTKsdKXnPquKr";
export const pcMint = "84hcvyEDsQsBdNuL7TNq3L2hd4W7o1fnauzwg3ppCqH4";
export const bidsPda = "FTyByNBPcwZG6FQ5VSF7XRcT8g7NuTuSpEG7Tw2F9PmS";
export const asksPda = "8cb18rVFayZ9Lm4L7UFNkMSRahypLmyxMHm79dUM8Rhe";
export const reqQPda = "14WmUL3mFHnfQSyHPLXksvWphPqXRY74hAd1P6NJo3Pm";
export const eventQPda = "AMSjygM1xGFkCQHYWm4Yp8C6CZfTUGhxydnaUKRjmwkD";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
