// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "8ApZDX7zLnCz8qSrQkY39KQ74zW2tojoTLoubf9AxVeZ";
export const coinVault = "3SZLEG59v2akvPjecdG6hR47vnAxqx4FJFBNWqay5GJT";
export const pcVault = "6YgdbTiNBeUpXwTnW5uXYz6jCW5Mj5xydBe5NCecKoc8";
export const coinMint = "7Gq5K1f42PuSDESSwnEvEsqmWvsUsKpvBfjLfhMC4o1k";
export const pcMint = "CxVR9pur5rAdDHxRCiDxdi6m6KYhtuCF5HERWBCQAJ5L";
export const bidsPda = "DwzTYPWPZx3WPdNJg9MHYC2o14oxzPF4xTkSJG2XTDRe";
export const asksPda = "GGRBJ1uHdPsWUFUkeEmWJbixLJKxgnv6b4eePkgvBatj";
export const reqQPda = "DQ31YqddhY5UZHh898FHDzuHqdA32iccZNHMj9a8RyDV";
export const eventQPda = "H1deByQ3hZhbRJrNuxYgbkGLMsF81mLhmCv6QZ9atDV7";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
