// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "DmCJvY9iZ4AwyhLG6cVuTDexKceLc3Qc9P5mUGkGoivn";
export const coinVault = "J15bHh2s4DMFyiDXuLAgMZGDSDZv5gLDr4GVsaXiGPSb";
export const pcVault = "7xdeDbqi3vrCCG8kMLtc6p72XzEwFCnLB1JAbZGGizeo";
export const coinMint = "528fAhrzCh9ea5PtVVrE1QtP4StRKov1gtJoFPCvX5W3";
export const pcMint = "4Mn4zUcC5mv4ab3WhC5mLYoda62d9gTbNkf6NE9YcDcx";
export const bidsPda = "E8ccLPgyS831LQP5VMwBy1Z2DJf8gCnCZcWKfTiAJ5iY";
export const asksPda = "9L5nErhBySXD4KSAQ1tDknht863grgTpoFtyhuFNwXik";
export const reqQPda = "FnEoLe5SfkexFx3jv6z6xjKgJW7B15J2GDFcEevENovt";
export const eventQPda = "4dZBefVndtVB5Kc8dnTXaEApu5knnJwgaddHBKREs7xM";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
