// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "4VnjGN2ZXvD9zRTyumXeDY4Wmja87aDXEbAx5ckxeTub";
export const coinVault = "BjMTfWSPjRHsFrv2jZircgs3R2tLRhryN7Af1wTvKoQ5";
export const pcVault = "AKT3aF8NA3FVgq94fMjowF7j2eWY2def2M2pCTNZC3fw";
export const coinMint = "3shSwrBpZUadnuNM9UKJ6cEZ8A9hMvdhzybM3NmFifgw";
export const pcMint = "GUA7rE73mTDrVNrQhy4xtXAjBX7tR24JNK4hgwYYU3x6";
export const bidsPda = "HRDCkBoks9d1yz4HWQAggwhS2Uhmf8BWo8PaeCUk5wo1";
export const asksPda = "hczkpkYaNqQJfWQxgRxftBRNRvTZyDTX5XrzJKbgnrJ";
export const reqQPda = "J6VPdeRvMrtVTKCPndpMLaJige34bwB7uYregMEuMu7R";
export const eventQPda = "DufP7BBq4mTCHYn9RMLgJArUwpCbGJda4f9Qg7Uniziu";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
