// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "GM9JYDJqJLT9h5AHwVthRTTbkQiwYLvwdhrCsBYFJ4Tm";
export const coinVault = "EjwLa6zfEBBVJ62QM17dDZUs6Zt4iKEBg6BveBwRHNYZ";
export const pcVault = "33NxAwdznZUsmNXriddK2TX3HyTMRTkEM7KWNbGYBYeF";
export const coinMint = "G5t3FfJtPSsLi8T4ZtCBue72WzJLzNZpipdZz6Gx9YH7";
export const pcMint = "9j7MMBaThzGzj5LQP6PU3jVGcx4Pb9fyFagB65gTqM4S";
export const bidsPda = "Ec6PRcDXSjm1SVyg3z3Np7fq7bEHdavFW4DxWp31zPzk";
export const asksPda = "HePJzcpdaNHA6UXgY1QJShPkgsqQABiEgWVZgLVG7zPF";
export const reqQPda = "A8DCBBErF5mRUQ1h5NXCGKe1KqYvfb4uuZGZ6nULR2hv";
export const eventQPda = "DdhKa62B6mTLqsw29oz7Xn8kFGTJ2VPmqT5VQKguBVUo";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
