// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "DchPBai2nkNqoN8Hbr7xLgTUKm7a5kyhSMfSn13UXRBB";
export const coinVault = "BDoYRUEGuCVnsHicbPL8wTHe6hPRVsXvuUzbsSrzZ7iB";
export const pcVault = "DrHQSo1R1ThD4wurDuMUqnEL3nqGRjshmtcVtwWU9wd5";
export const coinMint = "2wKnTbgfHZffQiLekn7E8eqek6aqKd3bxAJeARzyypDp";
export const pcMint = "AVAnjzMR1w46z1kNAHpmNPNEATyZ4TaYsLDRPeAXgsCc";
export const bidsPda = "3T388QHgqjVQnfdFCC7TeCb45455phnzzBctd4A5repc";
export const asksPda = "7UpGNHS3rqgh1V9XrgbbNpkhQiwRSkBs9ogfcDahZhhF";
export const reqQPda = "FDCxT6W52LFNTESTDLvqnuYF8JppryjfMcmk4aVyj1Wi";
export const eventQPda = "573hXeqA3cmRBh1xwcCL5BnyAjA6e8CxT4K2Jgpdmvv";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
