// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "Bcchm7tjvtDisZxnECzkYMxHcjVwR5NuMzraCBuTM9NS";
export const coinVault = "3h32YMhNZiJWQu8RRCqiX5zzZ73V3g75Lu9rQR3AubeW";
export const pcVault = "DtF7zxjUKsx2CQLUYJ7FoFtiaDFLMQLjqDTao9yoSYQj";
export const coinMint = "qKA5e3tnZWYMrWkBJBefZC2gwdXqpSrSGrjtf8so7Bh";
export const pcMint = "CpjpZV5ubiXN2q6LDbaffiZYi8WCmwAQV1hRMaYxvFky";
export const bidsPda = "6c6p3z9XaZRZUpp17g3YZAxm4qc5rf2ow2MsDbDubX6c";
export const asksPda = "13QpADpper1bZs7bjaqzcgfBaoE1r76qGSSuNGTpLZE3";
export const reqQPda = "8sgPYve9j2B9jkwZ54B7qfEfZxfSM29Vrhhku2LjQKXL";
export const eventQPda = "8TQYLBisG64F53XNvmSz1LinryEfKUTo4P7bJCj1e8DG";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
