// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "H3eoP6J6p9ck8UmUZpH8GX9rjw1xCwBXU5PicqDedqBa";
export const coinVault = "6oXw6x4zPw1FjKgvEcExwE863Vvw3bQyj9bdphnu5A4e";
export const pcVault = "G7avcPYAKJydXNWPnuNGK189vbtAG8wPPxemvqcAiwmN";
export const coinMint = "AvyJzVuQczwSPrp8Fkkvf7zPPZRudJbH7152DWrFAqNy";
export const pcMint = "8q9U5CjqcgLxUTrjGw1Fxq3rUU7EwEKkAVbRSB5UvjPn";
export const bidsPda = "9EaccCEkK6F2JEtnR6UrHYkgUsLmCDn7MSxhaTnqVNig";
export const asksPda = "HLsftVyqfNiRk5Fjgy1kk5bxJ5dvULHvg5hLJEDeWV6V";
export const reqQPda = "EwiVhx7FKG4uw4wTfYr4DBJFksMTRDYbnM7U4YfkV7vJ";
export const eventQPda = "EWfnDJ3j82dmndtKZQxdxbQdPmfUkPd5FMByFUqbDMFu";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
