// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "HJAikVcaxmj2nCkHKRtDnPBFFNAhu2ii8aQSfjijmLqH";
export const coinVault = "5NhGY4ysWrMd9Lu1XNb1DHsVSYvGHDqrXj3UaZR8ebdv";
export const pcVault = "BqZgezrQQMcdL85MEhDJKDuuUrex7o6aSqtpuCDAyanj";
export const coinMint = "DHntxGedUUtGxJWDGkPWJeS58Gg1SeGQ4ESnhf5cxW1f";
export const pcMint = "4WhCGGTyLB75HsocXy6rZwwEVLYzcbqwFCibnm6DhJGp";
export const bidsPda = "4aLsNadP8bSf5k1qYDzxG6ThUwWYfcJTt3TpEo4rcsP4";
export const asksPda = "7cQAQJ5c8zrMmHeZF1BYyhJZAk513CX6Ni7G1isJXUvL";
export const reqQPda = "H4XhR3QwfdNofSNTFXRVCfB9uM7RpTA4exoS5qMBHTVs";
export const eventQPda = "HK5bpx9NR3pFsu9YR5dhfYpKPL78TyodDb7QdXfsaCrV";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
