// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "9V5d9XAhP3m82GK2SbCpUX9MUSMo2xF2LLFEFANrE1R3";
export const coinVault = "XnMnU6nQcZYopCPzgU5dUUsxpK7BbzYZRtQYNtYJvUs";
export const pcVault = "5FNQ54hWmHb9Fj4KZsxjMtBwvppF9pAhrGcgAAUB7MNo";
export const coinMint = "63yC4uteqmir9UeWkANsDEATyfbftaWzjznYtWSdZnLA";
export const pcMint = "8E2QP1KdzpUkaHoqXBvyoKfoSHyMw9nm7Y8bZm29YNj6";
export const bidsPda = "Gbjtmb1r51UTu4mDjdzEnSszFoaErBfLZ3zcLhATobrv";
export const asksPda = "4Pn7J2g61a9bNADREJMWkZa5gYjyKewTXxWoSbKmD5KM";
export const reqQPda = "8nFamU2KUBH5hvcDmdyP4GE2PdhqFQexbahCcEix9oSR";
export const eventQPda = "Fcq4Vrnv6X3E4WxpSVQ17LyRvpfaPLeiwJRCUHtHCe57";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
