// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "CYHnZPa2YX34XLKrJmE21J6qyEyxVYzcoknH8mNnDJ6k";
export const coinVault = "A5Mitvk8CJ2azMFCTxUyuAaJ7D2M7tM5yq8HXNmK58Fg";
export const pcVault = "FLyi1Kw8cWg5NDSQ8cxyiJf9bzNF9h4YhGsxeMEvyQag";
export const coinMint = "FW2hotRpjt9b8vNjKu7NzQsBF8mjeJXA67fNUEyHxRe3";
export const pcMint = "63ep5Rd4d92JABpa1kPL7PtLTpdutGttKyNe7fCWiVFy";
export const bidsPda = "FteqSx8ww2Xm1iawNzsW3LpxMVYhU4EvPE8eqtMyLEmx";
export const asksPda = "4AimGXDwS43JZe39cbRDofUoEx9ZHPiWaKBWXqrbc6Hv";
export const reqQPda = "5qZz6XSsVQoZfYCyvvC7cmqCyWJ1xuBHiEQSJjPpQUzb";
export const eventQPda = "5vXVzVjf7TfJvQXYuD44vbxCTP8FoZv1gsbj4oBHARGb";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
