// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "D4bypzNQhgWtgsiHahvd4xCy3sainGEP2pcP35V5gozT";
export const coinVault = "HzenYh5Ycd9FasuHrYLcxSTuhQ8AGCapLetjnHBL4yXv";
export const pcVault = "H1DZrF4ybLiYbSrE7EEqZAgYaDx9UYxUFx7M3sXSG8W8";
export const coinMint = "9Yv21MZFDUc6RHT5adADm5ENYGqXYhLkfRwykWA1Cj4p";
export const pcMint = "6YyTNRHFbyyUc3NsbncQEAaJRaPPJfr7kJuhxkdc4PWr";
export const bidsPda = "9kdgRfJ2LJjLHVEoxBT1z586AtBeHwtS6bFbL5gp4xoq";
export const asksPda = "CpzzQ4dUr9UMAhY3gnuUfbK9Lju1jD8Dw7KMqr47Kpvf";
export const reqQPda = "D9A2Nb9DAckFRhg6ZCTb9QqtANxTun94HE54bbGCeEG5";
export const eventQPda = "4L9Y3WLkmjF3HMjzaigHZfroxovUPsryYm1z8fBh6J4f";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
