// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "8d41vD4VDiZgYFJSqGMxYYpTw3E5MadCXXSsrXVEUCh1";
export const coinVault = "5SWsMECboXR2JT9E8jKjnxf3cFZ19ABgwvhdHWDNfbf9";
export const pcVault = "4nsZi2xa8jbqWYByHV3JdQYissV8fCsdNesdzWcfGMTS";
export const coinMint = "GwmivJzhbGLJ1kCR6DEaysaBmvTGiEuiyKQf5t8ZXNDH";
export const pcMint = "8qiTqS8zMJLkiogHarDUoFnifkUPcQ9wA2wpiSSVfasu";
export const bidsPda = "AAdmHDQwSJybu1tpH64JEKbRMoZKoBXxWUipFxg5ymMU";
export const asksPda = "595F6vYTErpCLPz3PaEGQF1omTzAvybn6K1nLVVXJgiY";
export const reqQPda = "8jhqBoQE77A2kFPrvfLJGQPKW5wJd3YJVCNi6SyxHorV";
export const eventQPda = "88hp6hU8PELQPfPpGrAMYzHMB3fhYFzqaaRWmrhQ6Voe";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
