// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "A36vhVd1Gj85mtByt96JHqoFVzUzUrVfeG2kLoxaL3he";
export const coinVault = "BNotEthW14JdT4yGn7e1KtYDRnRbXua6xqg3QfYWaDtU";
export const pcVault = "Fr3xcxXFw5PDuptp1CcEQwduKX7C3VY875xoWmZoi1zW";
export const coinMint = "e6KMKeUrYSBWFXPXHo8f6v7MJ3MnJddAPFsaeCKKYG4";
export const pcMint = "CtqCc8yNYRpjiquxfuDB2WZchdAtN99jZSYUaXP4tWw1";
export const bidsPda = "8KSheH6yDbTDBhaFLP2sWPGqKQZr2CCtDTU5nBmm9vRz";
export const asksPda = "4BS4sibCsgvAtxGEVMKh5apQDL5LfDvVvBqURA96nEL8";
export const reqQPda = "7xS6w51jVUZPy6s828VB82z9BWM3ze1156UFtdEmFJgD";
export const eventQPda = "9ana83KfkPKBB6nKkox8oNYC16pwqKyqpcb8MJ4DnVXV";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
