// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "C8uZGmG4Vw3LKBeo4gVcXTGFokdp5hVU8qS6zcGotqtu";
export const coinVault = "EfcYTnu4MXezJbu1SbYSk6ph8Uyu26HzTY8XNiyUjRAu";
export const pcVault = "Ao3hdGWUgKtppQj6Mgb6YAko3WaLgnKeNhNadmx1Gnbm";
export const coinMint = "De78cTwp32nDBEb8uzeUgKh2AUWC8Gnpp1FHTCzN5c7U";
export const pcMint = "CLgrucbrZBFmALjneVsxw4BHEtceCuLiktj38G4mottg";
export const bidsPda = "9cEYHv6PqipJv2VYMVm1CkfbkdaRSjkRbMooWtCDT1EE";
export const asksPda = "APbmSKn4QgMdLA8XKTmZcZ8aTyFa6oj4bB8g1HVwxtDc";
export const reqQPda = "CUErhH8HSQ6xHGF8Lrcg5W6VQEGHCuLu9NLqBQyXqXNy";
export const eventQPda = "4V9eHfMikkvHVFsph4Q6N8QCszKPxY7H6qhvQ1WAPnu9";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
