// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "6cPbQv6xF7HzY3gMDqSJC9MAvFvzwtFLwitiP8YUoREL";
export const coinVault = "GN9VC1Pi9afR41V5heuVbWxj8ebuSR8nM5tqx2PQnjCa";
export const pcVault = "DtcYiduKJTuLnEKWpnPwjSJMsHm5Dn5i4VDQ7m37sdCn";
export const coinMint = "3irgJM7hPDtTByema1Zsza6Ef8SBg32GX8D8RowGpTi5";
export const pcMint = "9qN7h2BFvADvyJH4KpSDFqoYo86XGHDpzid9PK4FYeP8";
export const bidsPda = "ATHzh4om8hTAnkjo3jrJN6JQ22GQdVEytMgYp9TNvbs1";
export const asksPda = "9dENJAvxeahAgNaDmZAKkDXPpYaq4hrmYoezXHYg3cUv";
export const reqQPda = "E6ZLnzgWqWvdfqBf6aA6zZnpHe2WZtbsQtNdoYhAVumb";
export const eventQPda = "4afNCfZ3FrK1xBnpP9Urd2ytaz3U13GAa6QDeNxjPVxu";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
