// This file was generated by a script
export const programId = "Bk7e6ygLwT1FoMu19HRoe99BSE5yf3WATXUVzvQGj8Un";
export const marketPda = "4i2FqpNmkFPxR2ZCm8eCX9Gr2zXaFhhiTNcFmT5qj5nq";
export const coinVault = "7ceJUej5E994nct31Bg841QSSVSEzBgkmrusx34ug4vA";
export const pcVault = "6e6Dzfv8zoQoaXiMBWRkCSzAoqRyeEwazEgULXzdBRyM";
export const coinMint = "AqdByZ5WBJ7nJRgsjXNJHhc8M6j85X3wPu6ZY8eT2KLZ";
export const pcMint = "5N73yCp57rr2yHXrNGorAZksd8SXgeEt88LmbSP3rMgA";
export const bidsPda = "GJfpVDxZ9VHyRWy1fvef4kWzk7GsM7U5iLxHhVyScmeY";
export const asksPda = "6WD5n2pfVmSPtaKTNF4a14SJLTf9dxo6NbxerNBLfPW7";
export const reqQPda = "C8KC2uhzwSk7zqU71rLfpYTpgmbbS436Uw2pf86QLHnj";
export const eventQPda = "HfJpGsdr9ihbFQehNHFSrx96vQZp2XJ5gMFqb8by8oUg";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
