// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "4wm6Je5MGm1miQvdz7GfAE8nZQP4twjQRCa8tjR3rnhr";
export const coinVault = "FMJQLQdfJDkKgAcTw8rPC34zEfGyyXDNRqhJX5Gty4Bn";
export const pcVault = "EXEQieUkSdww93eS4ykRBdqaoAnTPucsogm7Ddr5CX3w";
export const coinMint = "HYp6YF1iAmMaBTirdNgctX5NFRQVUEeY4VQTRzrxtYbG";
export const pcMint = "77cVbWwx5LCAB3xDcTGztphr9wFRmHiAbZXPTLm9D1tr";
export const bidsPda = "5AUM5e9HD6sium9fFsq6wGdLGiCWkNhBD2W2TjkzvBUb";
export const asksPda = "9pFnzDJeXL3xqSDf4Qac1bjWktfDtBzYGihNTLsK2HcF";
export const reqQPda = "4KA9bANKNq6aRAMJGM4RFD9StAmQqcni5tkVTEf3wD2g";
export const eventQPda = "GnYEAP2SJoFeWwXQSV3DRA1yiR8W4bziup2Kxa4nPPLJ";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
