// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "HbieTh7QKWayDrjUjPThpuABpdKMR7LCVdv6ZciNhJqU";
export const coinVault = "5FTKcdhURjN7HD36g7sdQCYwUhByVCDymSFMnvyZk67t";
export const pcVault = "CjzXdmNYAj1F8dMfc6nK3FBgnPFMvKQ4nCQRQcHvnyX2";
export const coinMint = "6rtp6zMTUMv8VrftpNW6SmAwPuugPNWve85o2GAc19Nw";
export const pcMint = "E8Vncrq8M3dywJPcrrpucjSVVPixktu2kPoEMUHXAX3c";
export const bidsPda = "7jyo89LJcKAyv2K72yMiELZeBTEer2TRPWy9qgWWCWJA";
export const asksPda = "7hSeE8u87A7WyHWok3BpjofeEWPfZ7AtUks2M7ZEkL48";
export const reqQPda = "47ugUhft1b6FzMAptwy9bdLVL4fwvsCPr7jxMMivswEX";
export const eventQPda = "8NEzzB4n8gHYwHXKKseiedpPL8J4a3LGJmGA99CNyHWs";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
