// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "CcY9oeb2Mpxm6goKXQ4Xf3CR6PLZbqhEkAfVU4sM1drM";
export const coinVault = "4xfUseTMHbbRScJBWz8ncwtFhMbTJU7tsR5qjXNDxXUk";
export const pcVault = "5Ea3fAsekQMMhnBrZPQzApNzjUVq9Ygyf4snG6WapuZ6";
export const coinMint = "9HSSgcWa2NuQ2barGqWK1pKVj69J1J2zQff46ZP2aPsz";
export const pcMint = "BpaiSkBgtdHxrv5zLP3yLqYWrAUDp5fo2wd2SPJwdUGX";
export const bidsPda = "3v4AH7TRZSGmDL5HQA6hhQQw85yg25bGekHRSZmDN75R";
export const asksPda = "2uhiiPRQyQQMqVCauqJ27CYZ35KuU5Jv2SkNXpzc9nU8";
export const reqQPda = "meY3m1T18cm53aJdzdS2YdaKaqn22utwT7pgJ96e9vL";
export const eventQPda = "3nk6aCNF3t8k6LYDP4rpzUqdYF5SiZsGLThnnTqjk1nH";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
