// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "EY7uc8BnDYp3tzeCtV76rugJ8Mhi4EYMcEdjhWf4j46G";
export const coinVault = "6mB5HHjb6LgMdW6jyAKrCqjnsXKRKDWQ7T3tA4tmiBkt";
export const pcVault = "7KyYUmEbVrNiRSgJo8b5vmEd4yV1kpFdKiCQF3MsZae4";
export const coinMint = "2Sp4su87oQuz3qv5agCxcJiBzFCehb31ZwzAMVjSK4N8";
export const pcMint = "HeyujHd1K9rYkoaWDgaLrqBz2up6v67iKJMqPQjPbXZq";
export const bidsPda = "3DxW8cZMwqoLp1kvvn91AbybH8goanzwTnWWKH4Qeit8";
export const asksPda = "r53izYkeqq5sNRmdtfz8K3nRfafkoRWn3nJPZURMNjj";
export const reqQPda = "DtoJvDkJKkFcQ5rKxRsf8hjNVLeQ6C51p6VLGkJsMc3P";
export const eventQPda = "6Jm3NTdA8ZyJxf8iZc3xadrq4wrDLQPA2Y3Qoa9nNMmK";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
