// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "B5d3koPfNdHH1KAHEaGgA7SYyFzn8D7Fbc1wzWSwiK8g";
export const coinVault = "AjJQnZ6ueXPkNuk36PLRWuUnCJQfei3mZsNLko3rceLc";
export const pcVault = "BpC2eCqWTA5n4oWAypJZAHHHyf2MXbwfLfWXzh5R8k8K";
export const coinMint = "Eq8M6r32BMf5q1RSrEiaELx4DdJjpycgHeTXeXkRbUXD";
export const pcMint = "2QcYkD85NfgdbPXeq8iYKW6PzU8ZfNC3vfqymPRtJNX2";
export const bidsPda = "Hp88BoEDTucS9TuMFeG1mnc3BzckT6VG1fG8emLK8hn";
export const asksPda = "DVwUTPWrKw4U2fSs5wH5HJZfUChakMSzra5QvtXMvgMm";
export const reqQPda = "42Harbo8RSECi4fihjghVGxfKJb5mmaLWThtJoufHPB3";
export const eventQPda = "BbqBcQ92jYALkT5Zxs5Nd3tk2pbdcFbaa3iZXLNWHMWx";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
