// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "Be9Bi3Zm3W4CpLe9aAj8CNCUjYQ7bsU1VdhvEGKyr785";
export const coinVault = "8QShZ9ZRXQEDWLpHNkagurAibRsv2r94RXMV8UZFcFZt";
export const pcVault = "3KPQkEcmwQMHDech8yGW9f18datYphb1qEuoSc78qZUi";
export const coinMint = "9c84fbHskuGM3pisPuwkvZansVEKQWRLugPuKM38A8yD";
export const pcMint = "CTAHizJpAzSVqpZz8e6thkcDxyzwHacYU4N9paNN97VF";
export const bidsPda = "5afBvpLzrxkqjMcbGyAX65Fy4QRifjWAejgeLK6TQyJg";
export const asksPda = "AeG1LSZWKoSnK4UWKJh6FWPyBR2hLJn6VGouwQjDkrqg";
export const reqQPda = "Gxkk4v1o8zxpxrAGV7FPyAVH9bxkE6Lr5WVsyRJ4Vhvz";
export const eventQPda = "CkvpWKL8rk7KHxu7pWKoYS655Lx9kj3FQNLQRa2ckPTj";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
