// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "HMftiAqa6esTbMZrsZzKA8HtEtyiy9vAZi9gBUWQyCLt";
export const coinVault = "7Qnf9v3CtVU6PxTvDXamKL6nEVh2KFznZPfXFp9T5jng";
export const pcVault = "8THcNa2xgjRXCbwatoe6JdyvAEzj7SvL6QeQRq4SgMK3";
export const coinMint = "7ELjv1PN1PaJ8qZJn3jDLfFPuSuwmwbF5grp5xhJjKfP";
export const pcMint = "BRCW9K16HffgZAQMayjjJTjHQEqeHDvUq8iK56sXzSvA";
export const bidsPda = "6Kh1dZ1cqj9j1jstBXyVynVHs3ti6kaxRe4M8mUUXXDp";
export const asksPda = "FhXnLHC59sGWdtpP65N3aKNFhFxe8G8WU5nSoF427P9L";
export const reqQPda = "CTXZNeiChrhRKFsHy4A8VoiGPiQa3NdLqbBC15Ww4Xqu";
export const eventQPda = "9GRZAfWSQgT8k6uY8FQ1yRSfXkuyfJU2WtCUDN6tw4E1";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
