// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "65W8CGompEjfLESzJtMdjB5tX5ogNVAiTiNaraPZb5V6";
export const coinVault = "7F1rn3d5arn9q1CSS1R8iSkeVd6HZKzBw2voS1grHtvS";
export const pcVault = "r3cGxsczVe8tNmBBuNpV7oX86iw1Y7Rx55iXJ1Akf3p";
export const coinMint = "5eoRMPyUMAvNne3rucjCokDULtFPuYv7FQ61ra3k8KW8";
export const pcMint = "95V4TB7s4Mt4rAsU2KogZYbvdHZtJNFn1t4oAD4eXv3P";
export const bidsPda = "AgBXuNws9C1QfTggQ6xAemLJcg1JuNYu4fD9pHyUf3h7";
export const asksPda = "CiwbB3aogGo9f5YFmnq3xQGGtyYobaS4PkwhjA1TvTNZ";
export const reqQPda = "74GbQAztUQgBdvQ759Firsm8BLkhQZwBHtx5ZTviSQy5";
export const eventQPda = "2asaLeiGFVcY58k6LKvJRb41iRmCqSrmzWWCzqrJfbcp";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
