// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "8FGVt6n6smHsYyHoac9hdkbRyXndz7KBzU7us8rnozdi";
export const coinVault = "JBgfWzCmhHxy4ZMkN6eis1zYbF872dukRuY5WcLjzUmj";
export const pcVault = "6NWMgVm5KPuPdTgSGeoEv7oEZ4RdF3AM9wkMM3vbUYDB";
export const coinMint = "FderWBFuXUWKoos4Zwrud7vRqNjvT7CsjVmEKUAEWJ6G";
export const pcMint = "CVCY7VgX12zdQuw1d6urg3CHUpT8SJQnrvDey1WVCLLS";
export const bidsPda = "FbEtVjFHNDDrK2YU68rjNNMpDRaF8dSWRszaGqDaGvJT";
export const asksPda = "95ZPnU6SWGh5rojjMsbxhgZuPTLeEEeJ52QTB4WrtY7F";
export const reqQPda = "F27W1obEAFHMH15t5qD8jjS6QDfhXrerznSwAZRgdkYD";
export const eventQPda = "DkAW1itH2XL2XgxhYtjfb2WxX7zi5LC7cWWdy1MSUhW1";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
