// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "HRxmokwFmu7uoudX2HVnwvMHHohMB3xPLAGhrjDx9NwY";
export const coinVault = "3KTTAsnEzNTHoZofTJffkz2dqccHJzNfEohyaK7EfGuS";
export const pcVault = "hNozpk7j9wBKGJL5QWcLuuNyyTbCifxzCwL5YGuQjpM";
export const coinMint = "F1SQDDTYKSL8GkdwfiDCWcLYzRKhBVeyK5jtM2YGZyCB";
export const pcMint = "8Jyo53NF43zRVgGBhKejawwG3WNiW6nGDkiycHA5f3tH";
export const bidsPda = "7okFu7hoTm3nV51vScVChgjvgspQ4e6wGMaVCrUYyWou";
export const asksPda = "HWYbXmQUsd6CkTdXfnrNM4PXsrzu6LQBDLUhkhybLCsS";
export const reqQPda = "9WnmAun9J1fBV73R11MeYW7nuvxBaqUjSLssTwtQFPP4";
export const eventQPda = "6CYysrNeqax3ttsTSvjmiQ2YkPGXdFV2dx7mroaNAhMo";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
