// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "C1AjDaoq3L9TyzUvDBPmv56dp32ej8emrQNQUxTPsZnK";
export const coinVault = "5oKtQEpkiuxj2jUZ5qcbiuvGNaFLWfKDU2YihrdNTusK";
export const pcVault = "6DCwLjphyeYqYetYNmgvoSPEu5sJdPQb4zwenzJBSK7E";
export const coinMint = "EFEx7qDtNUWemtWsRXqvbbK5MGZ1rrftbVLSWUZRkYjy";
export const pcMint = "F36gxvYA2eS8MeuqYVGh1eXKwyd6yqVmm3TuZtkTmom2";
export const bidsPda = "4iaNjbiCPQ25o6YPf7rmM6DmNnG3UdU7ygWz7EjBgm4x";
export const asksPda = "7rFCwZBrLTrE3rioqP7svbfPhxVzHZrtyhkFhD1ZmJST";
export const reqQPda = "4VSV6dBnwFB9oHacseuXw6VuFPGTXh2JNLN812H8Hdu8";
export const eventQPda = "ASkMGeDLedeGdw92Wnt97j2KNFUD7fNTBCodjA1d9Zad";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
