// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "5Z2PmjL3S9ZXXuVsNUVa23mwZLbTAW2uvKaZxh3Rbt4p";
export const coinVault = "JCjSG3e98RRB77neL3f3CQom3MdKSk6soqPUc4qEfkXa";
export const pcVault = "8J6ivfuoEkWjTViDCYugZKaxVu3gEVoXjha4oPXbcX1";
export const coinMint = "AjN7xUptSXgYn3mgsQ7PBHoNiahaG9tpYurUiaXC3xTD";
export const pcMint = "8bEhPuchLYkh453x7GJX9eRKkkxYRPPWb8B4wdDcahVM";
export const bidsPda = "3pNAj9XxMxX6Du6JpvHWgf76HU7jhNyMn2r4STEexTXk";
export const asksPda = "EbBBRXjKvuURF2dPAsp5q4uuYC76sAJZRitTH3jpQVDj";
export const reqQPda = "CSMH3pHmSrmaRGDZ8Pb53wujSjp1NfFFNdVhCozeqH38";
export const eventQPda = "EZTuTmNeExWsZddsQ4DJUmWPgC5dy84BuctSaprn4mBx";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
