// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "6zAduwAbqFNP7eAGCQnndaXGbQVsYPZej7QPwiNoiPm6";
export const coinVault = "BEQqnwq2pPc18porBoTG9QTBiUNRf8TqmJMTat1smaC";
export const pcVault = "AwMka3WQqAzyaqhEEU3od3VJKQHhGDfjtLMsHcME1p31";
export const coinMint = "AuydGNfUE9Gau2cu2vtcQzx1Y72cvqJZDM1vqL3eyy2z";
export const pcMint = "5eMMRqyAYU4855V9FUomQmBWUZHWu5h8G6XJA2aD3zYi";
export const bidsPda = "84K3MXaevendefSGcsL5FuHjWAVPwvUdeBfaG4b9Bp43";
export const asksPda = "8NT6oqycBnK5vq6xxkzz47CcNfEHQCSd4qfXyYgbdYf";
export const reqQPda = "DCRk1gw5mV7AK6fENzg1NUFFHHUHsnjfnyomPZbJ7x6K";
export const eventQPda = "LBa9ScmAk7dqb7fCDExS2Fr8Jc7Vt96pEwvnMeezajf";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
