// This file was generated by a script
export const programId = "Bk7e6ygLwT1FoMu19HRoe99BSE5yf3WATXUVzvQGj8Un";
export const marketPda = "D5fX7hvn1s1d2BMKNgJ3AryKz1183R2hDZJoxNjq9ZGV";
export const coinVault = "Dd5L8PAtp28GJP71qgcCZ9vone8EQAoK9cmtEYZkZ1u9";
export const pcVault = "GCQNFMnnoKPWyfdYesQBzN6SYD9W5c2w6jg38w7Rh7Vi";
export const coinMint = "2f3ZFDEZaMT5e3iJwsNtsB6BFe16ZWqDNJZVdatS4mAz";
export const pcMint = "6ayuUekjTXmBoPjFKzk4fQeJquSiDbbbRh2J6NctxxTY";
export const bidsPda = "5ttjKLWbqNoEGHVJ1QSKEuqxvbuQaVCiCuAgiHYj7Yo1";
export const asksPda = "5UM9kGWnrw6opeVLUJZZkUkBFo4FLkdXAkSXrtH9Rjp9";
export const reqQPda = "JzRVYkLzWVNw3Pr6H3Q7Qz7eDvNLgQ6rnZSiu4gwo7n";
export const eventQPda = "Au5SCwc5a7L2p6vWE8XhbNf8ezepGEa7YJWCsqZwhoaw";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
