// This file was generated by a script
    export const programId = "Aodrp8JRS1tCywT97x5ytaoJYczv44JYtyBHDJGLCx5m";
export const marketPda = "7KxkuqHRKkExuthemPQx2u47i9iEKeUnQdb6frNq1o3r";
export const coinVault = "3rEHzJEbVzLvmtGnP3yre8thJczxvLbYxCzmFM4vgyhV";
export const pcVault = "EyCLeDJPaHTiiE8ZwnmtWr4DVMKYPMJGxoMAdqgADp7y";
export const coinMint = "FStghAXszxMpKjG4j5rrxteRWZrneSQETCDeCvykQ2FE";
export const pcMint = "38jLwMfc1wVuXhNRF3nUPMsmjX25bWwUbxjEx7wScYSR";
export const bidsPda = "GMtUY2E9iRgJKhuF7QxBVK19GLx5HsHA5ZwKrdFZzPCX";
export const asksPda = "AVZPdjjTvF7LGpz4uFK3dDPGfDjp4uuCG3FCo2fsLGwQ";
export const reqQPda = "633EWzNq5ESgCx6rfx4UUFP84mDBbdzEeUqnyARW79GA";
export const eventQPda = "HBTcXmqyH6d4n7i7oCL2Jg3rRerpNkQymdvsrPHYSJfy";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
    