// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "C12CnofX2RAatFgg89LKQNRpXNAEUKMfxV3nGXsNeAK8";
export const coinVault = "GksjBBCiy7TtgCPJ4jyRtkiWXSUTsCNc6XpWfzTneSJZ";
export const pcVault = "CbB9ufLUBxG9cwpYeip9VnDvAQL9Sb1q6LHRAkQWtgVM";
export const coinMint = "77G1p1kkL99mnQNY4BWU5dWJFqsx9sdeK3hP1ioYFE9f";
export const pcMint = "Da2TWBPwGfjJmNvHXtg3M3vnPzyuwxSnW2i9ZTu7yCtn";
export const bidsPda = "Af3u7KcMPSNWgLLseFSE5NknooCaz6hAVw5i2fPwg3Ex";
export const asksPda = "5LnsM59KZC9V5Xf8uWzkeFcyLbjtkikdwC1dMcdaxB7P";
export const reqQPda = "FJ5pNWrwwFqE8dEJkuxxmX1DQvrjqjq586tJnvQij8Xf";
export const eventQPda = "4bMQ8zApH8nVX4oCMookMEduofJF7iRX9K4gGdztbLdh";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
