// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "4P4NoF5gpSztDSUM6GexSUDP2fzqe2C2LBV8iXYWRUnd";
export const coinVault = "BUiEoYweZGQ86ZSte3qgSMb3wpDW1xqap5EQ4SiP4KSd";
export const pcVault = "6jENE1oCmFkzHH1UAdHRLSkaXEk5nDceCAAk1fBhQncn";
export const coinMint = "AUgv183aefcYX2etHNsfjttw36A3MAGeAY7F9AGeXsjC";
export const pcMint = "F6CFpAnpub4pabud64szJTWsNzkBUn9wirAASdmeyMMb";
export const bidsPda = "6QkhhjJDgDY3JcMbzHvrGWq49cGdC2pnUkUwnA58cyJD";
export const asksPda = "8294dAQhu97AgwyxXvsdbqZXoDs5LVNkFeG9L8iDC1fD";
export const reqQPda = "9rgiJQSd6TAnonCLykmFgMVHpFrYjYNkxzzus52Jr72v";
export const eventQPda = "GzDqF5kxmZggnJSJvaVAFQqx3HzheMLUtqw22yqsBcei";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
