// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "HEsNYiTyymnp7Ek1KnueXvCWnMGT4gwoenhFWMAeobcq";
export const coinVault = "9eyWQf2X4jmawBykUwq5acNmuBuUFcj5BVkgoHVCJfkK";
export const pcVault = "2Kuug6zeSgpTA3LKtGQqSVmeGwJD46i6B9CfaM8gxW7r";
export const coinMint = "4qwcstxwzqrEBSV2eoYG9rQddtP6M2xJEWHgCutoCQEi";
export const pcMint = "61S7r5VMz6ypBPGRwNmCmiYkoDP1icT8mRNctmsdqCD8";
export const bidsPda = "BhK9k56s4rPrCYNcot5XHuFT5wBXwqj1VkLYUoQ2sBji";
export const asksPda = "AWV8yzrCLvern2apHcoURBuwEghDnpGuAKhR16uMRAXU";
export const reqQPda = "Gav4FuqJ7ATnzHqP8NyfWv5b1PRJPCN94bTfaRxQDeHv";
export const eventQPda = "FPCgBHnUgn7nW6osCFgdL1JG7jeSoa3E3FK1A6Dn3uav";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
