// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "9K5LahewUKPh8jpUxLmGUAefWqTVtxwHbgKgBdASuW2T";
export const coinVault = "3vFMCnfZXnS47kqETp9Yd3h5w5zvVa5CGSv3JSHDmGFc";
export const pcVault = "FJ4bWK188aNZnWsopiqF29JmARcBon5FbraJc7W6HSVY";
export const coinMint = "ExNLCHTSFakfgnmbdvuRnFym9bHPevUN4yNv4zbHyyr8";
export const pcMint = "A8AfZb6Da68QN6CzMShwVYxm6cZV3Pjqyhzg7vNd6f4Y";
export const bidsPda = "5RVLAYq4FGcLVezYw2Ug6aUx4PrMo7iNmfphxpHXgUec";
export const asksPda = "3ZnoKWLWq9Q4Mube8m7LT2s7p9G9qkarueC2dQUFYN5z";
export const reqQPda = "FEQHyXfmhCfn1SJXGuFuUVP4piwBbKetALjChzrCKSG";
export const eventQPda = "ByYTWb1VspVs4e6NFXAopT7q4Vk4oZiufhpfBq2DYR5x";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
