// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "EDp6p1uACh4Biy21FM2c3gnsV5FcSHjajTmYXDFk4EU7";
export const coinVault = "2Ztpzmv2KqQAV9wsjPGPHaxEWrEX6dn9CvbUKFhjWb6N";
export const pcVault = "7ruyjutNKfRdXEzMmNczcU1CzzDPv9a7RmrQYNeaK1rX";
export const coinMint = "GgUzwJyJbXiF6c45Grp1pipuEdaUHdU7beVyeLNSMe84";
export const pcMint = "MaS1hrxhxGbdcRL3atJoGqF3KbmweBsxRC4NyYmVSwX";
export const bidsPda = "2dY7tMft6cp1CzaM1RERuFMVM8AWWrFgapkWfmLhSebb";
export const asksPda = "48uLXQr6VknrGVHweE8yZuav3Wdw1Dk5UuyzRnnSXjez";
export const reqQPda = "9octCRwWg14Hbot62czb2YFZUy71jYQGyPTTPZPqJpgq";
export const eventQPda = "HMNVCayhtBr5qEzk5FNV3LRMp9yYUDzwZ2m4WH2hFQdp";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
