// This file was generated by a script
export const programId = "VGwPEHBUjxa1ZQyvCAJ166TsKPYCWKafJoDeqdXqvdJ";
export const marketPda = "77KwYUX25dVYmY8iZUKUkCndmbDmsYr1cUevcknbDB21";
export const coinVault = "DbRpWqCcZHhvfq5X19J6V8BRL142CtfLobdDmhhknhVz";
export const pcVault = "Ftm8xcGhCXqPZik875BFKVggVvqJbtdvQrCxq6hqMziK";
export const coinMint = "2z6Cq3kBRNzmBVzn4psdn3oQTev79MSaa9RYUmMajbYJ";
export const pcMint = "2YQhqt6rRPaCLx2nSDMmiZ5neStdfVQKaSgavNniE99P";
export const bidsPda = "2t4EhbPF3f53ScBw4t3ALZC6nbJBYUVLCmcZhAWN3Mtu";
export const asksPda = "G9bB2hsGry5QznBamMEVBzdLF1gkBrFBPvaCm5iZ57Sr";
export const reqQPda = "DsyLvScG9VWq6ZLgrLGENDqLHmrnGqU8ARwLjbjSgw6d";
export const eventQPda = "Fmhb9DMdoroEYEvdo5BZ9EqsV8WQFBjLgvgxKPcBqTQ2";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
