// This file was generated by a script
export const programId = "Bk7e6ygLwT1FoMu19HRoe99BSE5yf3WATXUVzvQGj8Un";
export const marketPda = "D9LzLVVe1QXkW5BZ7cthjvN39XS8r1ZVqENvwShZWhK2";
export const coinVault = "4KrTiuGCUD1E6QMHoZNt7W9uDzrD6DCHHnox6zt1MJPH";
export const pcVault = "ArGoH7fL8ydoT4RPdvKpzzGMN8o8ws4fQtposhEVLm3D";
export const coinMint = "FSd16Vn5JjXmYTRVGHs2ExCM6LxN9aRw7GsFFqC7CHHq";
export const pcMint = "HRPGzkcsYnLgJdA3vFuPJGmc5Curvh9hb34eqypDaSEY";
export const bidsPda = "J1b4PRBjmoWBnc29E2ZoYcKjjzFZxpnK2psskMX9pFWw";
export const asksPda = "BryeRp6oFjPdjtr8nz4sGds2cG196Ef9WArpnTAvKWpn";
export const reqQPda = "AhErGLZMf88wk8vCQWn1nQ29bEfQ88gxCBDJQY3gYVuw";
export const eventQPda = "5J8LD8EbiUeWaUihvLaheTwDeKVC2ZgUToGiaovtmbF8";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
