// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "Hj8ReK9LwyzXXgkpgFu7eufVDggHqwFBZ5YmwoZfZB44";
export const coinVault = "7ehZpiyLQZLro4yVpboPys7D6wSNmxVghfMq2HjrdQsj";
export const pcVault = "GUUF1tVpmuTH8tgniFmxMrg2sMnDZU6LeK3jCwFuP67s";
export const coinMint = "6zz8SWqbyYaeTRyhfYMW4HbwWmNKjRwVQaPQXSJ6xnaD";
export const pcMint = "9wG1TuBkhXwGed9z5z954wYvmvReHNyXyi3Uc9cY7qXP";
export const bidsPda = "5GHgfCXqD49R6SJaz7WhCuKNUWRaXX3NwCScrGX53pnX";
export const asksPda = "234z4Lc97YCkMswKMA8y9dNgnQG3cepEK2z4aUqU9MBy";
export const reqQPda = "6RhnLasXmNM2QVu3apgkcoyJguCnwEbTSq47R8dnf9F7";
export const eventQPda = "3A1yDXREvTub1PF2yfuzNShNfrxef5HUKGfbwjdqQLEw";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
