// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "JACnmdiX33uxPHwzm62N2TUySYxpmXF9Z7NNiChETHv2";
export const coinVault = "9qdQ6ntipoyutT4Y6FzXu6UhpPigGUGkoUvimYCzW6yi";
export const pcVault = "B9JgZYyjjpAdfg36dWcsEkqGfp9wEeTcbPQjFpYPLmwy";
export const coinMint = "6qD3TP3ap5T4h15bvGa2AXarYQEkg1C89GSF1NjW29Ai";
export const pcMint = "AqCsoQiu6dFbdFLNVupUoVFbM2VRoopxwhbVrfqJtNPt";
export const bidsPda = "B1QLSxXHpz2X7CGCQ6bQAK41neAGPYZ8LtNkYJbMR5vE";
export const asksPda = "2EPcqUEVop3RdyPvTFS9npKh8rejLS1spj2JzNojLaqE";
export const reqQPda = "BVfrS39hbWae8v8vjgwGUAFqUzFh67GY9NYUQmQypQyh";
export const eventQPda = "72c3QgkHSx3KV8Uxe5jwYHs5LhXNLdGK5dZEnhJ899fn";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
