// This file was generated by a script
export const programId = "GJsyZs9cr8agF6SLiLfxiS9A11Avioe3JVPie92N4SNw";
export const marketPda = "8k1aGapJ8mfXiVd3tU8K1xpviarL5SGtaWq7aovdYAuU";
export const coinVault = "CVX7xoBAa8iYmj7gnHac1NvJ8aEa5BkW2x8LkvHFsKVu";
export const pcVault = "5guz79UrFWi6b6Xdjwx1LVnSjBheSoKtVwFCphopMLk3";
export const coinMint = "86aCdTDjXAsCv4WQ41hLrPHsRXHgyRE1jGDTmp8UbcFZ";
export const pcMint = "2J5bKeEfTkpkjZyA7guBC1G4p9h5p2bPUzRiY8ERkrja";
export const bidsPda = "8VYJMHexEiU3AihkBoT6x2w3jwjtU5q2nv8mv3hdJ7Fy";
export const asksPda = "AevcCamBjSesbpVf8PzsV7DgmGHWGUu1UJ9x2PbJsaTB";
export const reqQPda = "7BtYbKMLDCbUdmwrGaZtaoEebp486ZUC4ETvPvpzeiLe";
export const eventQPda = "6z6Mcm5QjnuWN8FN6Xb2cci4MFKAqHmmf9eMYrYXjxM4";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
