// This file was generated by a script
export const programId = "GJsyZs9cr8agF6SLiLfxiS9A11Avioe3JVPie92N4SNw";
export const marketPda = "Hr5QmHFLNcF2CGscvb1SsqzVVVRqC6xuZwEG4TVLTJba";
export const coinVault = "86Cuj5zr7Y2vhgYLoDpCNCCvBRUjn12WokV2szcfVAuw";
export const pcVault = "86Kh7rqtmGbfx2nhK3jgMjNPGia7ue1ALivBzJo4ynxj";
export const coinMint = "6uWUGSzVumRYJfDC7dcm7Tirw3Mc8oHEKyPXgzHekzKE";
export const pcMint = "59aexdmXuz7S26csdjnd3WLSjBjrVdtKvv86cxMAZgpV";
export const bidsPda = "AFgsznDLXzHrGPKZxBwDp8u5qvBUyMnaLPHR4aYoUzZ1";
export const asksPda = "HSjWwdieGt3bqYnXV5nM2DpVNMg21mwGdBxT1wUhGb8F";
export const reqQPda = "4fp5RunE6dkchnbmR2wb3DX63ASd7M1Tov4T98rKQN74";
export const eventQPda = "6LLg5qauDn8ckGyhXkmD56E44HCbNGESekJQQzsuvr2C";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
