// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "6Yt5FaAsMKjpnaxuC6v4EXpKcLKTq7bSPUG1nNgfMe5i";
export const coinVault = "B4YpZC1HuHd9TD4ZHL1d5jWF88tv6NCYDryC7DmUed9z";
export const pcVault = "AuvCKydZ6eApw3X3hFKqautotGpaQgzSVEjQxjBj5SMF";
export const coinMint = "GL3zqsgJ9hcvf5re65cqokLnnz7gsdzY34JfKAYooUAG";
export const pcMint = "7sCxySBcV65DiaDB5HLcCqAYpzHKrzaPy1gqc8G1yYeT";
export const bidsPda = "J8Grt2pXMLXQERnvqPZjcKjiouQa1F36o2wtKgpd3nLa";
export const asksPda = "2AMoAJ7mUHu5xei81mEaHfmiRrJZVE8Egu8MxEr7mimA";
export const reqQPda = "2GMMFeajrpYG2MkJ5PfEy2qdxjek5dSC3dB9h8KY77Jt";
export const eventQPda = "E7SCGMkd85drvCEThL7BVVLcEQhvVDmqU8azv2cKTEh1";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
