// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "6JmrQsEq9wCDNnijtZKyNvteDCneNnQWDNdfjmSH2Jvw";
export const coinVault = "2noCMT2FYz5S4oqFo7jziwRuEbSYarvdHc4gPtX35M5X";
export const pcVault = "4rKtjRa3AnoEFUSSZx7koRGLkmFv8CCrCccXj14vjbyC";
export const coinMint = "9GepV5Wk87wXNvvFjQCnnk6phzzmizozbkiQb6kdYP73";
export const pcMint = "FB2PGGGsb4KAnrreVsSAfQKwBia2fb4Dn4ZecPgtowCZ";
export const bidsPda = "B3x24RUT2JiAaAJmztumv57JRonRg7iwfCoRZg6ddBPF";
export const asksPda = "13KjFCcNLM95sy19iPXG1JButwpHDhSSH5mLdpgKGago";
export const reqQPda = "GJB7mYR8ybLKgZHBsniX5avR9U6mDJDtTY36CpwhUgvu";
export const eventQPda = "8TWwSGbjiYqfzMuV77dWtxeY8k7tUcw7Dv8fkWLZg13z";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
