// This file was generated by a script
export const programId = "VGwPEHBUjxa1ZQyvCAJ166TsKPYCWKafJoDeqdXqvdJ";
export const marketPda = "DpGihvus8ihXhG2d4s2AN5qmGmHd4S65D7mSyDroFiD6";
export const coinVault = "CiGDdQbC6Q8Y2eqyHcf2u1vsoQJ5fKsNivxXdiLm5ZBj";
export const pcVault = "F9cLA9YXcVWcxXX1wx9McUPRBFopcGcLsfVJGv3vorK3";
export const coinMint = "DkpkYv3doEK1EjWHr783jQvvSD9TXf3NrxVaV1mrZxdZ";
export const pcMint = "FY7Mk4PqCaKnxmLMDkbAEuC4wCh43wRd5JJDR9vmrZyQ";
export const bidsPda = "5QuDsT2niHiat3FDYepsoAHoqshTv92pypZwLy3R61Uj";
export const asksPda = "AAs3uo8mPW896NJEA95eSKC9VKmvYNnDAwuF8hBV6tGy";
export const reqQPda = "2eQFvaJ7QYX4bhJHxEUGvj3874XmHDBqJYXKG6HzXP78";
export const eventQPda = "2BZLHphBufxFSRLZdVHfbmTxxUPBNceBYLKEXpBkoWGC";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
