// This file was generated by a script
export const programId = "8yskqQf58n63JFYLPHhp2dtC98gNYYsjEp15XmBJV8u5";
export const marketPda = "2GXTC3GVFgUvCdEjVpbgFM3ssgygU5wmag8gG385yREy";
export const coinVault = "7PDei9zgBJyjPZe72HpiiDJsKpyLFMysjK8jMhAC8SaY";
export const pcVault = "6kYmbC9MFTnKWuZTF6GjPJ7AhHXUxaY3oBWmswT6L6BP";
export const coinMint = "AFnsFrHyeZmn5NdS21hNPuW6W8SSqSFonRTt8TqhwZVy";
export const pcMint = "FJKcV881Uzf7aWfCU12fjsxrq3TebMRfjZjvDq23AAzk";
export const bidsPda = "5KkQCARa6RDeZp8am34CUBWhw5bEr24ydk5RhMspMTYF";
export const asksPda = "687XgPy1EHPYSumdFgFE4sXxY6v9VuKEwimmBRjf4jti";
export const reqQPda = "6ZTAUp85BcfpcMgPX2pZeecpCpQC8wjvxXr1PLnvdjY9";
export const eventQPda = "8gg9SDgRx16WvDXFsJWbcekPoAzWHyfmzYgXY8LmCMyz";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
