// This file was generated by a script
export const programId = "3Ek56WB263s9WH7bhGtjpNkFk8V2UDXmvsKxDJ9RzmGR";
export const marketPda = "HXScDggyKgLzB4hhyaoxzktyNuJ6F5YTkXfbCT5p5mgF";
export const coinVault = "AraPiwZPSfAqT6Jm1f3DBeSCMZTfy1au88LqHzjJVeX3";
export const pcVault = "mSmUFSXiNKmHJxNEfLYQnkDXghm9nPPgfucR5WiSAup";
export const coinMint = "2x4FpS2krgMvk8WMYLvxaNCpEbdDeLAqVLex1Q8Md7DR";
export const pcMint = "5X8j3U8Dr1hvP2VujSEV9h9WdzhfojiEdvgFyMukqHdC";
export const bidsPda = "893tJAWmSgqo2ajcAsjvvxWuN6SCNqF6SU3561twmX5R";
export const asksPda = "B1cXRsw7Lr8N5tsxbxc65YSS5nRQhr3h4vpTeEjuGuAy";
export const reqQPda = "3U9PJjE8wHbrSFcMsDekFcTuP5kUCXkwKLsWVNtduL7L";
export const eventQPda = "31Ew79uWJjn47CkCeu9Zx8PucGdQWE3patoV41pVjsuc";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
