// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "GuFCvXC42ZDPXXb14y2NsCBRhMNNd6a4TnfAattYeTPQ";
export const coinVault = "9RU4Dv3kwTJWiqQGvAqWqMhtUTumq9HTgC9WbfFuDHNe";
export const pcVault = "7tR3Vmjddi9jTfttpoxJR9ANs2C8qeU6ep7VjRMUib1h";
export const coinMint = "DkTqXDz8b135Xnk7HwMPgAAopcRyA994GKeiiFXmUUbq";
export const pcMint = "GwrxpTasKBHPav389yqoMr99gVV9daMiH9SnNx71zUM7";
export const bidsPda = "6mwFZADJHc8N9YuqZt3arocnUtbJEVjymbBi8KC6K3Hm";
export const asksPda = "5w2zBaMdGS8aTHJ5pJRNzcKADK2kPEnvGvDwzfmrKkHU";
export const reqQPda = "7SCpNs5HbCp2sT36EciNjPDL75q7P1n4GCu41xd5jmTt";
export const eventQPda = "8BLpC6thH9rF5cdmyH9nQB89kUifEFqKuKdfZjnMAvLH";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
