// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "G1S47mH2wVCttbMz6AfeU8cyoRtNsyy4ccU3NHdD8rsT";
export const coinVault = "Kx32JP57E7Kn9dC8vWraYQpL9HytnXboXsbEStaQ4uX";
export const pcVault = "57qMnYhRW86d6LnrX372aNqMbah7S59UtNEqVYCXPnxV";
export const coinMint = "9aWxfWvttybMmgg1sYNKwjyWBcR5CN34nwFBQrhwbEZF";
export const pcMint = "DHnYLUmKoep3vbaqb5STaLMaXYXbfUweTthGyUNskHYu";
export const bidsPda = "DuqhHuTvUtCZnaXw97TJoNeo5r3zigrT3YHFimkCKjxb";
export const asksPda = "4ocb3PrSdumxPTBENkWu2MQvQDXSLuhCh5kumfgn3tjd";
export const reqQPda = "FzBBuZ1TvnBGMkSpuhZKVuQJfyi2ikBHg8BxCLyBVyf3";
export const eventQPda = "GDkmFTLxXdmD94JajPnPCmXghYNyBBSL4yV3xxJiw2MG";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
