// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "ERZNry8A6ij5iZ6upasmKevfmwLyWBdqpsuGjXiuMPM1";
export const coinVault = "E7FncjpYgZ6i2Y6hZYmC59BzPMMR1f7LZSp36NnuywkJ";
export const pcVault = "AswZYvsBZr6SpmmsJx6kLaf9v6ZLmmKParnz7XDUqNGE";
export const coinMint = "HjdZfWAJaKd5XBU6WoFvgWLEHWKw2TNcwvnNGjzHFgJ1";
export const pcMint = "BvdAY5NMUBzvzQCy8G6gvqAYeCUgSrRjufLHAXF7s2Tm";
export const bidsPda = "22KyyYAg9yrjhqYcqNggvUMP2WSangArS9WsB6Shn78K";
export const asksPda = "HmKsppikuZSUd9rYYamLjkN84UVdEkXzYXw7WdUo65Ud";
export const reqQPda = "4qcRNT7a5Y3sT2PzsTiDLEktdQp4nXtF2MJX3Z7Fqasb";
export const eventQPda = "8J8TtWMQamT6rkdTuyLT2vaCPtrguQVTR6UzJfUuxjUU";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
