// This file was generated by a script
export const programId = "Aodrp8JRS1tCywT97x5ytaoJYczv44JYtyBHDJGLCx5m";
export const marketPda = "CsEKVrVR5r6Lvw4T6Uo1mmayjcgsZY54CcaU8S9S3yY";
export const coinVault = "6Z6QyPjzeTXE3zMEokurcy3ubs1RHJa2Hwujhat6wJPX";
export const pcVault = "RzyMRPcy9hhP2EyAMCVE3kC1MqEfaJRweTag8oA6JmM";
export const coinMint = "7XLVC2unz3jHHsk8EsgZeV7ivnumM2VnwEwaGU4JAvH2";
export const pcMint = "FSbvrJ4DfzxkgW8XuQio8uKAYX9iF5seXK6ZvnSTc3d2";
export const bidsPda = "CBk3SGkYJe96M8o82xC6dFNSLeH8NABoWcxNGAtG2Tr9";
export const asksPda = "AuXgQp5pvxWdwucg2GsTu54CYp4WDPw6Datg8RXAZTpP";
export const reqQPda = "9e9c9QgF1jwR7KBzjXFRW7baTKa7AauAgQV9Ssp6j5zS";
export const eventQPda = "2s2FhsJNM3goMrik7Kz6gNDoPktXsK5U2wcp2rsqQmKA";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
