// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "9vJDNGRpDTYSJGT9x2VnTyA5wzegeeaf2kAuMJ8Fmu21";
export const coinVault = "CApoe6SR8QSHKeLxaGgQvx75vTsZZmTwMoF1ujPXAFnP";
export const pcVault = "AC8wLTFBVkRbUpBJ2RJXyotrWLXWAsH7GBLsDuPeGd1k";
export const coinMint = "4xoVAUDPAzoLk1pey77iLhVNo8UwWGnRzi3FrS7G5b4A";
export const pcMint = "4iVC4QHXtCv4VRuD62FhHX4K8j8SG7auAvAPfy2SAeQa";
export const bidsPda = "Avp9DUDnGxn3BxFr4V78QW9MAa3saVhZs4dH5DgZtVhk";
export const asksPda = "H9cPKF5rwR5dkUS5B2A3mcogNQT2pNV38TAtiJZsFAcs";
export const reqQPda = "7aY7e1CztzKLNVz7MsGH9bEMBkv3rZqtXYDQLNBUKvf7";
export const eventQPda = "CXXVZBcEQ48DWZwN1gZdAtMwcVTJgwsfCKR9ocNYcNNX";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
