// This file was generated by a script
export const programId = "Bk7e6ygLwT1FoMu19HRoe99BSE5yf3WATXUVzvQGj8Un";
export const marketPda = "DsfHunCEqGopxHVGfrQ7hp5gdbo8Zx6EqczCv4v2YSaF";
export const coinVault = "CoJjJbZxfwD9k49mJqaLHybitssgcPPKmixE9o4EGZvA";
export const pcVault = "7K8v5Fc9QMVXbFRxSkhD9hRJhdyK2DAa7LUM7kRyLuSM";
export const coinMint = "paVPC2A6Eh4JEg8JgZQmxfS56EMR6ckKJsRmyzsDnTF";
export const pcMint = "5iFSkPWED2AdpNNpdLSsenAkbkNYvsg8DQXGE8eb6BGA";
export const bidsPda = "9wYrszw6fRqpo77LLdAv53hgj1pfXKZ3kz3TjjobD62f";
export const asksPda = "BNHycYgu55xsUWL5FoPZ4RfFQfjojHJ5Hv6CySa9xHGu";
export const reqQPda = "56wb1YPDp1CJmrC7x6Kuw1NypQtARknZQGyVro4NkTez";
export const eventQPda = "6S8yhtEhGGUAHyYibLeEQKaC8p3nHAG32pEQMr715Bif";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
