// This file was generated by a script
export const programId = "VGwPEHBUjxa1ZQyvCAJ166TsKPYCWKafJoDeqdXqvdJ";
export const marketPda = "mgqJfni2ZZbjErR2TEAENabVQB3UbboFMCm3apN6Swz";
export const coinVault = "8zmN3WTsMPVo9Fuh99Q78Fs5QsELYBVp3nxTec1rsZZg";
export const pcVault = "H1E6PH1bFzaigu3dNtJ7s6v9Ms45G83yU8AsqCQeZ8au";
export const coinMint = "CQEpBgcqBngmeGHkmVnFsQKeqG9WW3G65jcquZnQVorU";
export const pcMint = "AvF1Yr2kp8VXUhB29jzKPuA2AYqPseAThPLbBbqTYCMb";
export const bidsPda = "CxCNZdu1mvdUEmDVySPRgoQLChZmjjPFNtMy2ERgRqRa";
export const asksPda = "HqGioaELjSnzRkzYzfVHDQtyMd1eBSNNzC5j25mDBrLJ";
export const reqQPda = "HNJrCLzHtPinDF3aRPdpLgdiQbRSD1GquQfMtisJCJbF";
export const eventQPda = "d9ivJY5sc29DeptRNPGXTy7LBe88v6CTcxTbeLoyjRa";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
