// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "42HjGj3qZHWcSn5DQEMo4nbpYWtjJSwaEeHsrsugLDVv";
export const coinVault = "EEe6C2LpAFpoVTp8MokDvpJ9KwbhNihjoeUv1xK34hXm";
export const pcVault = "GBiFMV5rk9e16ABkgNpM7z7rXE2CZyEPog4te5JoSKFU";
export const coinMint = "GjdBRaw4wy2kfLeJprLEjVrh6CRRoxLcgVzfKNMK8aV1";
export const pcMint = "Da2pBVzxUrdJCKU4N9Pap4SvVcUU13w4gKNpSUMjEj6v";
export const bidsPda = "7fZZFUkpHnJUBfTesgGFrrooiT6GzZpUfDYwu4J6Qba";
export const asksPda = "FAuYwdZfTR2yqDKZ3BpAd3XBZfBvt8xFwTJQVZuEjvTM";
export const reqQPda = "H5TgoCRFLBg4hRRbKFvbeX6YQGW9QecJWyqHdvesNv7V";
export const eventQPda = "A73CqVFtgibsUor3JCi6HDFvxvnnXBvQ3CKvvfX435qr";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
