// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "8QWRPQLSnPF7FRtapWR6zTuFufD6QHL29oQoJ77ZT7Xy";
export const coinVault = "ABaFrGe7UtvAPrKQc1WHJ1SB7jqReMDSfaxewMAfR1Ar";
export const pcVault = "C5gJdfZ77JWEJwovwXq1WzotrjURPs1TX98M9s76VMmj";
export const coinMint = "AhrgLPcPmAJzAYkPAmugp4vRgWk6R9hAjReawHpTBoMp";
export const pcMint = "DJ6XD1tPUYkGFATqdSZgzND2nwHCoTKK5v5VaKGVvKQQ";
export const bidsPda = "EsAseUvbUhvERuSHRCZFq8CuuHaJSMsTLUAhLhq9gsxm";
export const asksPda = "BhKQJ7JZcbsW76CD75P6d1PCH5QHnpCsuMS9UoeCu3n2";
export const reqQPda = "tPBe9RPpg2FPkN3Tniipc3QrX8UJq8n4E7EKs3mdpgk";
export const eventQPda = "AzN18woLxBeYHdQU5ow2tzTkhxhaJMCJEiohWEh3nh5N";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
