// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "8Ln9KqE9sxL8ggSKaTHtEPcFkxw7AZaxXr7Sid8KEDiz";
export const coinVault = "EkDKqinBawHkjCm3yGdrWfeU9F5egiKBzDUHyLpMLRpj";
export const pcVault = "7X2n3AvMDPWgW5P6ev3baLTunZ3LSgBfBso78RvcGvAM";
export const coinMint = "4DAu1z6RPUihTuuVLKvKJuK7QToztYumD44jfdBjGgRR";
export const pcMint = "CsPLLun284xQdAoCGtNubNvGMseN6BNEPUYCzK99bx6X";
export const bidsPda = "9kmFp24KuaRgjt4Jt2DxXecq4NSN4UpwaxtofLiVsTJP";
export const asksPda = "E3ZSUqyfyTJQXY9W18G6ZqbPMHDSqYpHweExLcwoRRQH";
export const reqQPda = "9j8zvWoAemtp7tYB2Nty96nwVCr1y3B75TFskwdB4i2f";
export const eventQPda = "7CYKn3X6ZJ1btkwyHvtCHiJenpAUE1iD1XfanZpWy1zY";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
