// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "HGPNxJDHFmrL9SYLuH8e17eFJLZronAzmeoXhjYe3tos";
export const coinVault = "ChqgFxrcQzWbZRCsHu5JddvACtiScehVQE9qrgNsUkR6";
export const pcVault = "42NWhPhrECwnGfz7g9yfDSJmtjhEcmXnQSc1hD87BX1v";
export const coinMint = "gLZJt3qU7uWZohrLJSj4UMpEaYGPVh13QPSq924nkUQ";
export const pcMint = "3JvCSvmwxWWfzW413LNvV5AJCiiC4vVMJqAcTycoYyxx";
export const bidsPda = "8Uzr5bWjqgMS37TnPFHdM4E2DSQTF5Thkq5h7yqc96Fp";
export const asksPda = "FkzgoZmaRE6nVtcm6QyW3rN1uu1eV78YuCCc4aMp1Sp5";
export const reqQPda = "AhmkM833pKhJfEJvSS2Bd27wA7w42iSXjktquHnueyKU";
export const eventQPda = "HFoPtVKJJTkwdujddWx42ocuGicJ8Wp1qot75m9tb35K";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
