// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "GZoP9UoVgzZdS2yqXj38LSPPyzZecUCBiNnk1aQq2eaW";
export const coinVault = "6VBs5pfHB8E2X8XXqLsZfHzHuj1GUuk6Nfpom3dhyAy4";
export const pcVault = "4CQtoxEXFyjVbtwjTrqmyUTMiQLSGcKVAFHv87izR5n7";
export const coinMint = "DP8X6mod5iamo5bC1s5Lzf8Ei6QnS4naTxfAGy4V2VXk";
export const pcMint = "7BXwBfyHz46R3SVWGUiQoDUTexsucPeVGEqNC17WdjLk";
export const bidsPda = "ETeBRRgZTCmJYhxXhZP2pgk5EhEVWVx7gHHPSxXgNPAL";
export const asksPda = "GdrQ7MFPbfBC3vWVFJ1v17i3DqTkvGMQDigqXkyzfRCB";
export const reqQPda = "CFT3oDdks2GzgXnR6dgEeQcyHxTcvFoijD34QxH9eEt7";
export const eventQPda = "GfjfHUPvBWeCQUCrBzaB9aZC6UPALMvfsbJ26f7DXTjS";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
