// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "AqPvSGuFRYspb6tBi25kMW3qSQ5pW4A5zr5ParuPYdHY";
export const coinVault = "Dd7iS4P1FbC55CMMWkyMahcWaGySnu69WAATtTgyTpUz";
export const pcVault = "i2toqsL2XWAngehB5ghYv342qCHojd8GKVdT9nc1WXV";
export const coinMint = "F4pDpVoXCw5vSrdYNpthv3Utrz6FpvP27Pe1cLj2ivJF";
export const pcMint = "7Y98Sh5eLgVj5EFevb6oTZMQiqyWTQRN1XTPK31evxtT";
export const bidsPda = "5KmWgVp63nXyCyeyGsDEUhwcFaLtZheLmoeKTqPLwyKC";
export const asksPda = "E4JU4X8CoVBxtzYChSV2DBf7JpY8ykAS6eBehUTv7yN2";
export const reqQPda = "2j3R8GWmcFYSFvq6RQui5WtkwvYqoG7yehkNRyXWZ7CF";
export const eventQPda = "3m3YJYXiCBwCp7HpoPwDQSwXGz32PDy4j8Bbb5pC7F31";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
