// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "DNq4ZN7xAV3uaK3Fjwc6mF1piCgrZeZCM3GWwReTznQu";
export const coinVault = "C2oRALwbLCEqzWJQonazH4c5XZT6Pf41QVREchfLvzCB";
export const pcVault = "38RJjdAatvd2PwyiX9wMd3gSwHnnrjMFqBm3iYnAcZTT";
export const coinMint = "FFkpf4wGpU8W2sDoXjLunBkZbjTcbvhz4mofyGqg7Z9H";
export const pcMint = "MxN3aLaygbWkMLNV5ZyhmMwWnbW5rxSDs2NijSJNY9C";
export const bidsPda = "4jjGnA3cc383RgvbKgL3LDQYBuzahijUuRNHoTtb9wB9";
export const asksPda = "2Dun4aiLAivS7ufqdkYrFJibUYp6haKpxhfZJiHDxyAY";
export const reqQPda = "HxXxmgSAvbCouoB8twfCgoeg7A64j8SJot8cTLaw5N9V";
export const eventQPda = "3RfKT7uJbfjeZavqqBrJ57HkipbHMhkgazqZLhzf6v6W";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
