// This file was generated by a script
export const programId = "GJsyZs9cr8agF6SLiLfxiS9A11Avioe3JVPie92N4SNw";
export const marketPda = "4rtQLZFY5DZ6UR6fWYZ9h5fHJn1LjHunPcRzFMLLTCug";
export const coinVault = "45iE4AkL4rkgRrLpLCBDXTqRKcaaTw7gBhXu23t6SdCw";
export const pcVault = "8U1BmDhAh3UnzcwWw4Eg1VbraQt8MTSrcfdZrHfs5rQw";
export const coinMint = "75X3JgrvbRYHVdvTdmKRfwFHSbqfqU2RGH4y8X7i8eaM";
export const pcMint = "CUarkCd6YBeLCj8Naveeo39ejg7AreTLgDrjepkPCpL3";
export const bidsPda = "H7F14j9oj9d6oNVKUMTjo9KhGFUywsHbvG8dXs1RHaMJ";
export const asksPda = "2gv87fGd4WQgkhehsJskCBuZexof5cenQks6ULVhcev9";
export const reqQPda = "GW4kr7ewinsX8TRYcRZZ8mxPkwQQ2xHyxqg3xttvjuvS";
export const eventQPda = "DT3BsqTYaFcNmt4uamu4L5We6LgjjjXQQtw5DLe48JcN";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
