// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "xw2hFq5sQpMcHL3TwESYeyDusy2iKBPafGx1sR3swic";
export const coinVault = "2kcu6WoMsWUpqAbFNdo7vWqcRP4sCqcHoWMKcfbhZAei";
export const pcVault = "899hyqdpMdRAj152MXRRS1STGJdAWTSqy8CHCjN942U";
export const coinMint = "C3w6Rh6Y4z3XJRuj9Nw8hmqXJy9r44seKTmZmNZn984H";
export const pcMint = "3EeZqg3TZ6iBMKw5kLbHpQ56DZQBByiS5Znzz7aAyvAH";
export const bidsPda = "7xeyhycT6m1XnWUu2CavHsmPPmuWMZ7b4doMoobXo6V4";
export const asksPda = "3hgpz9MEePkpcSAvotmjD3DqW2WqBAvisEjoPbFwg3W9";
export const reqQPda = "FLSSasbZnCfrjocMBPBdzh1Hp1SWF7tS1ZstVfiRwC1q";
export const eventQPda = "GfjTMfDWBnDU6iCwBSk7nwZgwKGz5xUvLuDMGZXKQK3Y";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
