// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "DW4hLZwmvNsir4ASnA7n3KZp1J6e24SmkU6VymTx2mYu";
export const coinVault = "4FBC7oXStCUJZzLp8D4MUtVNdTsbd6cnj81d2ZXcqFnz";
export const pcVault = "6ATxQ6qzcLFXaW3F6T5u5NbqS3wshwPSgzHavrZzpM2a";
export const coinMint = "3JoqMxiBKae3k9ujVoyXUD9gHaMgX7Rop9keqcCHkVbk";
export const pcMint = "HwRaSye6iBWeZZUNFLUz6iD3WdfhPFVnNLj9uUzemor4";
export const bidsPda = "C9dewH6W9DrZEc4cAtBfwkjboyZs49Y1k6EyYuw8Ns7o";
export const asksPda = "5ktHQXUPn2geHKNfNPLmPDUFkinkXwUW3v7MEch26pXc";
export const reqQPda = "9RbrMwGqpe6sfRa5kMHGcsCwQAxVgZmSAjBUJd8ZJ33U";
export const eventQPda = "BBcMQhZaqd8KpEW1hBxgVeXVuL2ZdMnBTcWuLfEpSDwA";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
