// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "1NxAtKnTKzeXY38J92BH3dC4LP4idYm6vsFb8xqz36D";
export const coinVault = "HFVDSdbpjFyvND3sdbYo7hRkAodzgAyfHwmVbRK3zbez";
export const pcVault = "6eq3g1Luo9kY75XkLZyUWRELsCAcaQDEJ3sr8kxjGXfZ";
export const coinMint = "9b2UKt9a76fqiU8sZiV6wBrRqrHjGN83kjcBQaE6ekA1";
export const pcMint = "9afaCAUqSz9vXETPw9AcoNMwQ92L5Fbzjhc8Bdesnem1";
export const bidsPda = "34cBsvkQkjFL96VKAcv2yHXVve9CCT7knYk46RTBkUrY";
export const asksPda = "Br3m6wR2Xs6xT1Zo6YVRtR5GFVQsYQQkPJzzGDnRmaoh";
export const reqQPda = "2QPE8sFRugCAbJVrTrLcNAcYLfhHvf32KULutWPVM8HS";
export const eventQPda = "3Rx5tguHGWYHhyDqo3oXfWajoPuMjCqN1jmuhiGfkfEN";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
