// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "BWJme2dnxzSP1AQ71qZNC1VVsk9C91khqxJeYw5sxheJ";
export const coinVault = "CgsEK1Gwr9Ei9zsTk6wPnDxJ7tuqUd3Goyyfd13MYwFb";
export const pcVault = "3qV5Mv1CWmgfb6KbBCwsHgYZ2qhtKjuWYZrMchw6To5h";
export const coinMint = "78CVktRAco8q6GFq19dHnAAggsZYk2Sm2odsYPXfryLU";
export const pcMint = "Dt4inNyUfX4ZVsntbrcUScBUaqYSvh9FkkAJdSeoCahi";
export const bidsPda = "2kkypxmLt1bAXWPMWbEkCqDyxRFEdMc8kHXVfo26iPxS";
export const asksPda = "439275Pwi8XjvuSpaHifRVdtQNMmDyqk3S3ckLzeSdwG";
export const reqQPda = "Fhqf5eBCNp5vamade9opehEiromVFyu2mSjhgRfSuXE8";
export const eventQPda = "5g5ntBzUsBsvK6RUxTVgDVVjY2FBUkgVoPmhapBGuhjN";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
