// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "GqsaaazSYy1PY4DxDGcUDJynttkNhCwhLYe7E2dthvPc";
export const coinVault = "4u9VP2uPjHz82GAhjrsDVD91n3spG9NnLgrHWH6sQY3P";
export const pcVault = "76RPidrJESJzU4L4JRwNyCV137ka8MpQqv8g5xcpLm3p";
export const coinMint = "6rQ7x9GumERWUAmJhLDhXYiBAznwMN3VuRhcZhX5SctZ";
export const pcMint = "BDwhDF949J6K7KdiA4qPyUurPrvZhpnUJcXcaRmqtCTU";
export const bidsPda = "5n4dLii5JZkn95Q2SyBaw2Q9h8c9iwkH4g6PDKbrWFPM";
export const asksPda = "6iheyGPrC4p4CU3TBVpBSXVAACTyGysa8As3iGdpmNWh";
export const reqQPda = "6bBmo9GdVZYnasznqhzndz8m9XBDo7UKa6Hgo5AKg5kk";
export const eventQPda = "6ZkjqJwAQ547eQroP4gWwgKwKbDLUnEEwrWz1yxHPgZ";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
