// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "HkzUBcQn7iUPAemVt2aWA486UcrYjmtZkNbYHHmnmZKQ";
export const coinVault = "9WYsa7eovXnhiWwBKkstUn5782eyJ1Uw3uRNHZT6eYKq";
export const pcVault = "GrTQ9h5jk83WNAVQGLff8R58ZazTFvEhAvuRfWegmJJX";
export const coinMint = "CV3BuuGx2wyegvA9dCBQzZcDxhb5Vj7xY8qXVMEUYsXS";
export const pcMint = "5WgfzF2J8uSwpiaExmziHt515pQm4nYEgtE179GmhxFW";
export const bidsPda = "H8nSZp21szj1qcu3rX6JwR9cYxRED6qG742rbydnrvmX";
export const asksPda = "B74JCoHVvtMmxWFeLB7xdUeXdRG8NNQo9nDRFnHQ41SY";
export const reqQPda = "AXBKi3rq6ARn8hij24t7UEZ3KBMF8u8TP1XpyZHnDB5C";
export const eventQPda = "8uuJ2Z1yZrBXvntwt8YekUApFT2oodUm8AU6ysrU8zU6";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
