// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "51xWVL7Krtyoq7Tc9ctsp6jvc2yLaRcNmzsoKXLoa4aq";
export const coinVault = "35xYHyCLmmW7ALXjwAYHaG2SSH3PBWK33yhyoQbN8QEi";
export const pcVault = "DdJWNQ1uh17grxGsukKAesqJQNhjHXjifNhGU5E4vApN";
export const coinMint = "CeJkofwPtneBNE5UXN63B6uekZCVvYDbZRpL12DMS8Ge";
export const pcMint = "Fvp5jZ6nkjQuuAJoMEUdLwWuWmyVanz3iDMvh37Xitdh";
export const bidsPda = "9nSAiq3qqvAtwpVswxW8fnqUNUrGPDvYsScfoDY9UZ4p";
export const asksPda = "667ngWwfQKj2zkMfkDz6ePfUZ4WqAF5dVjqm5vhW4fgZ";
export const reqQPda = "A1uWG8NgCyEP8nZQmvhYxVZgSAL1SdT4Xgvh4ZgZ9X54";
export const eventQPda = "391aojsXWcb57UuQ1roFn6vTdrKaLFcPsxtBfMCdCJ3P";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
