// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "Hcr59f8c8pzAmZBSdqWbyQbGGwvAQRPffDT86kondBof";
export const coinVault = "7JZWseCJZmez3Wcmkum9ArCDTqpnLxPcRfyx9GcEvZgj";
export const pcVault = "BCsejE4MQxRAo481YRgoyXxtoXZYi7DNQTkKPWu1GJdK";
export const coinMint = "AcQ66RGXkr3Y4yiwRFRjjmdH6aDDHdAq6FMZWxjo39w1";
export const pcMint = "C3BJK1i3Rw9TBXq9aFc2e1c21Awapxvo9hyakwm3Dd23";
export const bidsPda = "GxGTBQxnPjnGAt1xiA9fJRNnft8qiMrnDtYTYrvdescd";
export const asksPda = "GSya7de1f9aVexs8dBiXBZwSgWLXkemfJBYBDf5Ez9Gv";
export const reqQPda = "24deMmcoTYMN495czpz5MucuA4sfFS8i246trFpZTLGg";
export const eventQPda = "GkJ3WyZoePo1TNwaZCWebEJqyLkekxciiZZsbiFwmHbi";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
