// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "6PVEAc9yusEGZfU1w6LADuSMAaGbiSvZWwLE7y7EfMb5";
export const coinVault = "GG9DZYzYmnxP72xH8tFu3hqC9ssipjCckah1bPSTYbFN";
export const pcVault = "7ocJXuZzdCVJ8p8L4dSSLowAJyYfCbE9D2UodzpAwPqj";
export const coinMint = "8y5bkc2pebEYgLHyU1kZ1XqQoqX9VS2Sy8pvCU96DHnM";
export const pcMint = "nykpeoaGNeQ8UnhZemCc2U4fWqWT1TrxPZKs2foDfqV";
export const bidsPda = "CgTCdyFipbUapUvKMMeZDo9oePZKLJEia2tmX5o4WM7g";
export const asksPda = "8YBT2xLYZYeS71MbGfiAJVRSsmP6uFFfBtGsR4xaqPPy";
export const reqQPda = "8Paje3bxEAQWABBYKzo6X4WMVvWBAXUAzGgi7Sjvb7dr";
export const eventQPda = "XuHnPZGnHqKK4KYD9r3EkdxHfrkxUUiKMzoSsAd9Xxg";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
