// This file was generated by a script
export const programId = "VGwPEHBUjxa1ZQyvCAJ166TsKPYCWKafJoDeqdXqvdJ";
export const marketPda = "7XbHmAgaBfmpXEWpiZxvTUGUXrjiAn9o7TLtdaX7a8z4";
export const coinVault = "D2sYXoAwuuHb85c8emhJB9vJpLYahdmEXsQnNEZjgoyM";
export const pcVault = "D1MPyR2vmSCnkC9gfmN5U1FFBmKdGGe3Mhbm9BRn5Q2w";
export const coinMint = "3WTR5hNpXFQMn1rqmhcy4mQJTXnWQZbdoEgYGFQG299T";
export const pcMint = "AJSazwSmGSMWRtE7BwyQoSqjjcCefreZfJ5T3Tkvb6Ev";
export const bidsPda = "Fy1ei71sghJZHAQ8gG5e4L2oPGuCuY9hFRJNHFkzAt7B";
export const asksPda = "8p6Kv6cZHsURZgtudttBgiHQBqx6jnALJFoV2SE6N2NV";
export const reqQPda = "DpkhRNeRpuLqgDCZikKpD3zztDoHxwz57JqDqEpKsXbP";
export const eventQPda = "2t25qB1LTGZgZQPv1w524KodYMCrkGTFLnmGsuF7ezBZ";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
