// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "CUwzu2r5aMBtkjTjx9ijpBmcy4PY6KVCiJCrW3nSMJr5";
export const coinVault = "HHT6mSSKZUzReXakzbJvEegzRRVuR1HiV1PhTnYoiwZr";
export const pcVault = "H3k4NJDDT51X1z8dQ7ieHM4QULCLysAb83y8TULSrAVN";
export const coinMint = "9pRog3UcQ2QbSZPk9ZCzosnmbiUr3K4JsZ6ufqK92R6x";
export const pcMint = "4g3TfebddetrCTcdoRxDWMXSDpwtXSJVWcnW1gzEkpC2";
export const bidsPda = "241jfvsex1PVwWb4gAZos3ZT8AtffPdZabfpSMK5DeKy";
export const asksPda = "9Umw3xAE7caokAERU7DstaBgv7M4REcmw9pvekzVMJG6";
export const reqQPda = "FdfLXfqP7LdQMH5PnmzizTkmYYgxcGrWoCkB6diiHCng";
export const eventQPda = "8fbiBsixiKu3nN5Yeeo7btt8AaPxZhTVWmfqQ7gr1gfM";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
