// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "EVvNk6FXMirS79MPucRtskABuVho4hurhe19tiMuTMPf";
export const coinVault = "CXGBEbVfmgUWE7EBHu9QqX1EHxU2mfCzarZjuvkRz3W9";
export const pcVault = "64PYX39SzyHvcRfzoC2pqRymcC3pMB9Xu3sTPjeMLkHr";
export const coinMint = "3wN6oMdqrWiGumHsNebre8abHEvAjHp93Uyo25S7d61G";
export const pcMint = "CyeqUU4J13To4NGydNmXRBj9ocm4HmK8MMpXwKE3PW4o";
export const bidsPda = "Dhz1vN2So7vTfL74rihpTKPGmBbcYJyhVCz4EtVr7Cka";
export const asksPda = "A8oewENKfFeS9Mm3DqojGAxYh1qEmLYJtZymSXvQxW9C";
export const reqQPda = "CVEspPrfr64khYgsH8P4FVnQTkmeAxVuLA2P31KMid89";
export const eventQPda = "5yKcWmmL9jHwbVVD5uyW977JEYFx96GBD7MJw2M8g5Lt";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
