// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "5DeesP4Q6mJzVXNxQc469BMDtFd5fyuUZTx2bW3as89L";
export const coinVault = "65qDCGWYYepfhmm2HXzWaPKw3LX6YDRwm86ABaDAdsHb";
export const pcVault = "6zX6qwBixaXooSWeZzgGw87iYquW1yJ1P5Wr98UFmAZC";
export const coinMint = "EXQcfDgZgfJCCk5rwSmMYWVspL8TfhyTg8KtZFoGHq3L";
export const pcMint = "EMabsP5fE7SHRcQjRC5Kn2896AKiA56JmSjPsb1owJwp";
export const bidsPda = "4PJmsRWqw3KQc2TUpCde5VvJuPdkZGzW1yYDPyKjjmw5";
export const asksPda = "4iScMDitSxzX6eCAcgSbgo6jXMdRWd2FxwVypV3fENXr";
export const reqQPda = "C7bospgRuA1KqskDL71ybzh6YS5qFHuzQpGKVJVYqVAx";
export const eventQPda = "DjcgDvMqZkz5CweN89tFQy2vFSZfLKVFU7MrsEDeroxP";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
