// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "HCkK9ksVoFkMDdV9BvzyGLMNeNC3CaUXfcUe5UtdhwPX";
export const coinVault = "Fxuig6Rcm3muy2y1DURuDDha9a1Lg9KmuHaPzRtivZpE";
export const pcVault = "HV36URzCrEVu1cpmYz4usuZ4WExdUkgGynYBV8T3FM9q";
export const coinMint = "tiyoZEMi8sPN4vr8Bv4fuqXo3PzUDdeRipNztLCyK1e";
export const pcMint = "2gKzKxNhXQdGgAsEmagiktz3LD92pjhX2U3LnTXpgx9A";
export const bidsPda = "GhTHa5bMtTgDPuTsCu4aUaF7FmbN6UpHt4c5F9BLnhsg";
export const asksPda = "2dxBbdJHsxD3ZvpyiZe2FHdzES7nRh95CUNGjUpTZ3CP";
export const reqQPda = "49u6zGKXFb2E242iYf6KL6X3WsTTbTYFCpB3125f2P4c";
export const eventQPda = "2M8dPbLszzBCyfSSFGh7YzRiTZDsMLS7zEDvNiYqZ1uP";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
