// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "ztJCRcT7wabQNo6Jq2PDc6wkvBaa3DfTCpspf4wHZpF";
export const coinVault = "83ye88KvVDRi7e3UNByGevazqZDwCdzFZxRtuVLJEjoR";
export const pcVault = "GzuYfuAku6NXNFkUTGKCv9oTie88awJ9LMTRCf2FnKwb";
export const coinMint = "57pAzLWUhJdm8behZAHQ3gE2oyp1dnifPoGUD5ZSpZed";
export const pcMint = "7YghvHre1Ead6y2o5TcwrGRDcX5DT5vHt3mZswN2hYTB";
export const bidsPda = "74vcAZjJUyfCAPvK7ApGL1itzRHgyPvAXbhEjQmhbeEX";
export const asksPda = "H2KDmY3jNcUcKHk3Ln2bPcfREqhCdKem6fAkt59CTx9z";
export const reqQPda = "DarF9cpLtc5jwvLShysWf6VrEFckY1eVpqS9Aqw187Rm";
export const eventQPda = "Exd6LQQ8uo3z2G9G9SrBdzubAvXHYjEdwfa7wTUfUqxE";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
