// This file was generated by a script
export const programId = "GJsyZs9cr8agF6SLiLfxiS9A11Avioe3JVPie92N4SNw";
export const marketPda = "EyYxgxDdNaygmMoHhDS8xMJrATFfLYjNaxWxBYu5PQZV";
export const coinVault = "H3j64NdBnp7rMoGPnZGKG13gE1ZnBEBZw355zLs43sUa";
export const pcVault = "4iUmiBGVRCXRRqjVwDKsrk8aJVASWZeHVCc9Uq19MEHW";
export const coinMint = "5KWsXVvG9QkYLU9id1oyopjLmK1E5GaPz2SMoqwH2TXe";
export const pcMint = "4kCUZzJo8wPWKsCMupzeKn2Z6nv75x35XzCTmkaPgJsG";
export const bidsPda = "2oqQ1A6wE3y2WcZNU6ePtuwG1bwH8msHSd2hSxEBUzbA";
export const asksPda = "97JaWi9hssB739gg4nmM1XGZVNTQZjdGJAAthgACqSQz";
export const reqQPda = "DTCqJLH6BujeMd4CArpR7rfUyh8C7YAGK8dN287SCmQ2";
export const eventQPda = "9PM6QPTQnSqRegTYTZ9kpXTKY91Wh4vbtmZKGnGFNqxt";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
