// This file was generated by a script
export const programId = "3Ek56WB263s9WH7bhGtjpNkFk8V2UDXmvsKxDJ9RzmGR";
export const marketPda = "HMJkR7B9WanGgxGhLiRGTfrmfFps2qij9GbYomW6AECL";
export const coinVault = "B7picTbXBmz16LQNuKbrEXWqtFpj6bx3kdxyXfPmdhkj";
export const pcVault = "FEkFVMNYjNpZxKMBskfh2FC5XUEkwhbwpzqAm3cbymE4";
export const coinMint = "B2kGqYcP4qY4yLqoEa8b29pStNCQKb187tN34D24tFb8";
export const pcMint = "3TEdfhrTbyCWDpCgKt7bTNuxXonGa3y5pmje4hsQCXhC";
export const bidsPda = "B84x51V6t4YnmJujFwy9VQAuFPjDJR9yAKmmofWoNkxm";
export const asksPda = "3NDDCVZghMy3T9CaZVbzsov1ZjpTBnu9KA4vgT1V9JJm";
export const reqQPda = "Hu1U1wpvepak3pQTQjyJq7gRHc5cXwUjrYsakqD5pgKW";
export const eventQPda = "3L7uoSE1XAPSXARysjiDRwtugnw9L4imtmAsbCW1FvpK";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
