// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "kS6efr8wLSDwbpuFmAb7axHGRZeA77E2kam1tQE2CdG";
export const coinVault = "FCJmgeepFbAm5oRHFdTTyM6zYsRiZ2omP77M5CSoRLPx";
export const pcVault = "DZivdtLQZ3jmHoQuxdx1Tgqr3tKz7xDV6LS7iZuTe3cT";
export const coinMint = "BLs7jW1iFv5qGHvq2BUpVJbxRM327Xfqi6Rx76QU96Bm";
export const pcMint = "8jGbrhe2CfHGg8fcVSJoXKHSKRKUqFd6cCh9VMHxrdhk";
export const bidsPda = "8V5QtAKuU2hBx8iovqBBpLc76CKvp9R5kkVqfTpjCFbf";
export const asksPda = "HEhhsuJD5Gqc7W4x8Qs6JcyuauZHHmAGJF3hPvUnzGeU";
export const reqQPda = "7auCdgu6VFp8Q6j2NTJNtnTyJbTeqLLwT855a9RaLVEH";
export const eventQPda = "78WcuST3aQjJTUpHoKr6ReffBR8wZqGz8jrS5PEwEhfs";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
