// This file was generated by a script
    export const programId = ASrtYDNReHLYmv9F72WVJ94v21cJNa2WKo3f2tGoAH7C;
export const market = Hh7LgdXZvCh8TmEPgE2ogvvZeHESfRRJv57Z3zQzLvHw;
export const coinVault = G3mJaKuDfomRCHCqAddj7mhMj5xsYyWDvFBedMpjygUa;
export const pcVault = GMoFLzthFtV1gzbCnPL5x9VLQrBYa3Vs4bx8f6hiPNh8;
export const coinMint = E6gnJrV7FBaidsTr7xuYf95LR4mhSuhMWzPNKop8f86r;
export const pcMint = D9M8oqvSPvXtWQTvhnf3LwBT4XoqnkVVPygzoLNjo3xR;
export const bids = GttxFuuJvgehURKDAw6ySQo8H3gyUVoex5uQK6H7aUu7;
export const asks = 6bvUrA2snSkLFmUSTWG5ApJiwVVE65xMq6YQ2WWYRsni;
export const reqQ = HZhczomQoixYoTWfKV3JRDdp3NqTVMjU8Xpq1ULWhzXB;
export const eventQ = DCdG6Lun8aEkSnLS9EnCbPkFZnwtXksVVHi88CUBsDGJ;
export const authority = DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W;
    