// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "GemPBPMMUukHzzWmtxQz2XK6ieEBXkA44bFWtwAvVmhi";
export const coinVault = "2TVeHVYsASxMjiW6dpUegpZUJFqTcUa3MkhNaxBvKGA7";
export const pcVault = "CuQsMzHKuAc28Yfk8YdtowZpjDuztGhQDiCzioX1JQpT";
export const coinMint = "FhGFzVJP2nFCAu483MZqMfae63Y77ctug9V7uftBLRKx";
export const pcMint = "4eou4Lq2bCeycMsAC39iyPDpyGnP4A4Affhw4o6hmnNj";
export const bidsPda = "Ag5MftPSwBDtem9846cPHzm9kpW7hQxGkQMfTcHUoyru";
export const asksPda = "6iBKyg1KJk63VsjTN3mtCbD167qJ3TpoJQV9VFJMm3na";
export const reqQPda = "6voNMXPg98Gxu6Mm3JkRT1z4sDqyCSL44as15aBbsPrY";
export const eventQPda = "7is9NFZnjkkyFeXbvGsy7QPtJXyZyo7nyaGFi52bMo4m";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
