// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "v6TV4JMAsjLJwTjLFzNY7YuLgWjgeQ3aAdjg48cXYru";
export const coinVault = "6NjnTWjftoo2EDTQ9xtLnkX9rQoA4aWgsXy4LGDw9DzE";
export const pcVault = "4tELsKrn3tDFVVZwZUdsEs2ahHWhr4Rs3Lv5EPSkx3XN";
export const coinMint = "3yfMuFAy5iRXLufRhsToZvP9p8RrVGGiRCBtSecSoqir";
export const pcMint = "GJTZujJMkFs5FER2pJXfPfQuuGBuD3QCYZDwKXZyxkPD";
export const bidsPda = "EWXgSeB94qMGj3Q2a2tSBy8ryMNAoGWRzeKLsETY25Xb";
export const asksPda = "FKD8cXuTPsQwaxtDrA9gRauWbx4uovo6p8QRzJiJ2Tfe";
export const reqQPda = "5d3PwyuYwvZnoJhJgCV4nC9FDES9f1De5ahQhwyoZE14";
export const eventQPda = "2uWNfjiLYScaSBxCggMsXNy3HUCwuxagemyEvk4MqbsA";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
