// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "ANRuovjD1fbhn7D2a6cqCkFcdUxth5uBvWxR74s553Vs";
export const coinVault = "9zNi9NYKSqU4rdrSqMhodyDuM1BJeoUrmywUrUzi76H";
export const pcVault = "FjTwHH17bkpKyWec8c91V51vAhBVBsEDdJN4h4dXYN7p";
export const coinMint = "BC2kNhdYX4FW1bh9A86ScgerZACEDzGc6jEk2oJM8GTx";
export const pcMint = "7iwxfpgDHYhLqN161JQM4b5cA4wwMR6BrHAn6UoMNAf8";
export const bidsPda = "9ZK9Pvfv8Dvxv8Mt1Fj4WotiBdLyEswAmrdJJcFXeQ2T";
export const asksPda = "7dBS4Uj9kCnW5bXoCVzHR2af74ewJumW1dZEM5tEqdzi";
export const reqQPda = "2NWZMUPziBpbvGLTXDZ2nJiozkTGMRuGK6WM5akdCeZe";
export const eventQPda = "EJVhbsRLdWfSTczFqqQTBEBHPXjhxDw3VWhmMCgHaXjM";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
