// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "CzU9Qh7SuYymyasw4JrpfKRPMQ4NZTZRsJFcMXkfEj7k";
export const coinVault = "HNiga3xXVUPZsY3qJfvnoWRXuFaa17ZvhUh1jRRBAWEU";
export const pcVault = "4HyGqhtoneZRLmDp2oNvtiaY8x5TDKJY98q9VXtoD8GE";
export const coinMint = "DEeVmG8PuH7gwfuUjZkspzis5eyaBoRfkCJfn2zE4Djk";
export const pcMint = "6DgadwsvfheDvjrVdkF8WH7WyyafRLa1nUYUfmEBdi3t";
export const bidsPda = "956xh6aMwXTkH4dwdq9LEixK4qj8GujuR5vkDZt7eztL";
export const asksPda = "EWaFaDDs23bv7PaGQqVVQf1fTsQwk7cxFJAydMcd3oe5";
export const reqQPda = "27GPyXkghfz43ftJ48qnviwENsyu8MXcDca7NemmCMhs";
export const eventQPda = "9ggBCiwedqrUHsNTpzdzxrL9Z1quvsrUFtckAw81qvTP";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
