// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "2DEq5zVKG82rp6TDUXR2TAHKXPBULaRfork2cDo7PyzN";
export const coinVault = "3noLYs9FwzgmsQBJGgwFjj9qxJ4paWHPMBaucmKcJvoR";
export const pcVault = "BaWpWKULSHvhiqBuZoZcZSga9e8adsvnakkLKnGwAhKJ";
export const coinMint = "ENP5NuzUnN7M4bSr3tKoB9ky44dTxdFpTyVFBm9pxXfJ";
export const pcMint = "5jB9o7FC1TU4Fuy9FU6Lxr2p26MXVmyPZ6589P9qpJ4g";
export const bidsPda = "5Ra8YNxJB6PBMBQ8mRFurh1CTEAEAuinRw4PeB344kGL";
export const asksPda = "G3nUxcSzDg36b5yEcbV5c8hNC2ZaPckdUtudLQDj27PB";
export const reqQPda = "2KMA7rgZEWyjnFfGJaCtpQixHpQNyd3sqeNNdGb4uKto";
export const eventQPda = "41osuiXDELRqNboLGJTL1pUmsJg3wnpHNs8AkLNrjqyu";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
