// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "GaebYvWi5fftXrEod1JCHGhPwnHFMrD22DmfmVAHP2HD";
export const coinVault = "HWHKpbNrmcbmBbtGp73hA96X9WChGnCVn6GbJ4jqkwZi";
export const pcVault = "8nmPxHvCG6Vhu6e4s8CnhjMom5Rarcjan4RwTpA1uwxb";
export const coinMint = "FYURj1SxbaZqxsnoiG8Wr1mChFXSj1RBrKKt5vyYuquq";
export const pcMint = "9gMfdiiD6XPqVTxBQSFbqsgzNugH6fd4tjksHvhR7Tvd";
export const bidsPda = "7wR2eQhtvvwX2Ch6ys46MQTt22usF6pJvnFTKoa74bdC";
export const asksPda = "4iiebvHnjBtMXatVkwAQQ42F27DhdbS8Z2ad2HPEmDZK";
export const reqQPda = "FYq7D7Y8ZnRHjenryGnDSMFbz5id1yjL9yDM1TiqBRQL";
export const eventQPda = "B4gsCwCFL7SXneKTPvaR66sqr6r17hL2S6MrEdNQ2viH";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
