// This file was generated by a script
export const programId = "VGwPEHBUjxa1ZQyvCAJ166TsKPYCWKafJoDeqdXqvdJ";
export const marketPda = "BzZAfaa3osTEZUJtNdhXRUqC5vXZWTYPDCy9CPdTpQ7u";
export const coinVault = "EXTKeLgwRYNM5KBvCAYdjqEv4DpyJ4kaxAGTy8MJD7No";
export const pcVault = "GLmtPww3YNQfDBCrQVFfJe4B8sGTFXoCQ9Xoy18D5WFa";
export const coinMint = "Dw6tb1TCRoQSoabKQUAQFqwdWrE1GVdA7bAkGWdP1nsC";
export const pcMint = "4hntCp4gD3vjjHSrHiw5Ffto7YH74uufsjLCFv4tQFQd";
export const bidsPda = "31XrSHxcU1acajzvwjn1GbQ1RnzuHqHLxLiKpKwsiwDY";
export const asksPda = "4RXkPpjFaLHasv7PD18iaUVGRXH2hHRczXa6nukR8mpL";
export const reqQPda = "DjTmDRBMb9Nqyxudf6WjYWcvvAGQcV3RsHybNg3T6W2c";
export const eventQPda = "DvsEvmnsXA3PJAo62KUyoGRPLRvNeCvWd5bKzqm9vGBa";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
