// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "9gf3rnpi4fXVM3eCggJoFEEPUgTQgCWmDz18CJoj2S4M";
export const coinVault = "D2wffSFFAeRVYaabWvreR1LpUnvDAJ641B8yYWynq6Hq";
export const pcVault = "3uNseBcX4oX6nXxFNV9XN9EtHQP7eKHrZEnMzTmFPA7b";
export const coinMint = "2yGMx864EHVpz5AWJYRVTrpktnfYX8ex9ABEwV4Q9ANZ";
export const pcMint = "GLwfiadoUdbyUbAwVS7saeqH2RzienwPddFJ8qrJaGfK";
export const bidsPda = "FKA5d5tmFSxHn7DJwSCgGMW2E5CqeB1ErQA1HYsbnZQF";
export const asksPda = "8XQRxiLsGkGVwxL8uJpz7JU53Ambq3qzLYB6riJnAfRp";
export const reqQPda = "G5HaL6wiawtvuSPdbs9jKC1HTqT12VK9f2THDcWdmHfX";
export const eventQPda = "5D3siRjNW41XjpepeSbSw1HTPdrMJtT9orYuCK5UaR1V";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
