// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "EBeRpzVpft5nsWnU4F7nrw4kZN9GZUDWwd9acUH9JbRa";
export const coinVault = "F4RexUcfSWx58z6QpviNYPs67NQmc3qDuTaedG2tVtRK";
export const pcVault = "2uk1seA7FXVJMkAJ4KoCE3xNinPFWvt31jfcrxyVe3eZ";
export const coinMint = "CcWeVRyj1ExamAC6M3yY3TXiyb1XU99vMx7XgFjKqsyE";
export const pcMint = "GBDnhGZeSgErXn4pUWEP4DfcgvKhtR7cyUD2UezwVxSB";
export const bidsPda = "2GTfUFGKyDCm6A7xF1PikCvZUkL3QdX1kCzxjoDSzAFk";
export const asksPda = "FiVAxWghkZZ2kHNUrYvb8HfY5ps3qJFnM36muZYtmeWS";
export const reqQPda = "13JcMuySZcuZ8b2jbGhdEYkHqk5eGdmaoQjyfpcqmzK9";
export const eventQPda = "FVREbKaC79ioV9Bx1vjWRNx8vsUmVUoaGpv5NxSeqpHe";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
