// This file was generated by a script
export const programId = "VGwPEHBUjxa1ZQyvCAJ166TsKPYCWKafJoDeqdXqvdJ";
export const marketPda = "AHuCRTDxHZ1NJ3QYXfqBtwMGmWTT6ywSXJtoaMW52yUW";
export const coinVault = "7VxRBuYkXwhkkfR5i6KQhjYwe1S9d4EYYj1qKp6n42eV";
export const pcVault = "ASQr1kqRU5qBhXUhC56Y7gK9tbne5GSeuwGCVf47jwoP";
export const coinMint = "HK5zhq6L5E4NTw2yWo2EvpjqP6CrLUXkaegvsfpJwLPL";
export const pcMint = "64JS2FLVYHahQEd7Hsaq9JkHuTaVqqjNxaTq7nmtfYj1";
export const bidsPda = "BrFF9tX25ToKjLqzj7WHNE5eBeRzeq4F8XAAQYTCZhkL";
export const asksPda = "2Jz9LgrML93qk2UaR7mG7Xn5V5AH5P7BgagoMKpefsEd";
export const reqQPda = "gPF7y9dMEyDoSn1tDZiSsn85ATfTdwKMBfBv4hXgPPc";
export const eventQPda = "DVy2mvnE5moW2wgRBxYgKUo5EaebUSa9xaBDHK8wTbTe";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
