// This file was generated by a script
export const programId = "3Ek56WB263s9WH7bhGtjpNkFk8V2UDXmvsKxDJ9RzmGR";
export const marketPda = "3fR3N2cQPiHu8vEdd3CLRGFKXJsUorhQkrk5gRdGD2aY";
export const coinVault = "D5jM2PVeCvfuEA2poKznBrGeLGEg4bnPu7fEzpi5K75K";
export const pcVault = "HvXcP2sY3RG2j4kXadveJaFcxPmvbPmZNhQTQ87JarRy";
export const coinMint = "6khQcqiSR2VU5SLhZKwqQRJqc2jKXiB9ecBL1pLHetn2";
export const pcMint = "6Nb2NqmLYPWzjiuMiNh4vT3usG9K5Ln6eXWSibXePdBA";
export const bidsPda = "3nUobm7tpwtiQ4VVTZfNJ6P1Z2bRLok7kkTocCeevoTx";
export const asksPda = "AZYKHguhRKYHC9X6E1p4PWDPkqmdTDPzAngMQxbLt3s4";
export const reqQPda = "H5vqmvDxs4FLJS2xgfcwvWxofgCZyzDm2oXAJyjtcqva";
export const eventQPda = "GNYrU2muLNTvrB4m6GXtvpXsuHtjixPFWnDd7J52ovQU";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
