// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "F1uFSBgFcPk2Eai1GGT4PzxMpPzLbuW69ZyfHkodaWMH";
export const coinVault = "9jGbHCSQHHVBBqVTZf7o4wnfRi5oC3G6FXYAqA9kb7j8";
export const pcVault = "4kaRBsPuio8XJMkg55Wo5DL6kbSNqfKSqr3aUftrWJWy";
export const coinMint = "J5Kb8vv9nsHZPfFHa1gKDkeHDprfq5E4MwxmBoeTh9gN";
export const pcMint = "5SL9C98tvgGmSottwoCdKiXhrjVe2BtvREuWQXrnkCnY";
export const bidsPda = "6cPAZKek44b1NEdzLBQPNpoV7pgJJvzdRs1bVr8ZZNZm";
export const asksPda = "F25MwP4r1JPNnBYAzg91MNbP6b81rm6XzpeQ74GhYJKR";
export const reqQPda = "7JgzZy4aPKBQ6Y6sNpq4b6CWdjLRnyygL93MQY45CtqA";
export const eventQPda = "6Hf4AcegFeZJMdG1miEXjRZgmXxE8rsKgPquE52vgiSo";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
