// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "KvnxQNGbueAfQRUZMVkdxpuKvNWBFWd2gy3S4HUCYYS";
export const coinVault = "9Qvx7QBGRBGxs18e2Us7i4ZEDnucJWdG4TtnrBS6gKeM";
export const pcVault = "D3qqViGHzrik8WNkK6uyBJd9KkiWXXMiv4f3qJL1FbeX";
export const coinMint = "GQ3ucEbqCzxgE7RkmnbkPaEvQkcXrvWAMCeRsqhZTpVU";
export const pcMint = "FBqAa9ET5cDKEgQbQjFTgNFg6jLJGDcwCTbf3EaEBjuc";
export const bidsPda = "B9amSstr4F5VsH96KRKv3sfr3x1gS8Db96YTZRBNwxvX";
export const asksPda = "5VqnDXdSVYBavbiia5EDedVsAYUGRCzKf1q39VDFt4uM";
export const reqQPda = "1J1r45ccL2tcWovTLPrKog5nTGxceRWXvECoXfba8vw";
export const eventQPda = "7taAKE8863ncmZoo5dLb482azL2ociAbqc2WLoCfKMpB";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
