// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "6231Rq7V49oZobuZA2kUZ9quSs7nEFHRsXmuAm78bFLB";
export const coinVault = "J4UUG467RzWW8W6xodLr4hW7NLqv3sJJ9pAqgHhZPwHJ";
export const pcVault = "8S3Z3h6J67EHJtgTdW8XJWNDdsP2GWEztUWtB4j9Hsz8";
export const coinMint = "HWiNGJjC8eaQ4HEiSdy4NQMi9KQ2948w3kh1EAr1cp9m";
export const pcMint = "2RSKD7212hsRaZDPoJvkQMtutpJFzd6nXGSoSroMntkr";
export const bidsPda = "HQ54dVwP1VGKXgzb5je2soDwJ3K7V4ckqr4fXs7jAV8W";
export const asksPda = "2cM4bVmcAJAKrwdkzEVLgHFTg9cEHtUZiN7Hg2XHK8MK";
export const reqQPda = "DYsjetFztvVebogZL5sqGo9JGMizufqSakjdnJ4GC65C";
export const eventQPda = "3fn7eobUMKnzV987uQNdUCpANZYrDkCo7vMtJWB2sDz7";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
