// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "9kA7GF8ukeVMz6ZJDRKMctpKMSbbvwWqrxeZfDBumEHG";
export const coinVault = "3jnLguRHTWNafGPxfdmNpgZjVpcEkLMSsB1fqSs9DYKk";
export const pcVault = "5Yg6iys4VigkwaSZW8kgiYiHmb6dcZCygoiHvA71au9A";
export const coinMint = "EecCbky4tWG3GqRW8zaY9kqnSBV7b4Ui4F9p1baZYitS";
export const pcMint = "Y7BxdEGdsixhpbqecUko4LumW4S27D5dxde67vgzwrF";
export const bidsPda = "EtD8DozQWNBHwzrx2VnxtTTZqNz1sRzutgLtPh6YQJyp";
export const asksPda = "ARSf7J9X7mzxzWmBffsuV1kXvH6jRQXp94LrrCiWWGf";
export const reqQPda = "HrnazhFmzCM3YQRSPrKEEtQzxYanGFDYe2Exjdhs8uju";
export const eventQPda = "BSxCNLPgvxXMM3Si3iNfvvQUpyJhYCVWJTtr3eDuxjRJ";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
