// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "92JKn28mQUXoNqFYk2A234dXG7XxGSX4WYejfXTYwB2d";
export const coinVault = "7LhaU5yM3QWUECpvMoPKfBUxaxVtj6z1zUAXiYBz5ssf";
export const pcVault = "AnQ7pou1LnpqjgdxQR7z9fYvR3Taa59hrZ4VMtySWYM2";
export const coinMint = "FiJUythBJyjUGpg9Xvr8fUDZA8zpWz15GtgsqGaiXn53";
export const pcMint = "8mrtsFwLLeP2jjvStVdvPaxZuC5WWYBQziaayXQnerAc";
export const bidsPda = "FVJsK7MfJCsVqqsW826W4FcD6a5VRnD8ZsyV9Pq3noN3";
export const asksPda = "856ArvdGy6rjWA3CY4BDAmRfqicPaBUpaJ2oaomKnjnP";
export const reqQPda = "4avGdxNNDynJMDmxUw8Jsha5YXBobpi97hGn72gyJPjA";
export const eventQPda = "ELkXiz7EKzrM5QipTa4Y1DaJVKD3Z3fLzXTk2i9y2URX";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
