// This file was generated by a script
export const programId = "Bk7e6ygLwT1FoMu19HRoe99BSE5yf3WATXUVzvQGj8Un";
export const marketPda = "F8c4GGuLkUZYwf17BvaKHMhDJ5sC6mm2TJNQqsAb2PJp";
export const coinVault = "4YJ31JbFGNPvmqqnnFTC1dzHiyLuhtJTQHxPFFxHmNfd";
export const pcVault = "Augucfgq56jDXLC13L6UWXhvF4qkHFE1LsqykERdPcao";
export const coinMint = "9ykkbJSeCMHXjhC9ZVStcyY4TeDVWdz3PCw9TsLMaGFH";
export const pcMint = "8kQQsgK1sErtRNTjRP5hNjLUMBbsE8ujxSYCDfSwRTnG";
export const bidsPda = "9HXjAWuz1HbrhBKEmN26kf5SvCzoTNfXQYCWy1P6XaXU";
export const asksPda = "J5dZNzW3G2WzAVTaSBXHWEFvfakERnymSCruAffKNZpt";
export const reqQPda = "5acd45PHQwLk3ryvbgRd2tEDcu2KADLwg8qkxD1WzaAB";
export const eventQPda = "7WMonQtVC4VBcan1aYae4PRYQRGTW8jGuZDBoTjH8fNt";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
