// This file was generated by a script
export const programId = "VGwPEHBUjxa1ZQyvCAJ166TsKPYCWKafJoDeqdXqvdJ";
export const marketPda = "B2mW77iYrrVA2sr9SrK53Ntv9MFqC9E9SDoUugqL4Sos";
export const coinVault = "5c5drwoyAzfKMvVRPmRsy96uu7oBxjdQ6KwddVmhg67A";
export const pcVault = "FFbnmiPwHDVtVX8D5jd3n3ibsu4daYgGidsM6CF24PyN";
export const coinMint = "X3yjdsoafkJ9sUrBwMaWGxHwRBHtWPYvQikq9nu4X2Z";
export const pcMint = "DxQZvJecpAYzEer4q4doKyqj1hvp17hbvH2xugh83FB9";
export const bidsPda = "6urmWy2bBR8CpyMVr2q7kWTdkq4K1QK1ZUXfvcosBJeS";
export const asksPda = "3ysTJRR8n7dP5unvVmy3VqGTJNsmqApzSkvr37NamkFP";
export const reqQPda = "FdE2U4iwiVfrAmRAD3SiyUSRGBK7G6Qh3XwbjDhYydU9";
export const eventQPda = "3EJSmsmjTo2WNNZ69RvvprGFhFQwS6jAJsKqnHj3Z7ga";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
