// This file was generated by a script
export const programId = "Aodrp8JRS1tCywT97x5ytaoJYczv44JYtyBHDJGLCx5m";
export const marketPda = "3HA3AccjaqJwUXXoce8gFaygB3qeRBxJPY6ZBizDov5N";
export const coinVault = "3B7wpHZpbDH9LWcyFZUx5MXih7L7MayU6R3qQzCjgkA4";
export const pcVault = "HZZ528zCqLo3wUosrKaukoLw6xzZoHW9HS8qNZUk5UuY";
export const coinMint = "CzG9JiUcFmJJD8V6Sw3uRpLmUikmN6wEDAVVRnpSM4us";
export const pcMint = "vqu4L1sRMiAP5tC7wfdB3d4f22aLswPiVVjCv6uex6v";
export const bidsPda = "62WVu5BK2CYuyNFf4636bNNUMEtYp8QmAdWBF5YaNWuv";
export const asksPda = "fhwZvttLgUCxBfDdcUr7ArBhq7w4Wk458ouHKu6D4GC";
export const reqQPda = "6EqmqH4y4cHY3U7a896zFbMDs55nNDzacB5svpaMfW76";
export const eventQPda = "DsFAfgVFbrpAfcTA185dnYRXV6yQAMSwdNT7zVFighK4";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
