// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "9jf2o48SjXrrfxohf8rCwrWqy3w1E8uR8Ccmi2A3LoqP";
export const coinVault = "H2aC9zPg48GTrczkMrzT5XkwHJDJown3v2pWcBniev57";
export const pcVault = "DescVWhsssRUSBzezT1EoYcvqFFHYwimBZtAmTgdrGJo";
export const coinMint = "8MQerNRfBNKz4kfje3xZ7ssNRYRZ15S3JGiAMusxnD4U";
export const pcMint = "HtR9sVyLAh2AzkQ3Xw6Hp2o4Wmkv23uBM7Ede96Godxj";
export const bidsPda = "9Wjpj9RJ31PUrarhuMnki48Z2xN4nFR5kVfQrtkPQ8MS";
export const asksPda = "Hvg3Y14bVMdzRceqrKNXqp4SPnvPfATfrvfGX8ZDARzD";
export const reqQPda = "6MbW1U3asbmzL7KBxZdaz5JBHfaopeNfLzU2GoFxrwMa";
export const eventQPda = "8PMuPJvZtDJjRkmHV5onyWrji6VFrvWdv7KAP2DXXYqg";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
