// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "GjAYgJRbTB8jURT6QXfAjsMYt3wKTwGGuXDDcneQ9Hmo";
export const coinVault = "BXEje3LrZ7S6Eie2X6bbw1JddFW8hVtJ1j8EKyPbLL5h";
export const pcVault = "7ty5miHngYQY7BHjCqC7SQMBkzeQpqYcmwLmtJtJKAGo";
export const coinMint = "YdLTXT72Mi7be99ewUUnzkZZGVkiiuQYp6pp5xbTUme";
export const pcMint = "9HGoN19cW62AFH74RdypznA3HgYZeKWkJjEJehKn9P5Y";
export const bidsPda = "H71w3XgY27DC5oLDBGaeYQwzYZGTp5CjhH9sPYNFiB8K";
export const asksPda = "HwvwL9bSMYPTw8BZQr5WP1WPy9XeNiBeLjLNWGcqQP2F";
export const reqQPda = "AXekymPEcD3BGZthbbW9GPUrMEZm9tWnycCTzZxYZNa4";
export const eventQPda = "7b9hZ64t9apKVngNgGZut4pN3RBoGVRnpTNcGi1u18Pr";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
