// This file was generated by a script
export const programId = "GJsyZs9cr8agF6SLiLfxiS9A11Avioe3JVPie92N4SNw";
export const marketPda = "2MaA1HRkuhBB5wmjkkprpU2PxFWqi7qJ2AoHzHHurGRT";
export const coinVault = "Cfki3Fr1ErGMNDGmu5cJcNg5dAwEBPbSnQUyNLLzWUZT";
export const pcVault = "DUNAj9vMGXedkBJuhUFVM1UCzxQ42rvKp5Gs9kcFZSv6";
export const coinMint = "D7xHLv74q6YASatKZQj34mJ44zEX3paZQE7qoj98sdZa";
export const pcMint = "xA87tM3KEC7rXqHcnTbUiDYv2S1ZVjfEs9t1oD4xbSA";
export const bidsPda = "J6Fwtd488rsaH9jShanQ6YvJJqfwc77FTufG98UoRrBw";
export const asksPda = "8swf32oXJboF3FXyp23E6AJ1mFVztdutk7kPXf9QtLJw";
export const reqQPda = "25AwDJBGyAwx8EkKyaFYMfA9bTwgahpgxDwcwP15og8d";
export const eventQPda = "2ySVfxcxcrraS3xg1vG6wnxNFwPPixvScjamLfF9KY3v";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
