// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "AELSXe5o39AcAYb3nEJXshECDTBzRKwGjMNDAeBSNSXb";
export const coinVault = "B5Nknme8pWQ6wJDMxrGT9u9KeKy5KSmwUYMFAXHXpXgf";
export const pcVault = "7qXY99FqfgjQYpvjrGwCiSn3oohKGyRrGMVP1DifQasa";
export const coinMint = "5dd3TA6Zkw9ymuui4f5rKSNfB6YKwnaUFGzuL6P92nNb";
export const pcMint = "9ze7fBPxD8ksTD8ACqZXmdBhhg5kDd9dDacsQMBRZK7A";
export const bidsPda = "AJnxy7XDy9T78vtio66LmeMwvh29QFvTNwQWesBw3uD4";
export const asksPda = "14GzuX5eHa4vgDdAfNLqk1GHeHMEimjn3TVghTtZhxzF";
export const reqQPda = "136UZRnXU7LeTYeYfayeRTdv91v5eqWPkv1S8a6tALES";
export const eventQPda = "9oGNATJUPwwKjTh2chorxaNapM64mVis6YPUSLRDmF19";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
