// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "8Hueq5KkwogRvd5A6Z1GBKMhxCnfnRYBrJEmUfsb93Yw";
export const coinVault = "8X9ADcr9UuBEtxtnV7ZZ6GxZMsV8z9YmTCJt8RqASv9X";
export const pcVault = "5acsRKqWsYw8RtWF8ng1fLiAUaJ9pGJYSqNLALF3ExXh";
export const coinMint = "2fDaRpr5jn49tiQHfM2e5UXgXCaEgTDqV3B2tJeyVJR4";
export const pcMint = "ARJCTS76yS3Ks7mqjorCkUtMXrJnmchBF3XJuauwgVVF";
export const bidsPda = "HE4nDRdQbRhuXHXVaWd9fTVg3WRrAEDasJsijS6DAqfg";
export const asksPda = "2v3uG9qVfctXCbTsqkJA2yZu8ygtSFpeUueoWMGawCKB";
export const reqQPda = "GCrjJ7wV96CvP68npZhoVJxAiqsifEtAkR2wtsiR5yLY";
export const eventQPda = "HufsXhxLauB26rDvGSSmEyPFbSPaA5xo9cbXxHcwiz3u";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
