// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "HyrhxeeoA6oxEHUkYaHs6BuVdGkvEFXaDin5eJ4SknQ2";
export const coinVault = "Va2oAY8AReJzXrfVvJH75B14PiopjL6uzCfLrcPRZmP";
export const pcVault = "3DCbuRfY37FMbRhTsUjqhPzqiAECMQNZRjv7UDPu8acP";
export const coinMint = "5JQ2EuibKY3cJxKB98cSWPAYbDiCo4ahYEQUunQmrjSb";
export const pcMint = "H17P4JwXHHXFcLEotc3hX3MN5MLLUdSWsgMMAbCSx8cG";
export const bidsPda = "H8rJdotMmrdyXiJxi5G2UZ5uZu2aZFbt9Hd8tr7zwUcW";
export const asksPda = "3gmCDgbXZBixurDKvYeKvAPqGH59625LDyp7Acp2x4ei";
export const reqQPda = "EyiUMcYCeYcw5YCTTcs6RZyzA83P83DZe5zWPs9EaL2a";
export const eventQPda = "3nNjG4A5W76RVrfbspBxUKjWsvw8Ckrdr1mNkKS2B1h6";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
