// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "7Dq1etyzAt8mamZXkSbdYodeLcF62UmS1ZFXmHRwmWCY";
export const coinVault = "9BhNyvY5C51ZfRdNXyzSidFy8KmYf3tVYLc7GgU8cEKx";
export const pcVault = "71pNLiZag7pCQmQUu9cEc4cCiDN8kuiCkMv25dZRN4WM";
export const coinMint = "Hrixixk7QkpQ8wRqyRZ91K7QfeA5U1dtAoenhVypY3dy";
export const pcMint = "6iURW7znW941G9VCsxG9rmzLw5KpuhNCkot5RfJWRm7x";
export const bidsPda = "7NuCUfucbqGfMyrzCVTTVbM6HyPf7JPbeR8ytXTk9UKc";
export const asksPda = "DEyT1fZRiWfE41HbNCpzxdN3it8dFiqdC7XH77GKa9hh";
export const reqQPda = "8y9ujXJWGntdki8nocLaofk2wHPvg2x1g71BmNdTPfnN";
export const eventQPda = "4NfMZs8tFdv9UH62docFi9dNRNQ7rMdc7uWhHsRuagZE";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
