// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "D4K3VMnyghTZt5nyEvjLL6N7CmoZ2pr4SRMKBNrTm6kg";
export const coinVault = "5VabJKSMGvjb2iv5z1rV1hFBEB9NqQhgNGYoBDiXF8a8";
export const pcVault = "B7w4Whqwy1vbbmKq2AVn4aMSfB58RJDE7nr42Qrj6Wbn";
export const coinMint = "7tMA1WPKjEFaJX9UUcEafra64igweNChb67hpeg2Mb91";
export const pcMint = "EWMfLeeLv2fHx622ehFF7hEetnsz2j1c2gFF6kZV5NHb";
export const bidsPda = "AtKvSpf1qP5Lv1r4XKeUnBtgUYzr3K7D8eoo1MzhUr8W";
export const asksPda = "K4DrHktrm15YHbKPfqFyP5wabR9ZNwTxTLPMQxmydVK";
export const reqQPda = "4pd4XxfpAXK2Muz8xZa8CaWqXzDeNjBa5pHLN8wBV4CU";
export const eventQPda = "HG2wKX1WbJyafXaTr8zP6qEEa9P2LgBoR2m9CtEGW2pB";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
