// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "C7BhXsACZFM8FHhA1qbyjivkMruTN28HS48UPChfV6YH";
export const coinVault = "6tgTcmavdPP1zQ46nRKQ2ism771d5CqEtergFtLofc7J";
export const pcVault = "5znyXc9zJ8FAFTbE7Nuy2LiGgXyYNgk7QCnVwkJS1MbF";
export const coinMint = "CM6rzf3ue3VQ99yiXfWdszc61HwMdfRfP8343dcAo5RW";
export const pcMint = "CuBVg7nZYJaE5PxYrfc9ot5un4a86nWpmu4XdWgeXHCQ";
export const bidsPda = "FjcbgGzPtV7PbeEGQMM57og8ov6ctmJ8Ma7QsnaQaq67";
export const asksPda = "5QjAzzkkYmKLE58Qmz4AfPVhnB2pYwir81HRPrs79H37";
export const reqQPda = "6Pjfpue3yJhh7ZAka6FYaDe6JreL6m7JnwCSJbHLM2mS";
export const eventQPda = "C1b4v72yXthcpqs6C8J3WptdRYKJKzDPc9w6C6cT2sta";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
