// This file was generated by a script
export const programId = "GJsyZs9cr8agF6SLiLfxiS9A11Avioe3JVPie92N4SNw";
export const marketPda = "DtxpzLDZcwwGNSrgwBgGq3yV3Q4wfGoo8YipJ243R2B1";
export const coinVault = "66FhipYYrb2F5AfcPQvVR9QS1Bswv17KH88tGmFvZXWh";
export const pcVault = "2vKwHNRwRL6C98udaBEj1qf4D5ajjV2WQcP1mrSciimB";
export const coinMint = "zrHjYfV1uUZaYKhFvZVNzYA8SNoKHhscPNw3QRqYPvP";
export const pcMint = "FUxHKSYpC6J6CeFin8zxoaMVy83Wv93gfGnmmFGSaJv2";
export const bidsPda = "DPo2ozbFwmZc8HenUHcnXW8dcpP4zdQHirYKQmotxYnF";
export const asksPda = "Hxq7o34qZ2SXS8G2dhGzeUNHwEoUPkZiayGk1h2UhdfU";
export const reqQPda = "9JtBUxcy9Tau8mdpPrfnGDtTiRS2vdwix4se4Q5ZRyXv";
export const eventQPda = "JDJetZB7GqKJgw86B4otRrGf41GYn1HcDPreRgzK7qgu";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
