// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "nKWERdAy9UviFciXEJb7ZmPaQWp6D6sKSkHM3a8p8hS";
export const coinVault = "DLg98n4HUAeF1b47JR1ytBLR2A2Mai1gJhT8jeJuvnVR";
export const pcVault = "CLrKULYgUJC6q6JWFhg32VMkvSBQeaPe6chuNWGb7U18";
export const coinMint = "6YG4DiTSHtuoPKPvzmQsUnr4k6BVzqyGKjAv2z5bXCkk";
export const pcMint = "9dUrjMpZ9nHQDDoEaua3wkP7WDv6ExgrGrLUPqJHNQsS";
export const bidsPda = "AfUBSbCaX7mBxEfogDAkjsMXbuZhWPgca9fHQ7UrhMbJ";
export const asksPda = "8aKtWAGJznBnZQWGVXYQihFodHVJV7KsFPFnGy11yJV5";
export const reqQPda = "2pxCTubcvcekdy4V5JfQtF7sZ4q9xCH2YLBS4T1NS5fu";
export const eventQPda = "8byu3seHQumcyM3LsoVeVrjbizYyBT9mvCms9HrMByeS";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
