// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "48cNnv1iQs5CXCsKXBNSPCyj2SXTjz2YM9hpnCUmA3m3";
export const coinVault = "8Nxjsy3V3y7d1kpiFB3yh6EwocBzFwvthmfS7gMzAa1Z";
export const pcVault = "AHtRzjzsPCh8FhzFZKYD4LjDrDmuRwJarqVg49DtxHT4";
export const coinMint = "68K3KJqGBQdU4JimV1DEJyygjq9eMymvedSRWDzJpHZn";
export const pcMint = "BGDpMmhvnw7FxYRN7r1WrSDCoaZB1fm2vNmWmHAZXn7b";
export const bidsPda = "6MM7gPXWzhu2HgFJMs3drHLCxmWsy6VGfYh43W2ycnG2";
export const asksPda = "J8nV374dGdyZpXgzVoXki8NMJmWC9Wq7zHhBS494nAby";
export const reqQPda = "DPcKzPJe1ui4XMDUbk9RyeEkpZWqkeMmnuV5DwFsNVVA";
export const eventQPda = "Er8k9ohv4BnWdABwF3EetWWUkkMF1oQujc2eh6WrkBFD";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
