// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "6MVpio8VdRZinHiKAKYTMubNtQRLEXvTnggsGXfdh3iP";
export const coinVault = "DaA6zadsKqCmX9qAstffQEBq7jToL85sDFKyxUgUUyAA";
export const pcVault = "7oLMdZG2vQq9NY2U6MS6WKAJ79SgfDmRVnLBwRdgS8NE";
export const coinMint = "EgLTp9z4dCFVfnMYQmwnvk3qN8DdfGk2Ti1K8HD1aVBE";
export const pcMint = "GhJos18L8fwvun6KWgwWy1v2vNtDJMqEUpugTfdYCXpF";
export const bidsPda = "45GVJE1rwf8nDjH4CUEQQ7oZwFAr7MiP8t9VaBEtBCac";
export const asksPda = "CpaRSnWtA7G96wGLkVJZxWqvef7H5XsCY7416mVat9p5";
export const reqQPda = "DwbLviHu2xinkqL3Q1xAN1P2aJw4c9Yog76jWyCeGiQ";
export const eventQPda = "3CHUK1M9b3Axi2TMnLqTLw9igtaiA6F9StRixGYR73mp";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
