// This file was generated by a script
    export const programId = ASrtYDNReHLYmv9F72WVJ94v21cJNa2WKo3f2tGoAH7C;
export const market = yHFhsjXmNNFzVxJ2gTZmbQMPLWffpFVfMqQULBWykJ9;
export const coinVault = FNzHDngr5d5kWxN1eTKsrgUmEr5kPNzdAFqWYR8PaA9W;
export const pcVault = HV14JvCqNmcQAVPCHfxc9d41iXBVgHaS5d48DKJV2TfF;
export const coinMint = 8xS89aE8rHwk8AWfqWNqEufz76ryZdCwdtqzfFVvzZQV;
export const pcMint = GbchRvd93pAogDmBD7NhEJ3PLWe8UPSzR5h9sY1NXbZL;
export const bids = 28iHqjoVXezZciA9GjJii5DiA3r5dzqriLyCYBuF1EnG;
export const asks = GKvPbjhsEHvzSmv3jqLMYZC7W3WcUxZhx5L4qEnK3XWW;
export const reqQ = Fhg5FFkhESPrXZPzeps61iVezLkVKEUFGJr2uAhwYd9;
export const eventQ = 9RLaLvzvrmZkDTqKUNXGRV3PEbNKwVmuiAFSdGQ3J9yC;
export const authority = DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W;
    