// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "9nH25KmSpKaFDqpRVg26uirVkhFBrr8A8deEMn8disP5";
export const coinVault = "3AChtyUgLFCYcUjx28TgTZfFNRA2BsLTy13KcwBVxTe8";
export const pcVault = "BQiVdTYxhBfTBGCdrNUKvPPpUBASHuoQ3f4fUBzkeazB";
export const coinMint = "vv3gEeSxCRsphRu5ToqGuvyZZbnn8XMXwhRWCPjiLDb";
export const pcMint = "DdNAbo1kka8hsW6Q9F8AUUeLaqXWvMgzjRobNpkEPEW1";
export const bidsPda = "GrxY4zaBe9mVdMUyUHizu6mg3NDcvtUARhm9cdRxhCEQ";
export const asksPda = "6CwSeZK7tkJ3y4iHroUYXazD4uxcFg47Zawfns8cHunS";
export const reqQPda = "ByUTYpng4h6DFWJNxmH2UPDKCiMpGBar9jagLMCZVwNv";
export const eventQPda = "C26XAxXSRZ54EdkMuHXkAUQoxGv3QivJuTbi3kPsr86e";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
