// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "8bUhQyrivcjgNAgi3vTChFkQFXBamtcPpbyJbpzJzd32";
export const coinVault = "2eGb1RmkkSLbKLRG1naoRpXpvbsnBSurZn3E2pJnKxaS";
export const pcVault = "6qoqQcG4xowZqqB3AvP4pRxnuGGVwWNCkKG8MGCSpuzu";
export const coinMint = "8EscMxaDE2s2mnvh4Q4xia1mnzYJaoXhAJknrB7qj9pu";
export const pcMint = "4V6mhhCkWbuf54NNjVg5JJQRFBTgxxVEud41UHPWmMjg";
export const bidsPda = "DfsVWm1MA2QXjbAu4yr1wurqSBGRzv6H2AX67cF3VYef";
export const asksPda = "CHd3DKig46wj6NWFBwyT8NgL7f41CoAnCVDitxr51igp";
export const reqQPda = "C4YbfV7E3m11ZFQZeAHnsGsR52MZWLXaQKim9zjigq3r";
export const eventQPda = "2bdcmoCHyPi25LWTnP8A8WZndgnfseyy1rEtL55njZrC";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
