// This file was generated by a script
export const programId = "VGwPEHBUjxa1ZQyvCAJ166TsKPYCWKafJoDeqdXqvdJ";
export const marketPda = "98GNgSHoVJSQbZahKEKNfS2A7q9tJyybDXfNmPLtHN5s";
export const coinVault = "CroUmBbJcem8quL7bEvUJUxDHNbQQteVuALGQePb8qx8";
export const pcVault = "ATmkspY7GxZt5NugDKVc1sG19XBzUqNxTGdAjFhwnuDB";
export const coinMint = "Hvsx8kHTVxoc9tLgtkFyRtPGaMKL2wa7DpSKUG3rqgGi";
export const pcMint = "21aehVwV645TNUfhnQJ75FVjUh5SqfrXuZ9FWJtpWins";
export const bidsPda = "Gsqg3x352Vy6LkEJtYbkchY2SKdWgPB1jUC7HkaHm3R";
export const asksPda = "9YMsJKjZDVbQGFVnJC1EFWLnzskePCbR2BLoiNuRx2vH";
export const reqQPda = "6DN4DcTdiaWP4qwwMrrUY6p6EzWevUSHRjRGaYtdEGuY";
export const eventQPda = "4oCWWGcGyVp1eFXQqhS66huECVZdubAtBoEGCzMoVZWk";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
