// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "EbRPm8s6B39hEuMuT8x7qnBnL9FcNjpCEiwQyjkUZoxn";
export const coinVault = "9PjwM1gDENyCPWYYQ2weUWMM1gL2cVqmJaSwPxubemWQ";
export const pcVault = "5TNJLprTJyN1Nk6sS7SdTG5NGVVwGFxEtSC4MZ4Jvm69";
export const coinMint = "5BPd9cBeehhRNP3ymeqSZWRYUL9YfgeeTWSXCpc6rBHD";
export const pcMint = "3TJMKaUcAJQFbq9mJcu6kZPSnfXXa3KgcJ2yJp4hkd3D";
export const bidsPda = "9F71is32BC9TNSpd6eZ4wgQ7kCqekHmXost1NHpa1Unh";
export const asksPda = "3e7e8kVYSSgDx2TCWK9YFb6bw2WqiDWbs6JgqizPATR4";
export const reqQPda = "C64M7C1DG8BtvGJj3jdzLy797J7rGExC4TbFLMqZqjUi";
export const eventQPda = "FD5agva2iUu7LuH2uDvKT8eFPBz8XNMVyqYZyvsntm2W";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
