// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "ByDNdw59pzA8K6v9eLBRVR9f6X4AfUSCZRNQ3WF2PuZc";
export const coinVault = "Fykp6TJXwPz2tGdNqLWs65yrqs8Bx6TM1kg4GfXx8Tck";
export const pcVault = "9zzWruiZ9vo163iucRCFRFyTBEKjdRQh2agX78AKLc3W";
export const coinMint = "HNThFC9XhDxSLhBnm6wdkwuYaZ6Kg5W22J7UWVvWp9tJ";
export const pcMint = "BXyRtAqJMcxxdSNKEeveuX6qnmSkLaPsf4khaXsiw3nN";
export const bidsPda = "HCvR9KDhG9B4PAwBbA9hYGe61Y5qwbqMuogR4tBSiZhu";
export const asksPda = "C7JnFJZccMNnCfrfZ3GDTVZjexht38deL368mmz98ow5";
export const reqQPda = "BdEWK6Kbur8dUu5VbWoHiMciaeLik1mnPRCmCqGCcb8h";
export const eventQPda = "DNMA8xXKyLuQEMoNjLvFU8Y5bFdXqGs3rsLLkuR492Md";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
