// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "J3oFhKzpksiPrTXRLX8SY9d5ytmBKZm3ZPHJXBQ3HFRL";
export const coinVault = "AhH1TceRtWMvU7ZbEQebfaNdeuogMoHTD5jpL8exZv3n";
export const pcVault = "2rNQQFT11fx7xWxaxqdFpuXiDVaxs984P72nANLjdaQL";
export const coinMint = "814Rp6eiLbJkfPw1sXPxQXJ1Hr1C9UiQegJtFe1b9uDF";
export const pcMint = "CjktLHtHiZCq6WnjRTbxYQdXu5iRk3NYjj1HXT4YbwEu";
export const bidsPda = "GgYAdZQfXmouswbuxZg3LqRSoXFMs1yCpoTZQz3P9A1C";
export const asksPda = "7f4gWfpaWtD32EsD5vytwYtpV3GGNEZz46mJMEeooX9e";
export const reqQPda = "4AzwrayFgMmSq9aKvS3nzjZse8iENjQwJ3cjcKvSKAB7";
export const eventQPda = "EP5jptfrT7NnbPciW5dCpS2fz5dSQuQUDroDiDGYgPsG";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
