// This file was generated by a script
export const programId = "GJsyZs9cr8agF6SLiLfxiS9A11Avioe3JVPie92N4SNw";
export const marketPda = "4HGuzZEtXgC6M1qfMSoQWZeN2dNBGzfbmQjPfvxJfqed";
export const coinVault = "522oswhMnfG68Z8jn4eptY6VgXKhhcnYZQgYMhQuj2iw";
export const pcVault = "J1ERUdH1wyj1ZkevaXstZUFyzzBHvd6gMq9nje9oUsLR";
export const coinMint = "BUDcwxTkztaqP1FxpqHg8ik2M3N2PDbpc9nHXYTGg9qu";
export const pcMint = "Gfdegnf23ZPjHwqPMCf36JuCpxSrwUwhrh22wT7njHXa";
export const bidsPda = "5tegTiPzBxZ8FE5FSDrUQj2UZZFd9gWzc3Fr1P63ZsUz";
export const asksPda = "ERH2un6dNM4KXdsrLSMT9r6F4UPP6MLA3G4hrw4FrojX";
export const reqQPda = "CiFz547sALpyqoiqjb57baorWfiazyTZvcPHzruWW7pF";
export const eventQPda = "JrDMtLyrdYaQvsFJ8C5ToUNpruLuPMnR9jUu3DA8GuF";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
