// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "Fc65V1EwbQArVxrVX7qvUYwWcxoMhUtfqXsZpQ8EQVTY";
export const coinVault = "4qtoGQgaqTEhgMH3nw5nfvYXGETNXVCn2ckUfcguqWiJ";
export const pcVault = "6V4LM7QPwnsqzSi7oKdP543ywoztdwCAX3hr7x96k3HR";
export const coinMint = "E2ST3VbFRNLCPXzZu5imxQ6GrBeS9QqQUtR5jjmxaov";
export const pcMint = "3GXMmn9gS1erpeC86r7wDaT3Ncm39NtR2EgNdYFJs2YH";
export const bidsPda = "A3v7LRVFnRNn5BbAQwEi1xde7XKPiLcS1XN2fWpGLgwi";
export const asksPda = "ALXGZTpmnTSzjrRHxwEHE52GVL7QYRJYcvbRi6T6eGZk";
export const reqQPda = "7pS2W1oGpt2gdNSHriynjQVicXJefyihphZjfy6vogQ3";
export const eventQPda = "8d3e55RxqfANbyTypfognRyewap5NzqmGLKKe461aNgj";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
