// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "BNECEevAg76nyz8jQehcASqLgjfTwgshwSG5cphcNhaD";
export const coinVault = "AxyWamKxgzGhB7nh6nQmdrYLir4WPNNU1N6szbb6Gqox";
export const pcVault = "JzQSyTbSy4XQhrDgVhLrgSfQcvE7dozbeN3wkGQSoBN";
export const coinMint = "GXGaKuuLnNXtQDrW6JozfuKYs4upsccwr5xAUnjRy2yS";
export const pcMint = "ETtXHzMzv5dKrkPwXaJ9KLxU5pa4drHKUxgv2VUyz4bW";
export const bidsPda = "CoXdUQbUi15XrUepj82N582t3fCF7MsRiC78jBa8u1Tp";
export const asksPda = "4wtNd8WyNu4FhUabqhQ1FTxhYJHvxsaexoJqnkHRk5qB";
export const reqQPda = "CF8c2iz6dWDBAKXdQDZLTRkJdQMKyHy1ANBsJCJBfxWN";
export const eventQPda = "EN51hm3Dh9FXPT7taEMXSLSQaYCJYRvu3oKRKAic58xf";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
