// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "AXPj7CLFMGoX9hTQDUHgBL7dENAnvZZoHa3T6qGg2d4m";
export const coinVault = "7fMxfeANrrKtnNhbsafVA3PXhdcB7XMtU5L9G2GznNvK";
export const pcVault = "G4CQEpAPVQyHxfoV4gP6hFTP1LnEd78RwaipZ19d9ybH";
export const coinMint = "7ACGUoN46ZkCJRqtWtuQo1VN221BoufXFFTsfbKMMJAM";
export const pcMint = "614AkXquTx8vfq79etCNf5SzmynzPHHckNCyn9zG7zM6";
export const bidsPda = "DEmwCwCcxmx27nsitcYt2aCu35FF8g9VHR9mufZrVNv9";
export const asksPda = "EWc6LcjRAMxFD47uuQLmWcKHyCRwe8bbPUnUHzYXk57B";
export const reqQPda = "FVJLAAt1DfMuod3GPmSHSSeYZoToZyjtXUUdTDcf5ZDu";
export const eventQPda = "AUieJv3zWUqHnLdhprnzL4CxE2XXAkvb9KxAyRoc9soX";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
