// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "2oPgpX1W6JZLBBmEAT37ou9h3ATk1vkaH1NG9N9jQWyX";
export const coinVault = "FL3rn6wFeqZzGfrynS8AARM3G1rF1eMvuDqHry93N5a9";
export const pcVault = "Fpwm9EU6Z57dA2KN7yrJFs8hhragR7yLsoXpU4ZAomGX";
export const coinMint = "5UMH8uHNepkGYhQPwc8RsHsthS9aPfpMLFmBtLnWkryg";
export const pcMint = "KiXu3nJ55pciDTkhf6zuU8CPyGUY9iaRoo7MziWNRCM";
export const bidsPda = "EKCLXv1TvWMUdMkJcPFS6kuDvd9PbNrstoCgrBR9okc2";
export const asksPda = "CwicdLxXf8UmWGcMRr9iZPFq79MguJF99KmpBHoL5iga";
export const reqQPda = "45D5MtNqPqXrtyVNe2RpWd4FXaDyaPZnVpf8gtFVEvh8";
export const eventQPda = "9AZ4cfAaCH1muBE4vJQp6a8iYAQmofz3JTxk8qqoBGUT";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
