// This file was generated by a script
export const programId = "GJsyZs9cr8agF6SLiLfxiS9A11Avioe3JVPie92N4SNw";
export const marketPda = "4ftipwBU67sMkzcoB5f7XZVW824BUtYqKQboeMUa498s";
export const coinVault = "4xNiBVE96m2aFfPvv1YFfWp6ZqRf7VTVyU49ynyjWxQr";
export const pcVault = "4dmT1cRFWktVXLpBPc4KKMuGeiVW4Hh477PTFbHqNRfW";
export const coinMint = "82MdNazAXqARP2n5ENEWP28KpwvTfFiHZ7m9U3Lk1LBV";
export const pcMint = "75R7QYH54tAYaVoHzR3jzbkAU9LsPGk8kCLNvbjuCYYG";
export const bidsPda = "2ZNHG4wkLPgznXGcoErJjd39AtHTfRXcNezW2zV8rxcy";
export const asksPda = "Cht7t8t4ooorD8Dps8mJ8zrYvsdLXjzmbVTCfmLDL474";
export const reqQPda = "5MYDKrEKw4eAYrr3N9jjecN56A6T3fHNhbt8bcTpfbug";
export const eventQPda = "GUcW1xrmxQT7wnDF9jpvtdFaTbQaJ6eqZMh7zQ6WpcpH";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
