// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "8v2myhRenHLEWifuLnkdeHQZGXi8U7WuWFbunuLLoDe";
export const coinVault = "FEN1CzaLV8vhagDvvkAzanvcBpZbURMvJh83obt3us5r";
export const pcVault = "33QzrFsBdCoMuR5u344zAutdhFdtxzu6Nr4vfXcmrMQj";
export const coinMint = "Et8uKDvroDGa799Rea2YqL8mCv5B87EhEF1YuHtVcDqy";
export const pcMint = "AvyD7KBALjVeWu3jFKCmu3NTZZnaRG8cbx77ExRAqRSw";
export const bidsPda = "FU5wTLsxYKkCPcLcH5qvueWm7cNekikpJnUxdSgsrYB7";
export const asksPda = "7sHNcVXPfwRdEA264pj4zEbkq5d6vE6LB6EYdQ6CvZxq";
export const reqQPda = "55MT444tHeYbUZzN4YvEwwDdiG8BJBjEmfao7zAQbFGk";
export const eventQPda = "Ee1oCrPJv2tAEUY3WpgJUoWquyLgycDDBz4VhRFqMMg5";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
