// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "85DHy3pTr3oTT1WfKRoMJ76moJJCYJ6eiTMpdqBgM5Qk";
export const coinVault = "G4yxaxgNMDoT5ngV2c4W6vU2Nn2KHo2zvwYnGyUdHFgq";
export const pcVault = "FgtakTGcE3LA42KpA2qSq9LtedaWCSQ7T8KGQzodHgMG";
export const coinMint = "H3MESfGkxtHPDttrNAScfWra9X3CRQ68CUQGXkzLoAei";
export const pcMint = "TL6wCTW7xQaanxjzzYcFsxviFjw3BduCmNznwRvzrp1";
export const bidsPda = "3VE3ohbMecMMyWTVZPQs8pdJLGtn8v4ztUVpK9HWjjVN";
export const asksPda = "Gj7LVk6eRDWLkv6fkzwLwLzmqtG3c8vALLsZkZNYxiwS";
export const reqQPda = "H3EobYZyoFYMY4sGhjY88gz46RzgRRUMKxnXkkjqEe2W";
export const eventQPda = "J7YsgDqKNkLtXX5Gs3NkEcwKC1k8w1x5Ns6UqvL1wqd2";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
