// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "HRQzpnSrZn3MHMG2pp6D4JAK9CJQnuG5ZGA9f2PqWzFh";
export const coinVault = "BFgwxcBTzYyPPo7BFwZ1FzNZM8T2BRNGkvptnCxCUt5b";
export const pcVault = "AiusHsdzJHmDGLpaW5AowcjddMzBfhqgQgqDQFGRpeiz";
export const coinMint = "HaxsPybxuiNVPTAxvhGFodZSmxLtuFPege6n82yNxnTq";
export const pcMint = "27PWwxt4tYWNUGawauqaePNWhWnKiqW8PsyH71BwE2qc";
export const bidsPda = "35kV8qU5YiHKQMzUN1xpcgqVob4R25NMTRvGuBFiWBv9";
export const asksPda = "EnFhb5yDtAyxdHPFA7TyGnK9xstJsPinyEnRbjc3qAkt";
export const reqQPda = "2Uo9agtiHWshyXvk1CmisLv9RpEFCPcAjBDQh9ZBuCLd";
export const eventQPda = "4iuHrAeAZNnveJBmZjkFGeCYvW7fZZWLbaaWSEBPWy5T";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
