// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "9Qg6KhKKwaemTaFGwd5H6M8gWsx7nKaSxZmV6HtfCmXv";
export const coinVault = "JuPDWXpqEWwrr6Q6yr9nMYsx6Pr8AbrWZwbUWJK7Ncm";
export const pcVault = "9KwZegxrftt9tn2KtzHo1egqYcF8awsy2KaJVsJHMQH";
export const coinMint = "BxvgiiPu4RjJZ7TMhE4VkVfQFWtU5XTLTw99Ehys3PRs";
export const pcMint = "Xit7fieHRrLvJuVbM4uTp9Yt5PkFez97kyyVzSkcTMF";
export const bidsPda = "5x231Pt2C6Lb1bRoENe6ZdierpHXhkF1oWT4QRCuqHwN";
export const asksPda = "B8cQ4LeVWSJLv7wJnGLRQwx863yrcWEwLVttMqTA3in9";
export const reqQPda = "8bQo6iBtsh9iqRTdjxa5YGKQ7W4xx9QWuPeDz3ESPxxn";
export const eventQPda = "9zFz5thaKgwewkseJXEPXQ8rkdycfuphXDwaEx6w7vD3";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
