// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "9UaCLWioSCo633W9eSyi2WrqXkmhikxsowHvR1qoG8s6";
export const coinVault = "4mw6SF9YyHVKVeorVG4wVVhzfvYwyMwbRHCMNpo3ebJW";
export const pcVault = "B2TdmmHvqY9Ei6JtgTTigUQ2hS9yPJbVLQvVfnGokYUa";
export const coinMint = "Hz6S2YMxVjZmqbtpYFbdnzRuqhe2Czn5V7ZxRUYnuDdJ";
export const pcMint = "4oMW3pQTYCUpAJ4jUzhYAQfRpabaUrqwv4LHewphNPXj";
export const bidsPda = "5vBhbsgwotSkDSh7htQLH6iPWE77fzn8nqnBsrT79Nzd";
export const asksPda = "DbWjfsoBxVADn8tURHiXFWAJn8uQixCnYSW5H1hUTgGe";
export const reqQPda = "2W9dWMri3xNfWZdZKk3s388jFfGExQqzrDM8m8cx7dRK";
export const eventQPda = "H3Kxy7YqM3dvm6PjW6ReyRAq1myauUY3iACBPGnmFhtm";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
