// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "mByNFit7KwGVP7R5ed8RpewR8gtjaLgFmxB9Cdjh4tz";
export const coinVault = "4rVUv47rT9KLHZEFpjCMfyrSDCeFUGm63bu1Q3DvEQVw";
export const pcVault = "8MBLAP8vuxTHhMJBfaUWndyRgj8zFyTvYAWDybreVpHE";
export const coinMint = "6WgcHAFqn3Rn7oskyfnEcgUo5C6KCUodctPMyoKn5WcP";
export const pcMint = "HQr3hbjbgoGkz19chnnXVFrt65JrjSef1FEkWaSvHGLc";
export const bidsPda = "CPdn9dpTEuEfPPEnk1vpzPndj7WH88E6CsXEJXCWmimb";
export const asksPda = "AhqSusuL2NxjVahmFCPrzMXsTJdU3n8raKmdsxAvK3EQ";
export const reqQPda = "GJLzQbHwEFYYr5EVc6M72huX8YcCM6XwoJsrfeW81mek";
export const eventQPda = "FWHVokTi1Jkju7ZEV465Mk3gyD815f51bpGR6zRRQEGs";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
