// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "CZSgGkw28zP86oyuYoRcr6MRmnBWvKKh2m56yDDLB9h2";
export const coinVault = "EVUT7UANWKGJ1HZmJNYEt5XJubXmZvrn1GHQutxyEogE";
export const pcVault = "8WNrkN544LYEeMuuxyUnWyB1pySnBHR471b8wRFQ7Lyp";
export const coinMint = "5ETSYW3DBRzDp8iLVantxyAo9akD2DMr54TbsrV91qRE";
export const pcMint = "H4E5fBrV3iygLu8TgE7GaNNEEp5nBqwKsjZst96qLPVH";
export const bidsPda = "34FfDDmu71cY9JuFZg7yjYNJbbrdmmHCcqh1Avi1kYHj";
export const asksPda = "257NyYEvRvwsuFzjQJupCjwDXAqFTkuzxvbHVYn6qENp";
export const reqQPda = "BkHqDeTKstjg6EbQKcK4VgGun4zqnmc4osFyW3QywSUv";
export const eventQPda = "DrXngyrZuU4C8rgsEwGvAcgdWgXfVJtv8gEmpzJvx88q";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
