// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "8fhuRHCgiF6xDfWkZjU3vev9Z6QYteSt4ZeJHi2WHbPE";
export const coinVault = "FpCCkSy977zkUh76uUZb3evgJmf4HQ7NJboVqjHkvDL3";
export const pcVault = "3v6vVVkHtbUiWTbZHoYfx8vBAjBdxky9RdLH75ZBPTPR";
export const coinMint = "EUQ95Xtguo94NQBmdzpJmJ3gmjzijWyPWvWaZHGYubuG";
export const pcMint = "E51rdhbnWp7WhAdTqx3dnAmemqDT1v4nsQnymMEWso7b";
export const bidsPda = "3TR5erajq7QvTF32R3xLmZ55nnQn2a69jGyZNqmrRx8Z";
export const asksPda = "AfrbvXv5WQNoDtupFa4fCYbTwKU1TgzEbN4BULvp527a";
export const reqQPda = "9h7sKoUriHxnnZca2uzvthtvJjcfqEeVW8zpZy7m66L7";
export const eventQPda = "4hZrLHqHJe7EK1eJkEH4eYtQ4UdLMtpcBSpekJyvvVjU";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
