// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "5xCsPe2VysbWMeVx6qSkHiF2yKYtPoB5SmRpMMA2qFxC";
export const coinVault = "BrpBGDSTdKfFbyCD58BNc3LKaaXuz84Et4pDswHgNBCv";
export const pcVault = "AWovscLkxc92quLM8Vd6ui5vdxbjL3NrrngHLVMLaHvJ";
export const coinMint = "6kx2DGMVgCy4FepfDZE6Yxz1aicmzm55yNbEsiYVRbVs";
export const pcMint = "PjaqfAywXGMhVcHzXE3PY5Ru5LQfB24LdNKbJWSVqkF";
export const bidsPda = "FaSWBvpp4HGDgeTADLGXv6iW7DqHdrosRAMQvzumeamL";
export const asksPda = "EmXQAMzoMBEEoUfeVJeXhJYdPjGyp9jWWYS2Zud5MRqQ";
export const reqQPda = "BH4KmGA9jcSE25KRJgeoR7UC6ydRDq7th4Wjugkos4VU";
export const eventQPda = "ABLwra5fmwGoufdaudVjoy7wRE8y6g2UUAb1WUQ9Jxhj";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
