// This file was generated by a script
export const programId = "GJsyZs9cr8agF6SLiLfxiS9A11Avioe3JVPie92N4SNw";
export const marketPda = "C4rVBoHXbKhCmwZzsD3XKX2hakLNucRPQx1vka2yEhhW";
export const coinVault = "4VEQ1GeqKQc64Cx3mF3Zzn6cEsz5vmPjcbJZpBfNap28";
export const pcVault = "DRrpFSWSW24KBjavhj1nowVos9uJK7vtVsdzmFcL4seR";
export const coinMint = "EFJmfeCz11YKjVqqa9HCAqkz6KdbWsFqRoCjAGbVG6eD";
export const pcMint = "HJHjmNr3f5TVtNgscS263MvyCvXnSj56HVRuSDf2ex9t";
export const bidsPda = "BqcovVW1UxFojq26iuHcgpUojz2rXye77c2LmgioiJWu";
export const asksPda = "AeovmiMmpGnmptSjRq6BwgLj2NMvqGXekUDkdyKJ9ZLT";
export const reqQPda = "CcFZYJcWgnZF6SpmCkYkNWe4DtFRsyRbug13h6viYWHV";
export const eventQPda = "HeWQpDPPZKCnJSHLkwjT32xgomy558AR5V19JCxYHcLM";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
