// This file was generated by a script
export const programId = "Aodrp8JRS1tCywT97x5ytaoJYczv44JYtyBHDJGLCx5m";
export const marketPda = "FZirSzvVVXZqHx4EwGSJe1kL4MscwKPdP6rNkDz5N232";
export const coinVault = "2GSA1Ycv5ceZ5uK9hUVNDSMAp1QuMU7ebJhZwf3opwKq";
export const pcVault = "7AMJaQYyWXAJ5qSk8QMPYCh1avynMzZXGVRQtCcyVZ1K";
export const coinMint = "ApD7mhTT41vExbhpKp6w8X8hawnwLQU5b3uRaV6LvxzM";
export const pcMint = "RWZf2DdbiYgHRy5JQPg6EgaNHyWh85VQ7Jsc8VMBcUK";
export const bidsPda = "A1SNGyhMEo9bdYYEeuHdskNnCLztr1gbNMdHDmqRwHGc";
export const asksPda = "67SN2NkEL2njG4EaAwXqysc7MENU1TMKruUtaRcUAuFa";
export const reqQPda = "HSutDKRtXji457aoxHxeh8ydvoyPCc5oWBV8snryufRS";
export const eventQPda = "juxWC3TQ919DHgRbbdDAAFKTNYfvZ1zd4MyK4zcRB3H";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
