// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "9d1eBR4FWrW66tNa232YWZZA1qGEdPu8hmTb1SwVRR2k";
export const coinVault = "58oHLWek88kibXu6fKqi83RQ8wXSEfKDoNrXefX3CyDu";
export const pcVault = "3gWwGjhw1Q7R93fim7XSknkQKqdZ1Lxnfp5YRmXzFWPG";
export const coinMint = "H3tYviqU1Co8u6buiycCFyWvCdrDGztZvXuGJ7oS8WCf";
export const pcMint = "2voCQcEEZfCSXoMCgPtLK6XU5bpwc9gQL6kom5uMCAGW";
export const bidsPda = "2AazNJkUFMm5ANerSjsJFu9tET6nMb3YyFn21jnEN7Zi";
export const asksPda = "BsLqcLKYoeXdaUJzYE4f6LfSZNBG5TgTfA5nd3C5eZVW";
export const reqQPda = "FkFQ72z24AfyjRRJv9PaGbFa4SsFca5SdwM2ip49CTHz";
export const eventQPda = "594CFy4WuzNaiTfVRwm4Y6sAnZNoH23Um5PBunM2AgbQ";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
