// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "2W8JDTWz7Hh2RLcGm7EFZ9uTDYSVpa8CozEukwbHRuWa";
export const coinVault = "4rNwKSp5MY9j4UzYHCvgTDAcBGdYjVNJ4Je43CGtij9a";
export const pcVault = "GvNnPSdQRCueFrjtzGYbx5T6D4fKFwsm8n9C8UwX8paE";
export const coinMint = "7fYCA3a8xpF8f5X47agPP1sddzgXTAcn8xGNVVZHcjtf";
export const pcMint = "Eajecq58ZkjXkMgakN1cs2wGXCZ2DCuWi89sUY7nYCSM";
export const bidsPda = "y5fxPx3avquTy3km4kaCvE1jzKFT2fy545mRGcM6FRW";
export const asksPda = "FACi3jQbuMr2Tnovj63gbnE7SV1LuyhxVZrgzABJsWSH";
export const reqQPda = "2w1xxWw15bGbELQsWAD3wxpWBqs2dsRpf739FuRTvZxV";
export const eventQPda = "5jatrk4Ky7Zc7VKYwD1kiRQEKom9LbhUmh5MAzZoQNqC";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
