// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "5jnW381vHAP5huc9LwgThutjacdipWL5dTgY4xZ3imgV";
export const coinVault = "Fn3TYFbKFc4zryRhJ4VQfUUydHp1hCnH4ZvrgmYPXfrk";
export const pcVault = "Fr7ZkmLVnCyDMiDL6BW8iMSw3eMsvvjGrRZtjwTCE47N";
export const coinMint = "8s82HFdzLEb8snZv16p825sRSmX5pggWsaHQE17sPqaW";
export const pcMint = "E8HebkzU5j5sJP7MAezhFaepP4JsM6HNa5u1BEyYzETv";
export const bidsPda = "5k8EUmsmXySmFfxJgH1BNCiugi1U2p962bSwJYyoC8Ya";
export const asksPda = "mrNFLzUKkS9jtSH9ng4PcATyESbWFdigLra7S19YXYL";
export const reqQPda = "52B6F75kzE1dnQyg3QphSAbKc93S8x6pXvb6ktjnmoSR";
export const eventQPda = "6e1dU8XpUuVwk2DLJRa4HTFF8btiBhM6ADwdZ6FgJWmC";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
