// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "G4H69Rd9vq8XHjicjGvn44RXKvNbgvNkExpoZvPPhJn";
export const coinVault = "AMNoyFjaKLJ2uZXMx8gbYCKHXe2fXLsgKEGH4pgNArfr";
export const pcVault = "7ZFTFwxfFdGg6Hmx8HKEyedcrPA2BDGVR1Axfw4nhDCp";
export const coinMint = "BN4YZbwCztGCe7SGR81TamzLTPJg8o8DY7cw8KQFzyhW";
export const pcMint = "7px8RbhjDhUuuekkTUvKdDSkAX98dBjPuKi96GoboURx";
export const bidsPda = "HDardLmW4TMct47LsEuLp5aWK1sA9jvT9r2cAV2BxDc7";
export const asksPda = "6amM51EWw7XsPTyCJEB81BCkruXWpo4eFi5YMWMhEq7n";
export const reqQPda = "EdKWwsMfQ5iygvsf3zPXnqK73MLEnC2b428jTx8th8Yz";
export const eventQPda = "GtpJUCGX9roF2sADpc7WXwcdw7f6Ea2PpQ1en2LVwf46";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
