// This file was generated by a script
export const programId = "3Ek56WB263s9WH7bhGtjpNkFk8V2UDXmvsKxDJ9RzmGR";
export const marketPda = "FXGdKhdYyLbn7ibke3oaC9WVBdsXdjtSSKugt3GKgU4F";
export const coinVault = "AyrFkW325LnHEop4VmVCzZhUQ5uSf9SJDxJsAPT82f1m";
export const pcVault = "7BfjC5cKX7ZEvXNmqbK2sXYG9deo8nVx1qCT5uggB9Xw";
export const coinMint = "Ffe5ftnREhJzuZ9dCAodd5HfMXGh7KADiZBLPDxSZVaB";
export const pcMint = "B1GTixVd9me8bAscYdCnUVJzDd6Qy5Tnd2VEkiJRVrz9";
export const bidsPda = "DRFPauVrXKYM8vSDT7dd36gVfmXjL6i56z5RLdes5Boq";
export const asksPda = "4w4c1FHyGw7zvDgR7F65xoGFydvGVWqBVYMkFejzx7MY";
export const reqQPda = "k8Tow6p4DcRVmuVV4PWzGX3VnwD2vw1KRtSp9edkoTD";
export const eventQPda = "82D4SQdM4V8rtaN5K62GckuH58D12BReAd36Rwkhqoxw";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
