// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "XZqF6VRBVgTDfcPTaEtq7VC3cR6FavMUpo55jerze41";
export const coinVault = "45ziJDC8BthQ8DSudZKreGr3guGnCCJhgEizVo8Np7Aq";
export const pcVault = "4F4kb2VjRzZJZK54jB3Bf3MHPYNysrYAy8qXkJ94wLcg";
export const coinMint = "8MzDhRaUoYjbaaYcgWymFVveXdiHdjGtknDJZaGvpAMY";
export const pcMint = "GC7GK4CC1sUxEsWtHBwyiMRLKfds2mqtXb1EBGJiMSm5";
export const bidsPda = "6iC1iePmmpPtrqiw35Kd36r6xhNNkdfmLp6jN5f5Z3rz";
export const asksPda = "uDXo3Rhs46a6mjiQ3AExES7jkuiKzUYA2o8x1X1NEvy";
export const reqQPda = "2vT1kvDgem9Yd2wkNAsXF9UhJBxjKsybWnLr8q2mprr2";
export const eventQPda = "87GYSCt3Cwr6cYPK1pjgy5k6CNXHikA6ffsCVJkotfCV";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
