// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "EFY9H1A4Pc3hEebWX7cB7VQG7udvXgzG3QsAXdxuoG5v";
export const coinVault = "7pu3WUoxKgbJVwB1GDkvkN6vp4UQ1tDVcmYtjctEUNxR";
export const pcVault = "GywGvK4ZwEZqex7EufFEtwk8tKnj1Ei3hFAkAV942wpJ";
export const coinMint = "J3cadHDMga4yxx31eSkeU5Xbkg7wdvm2pb4cHkBGsuex";
export const pcMint = "PQDx9fMQkTnodRUugDscz4X99N17o229EMjWtiYuVmL";
export const bidsPda = "De8EozZZPS1HgQQ8geYvtDrfGY1h9uBLdV6s3H3JmXg";
export const asksPda = "DVFuvyyZhhPuCeLq9JJXr8W5ZJtKB7bhQfMRiFsqCzqQ";
export const reqQPda = "2zfBrXvsJCw8VMmSD7W4nbd4fygBPbtYMZE7AdWM5oCf";
export const eventQPda = "HoBzNFAWjSeyskU1ZTa9Fx8aDHH98jBVV8h5cUc34ugB";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
