// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "6nwsz4yiLtbbKoeLV98UtzR1MVAmGAj4DRZmQLyQXQVc";
export const coinVault = "6QpNpTbfTtfc623wAuArFgoY3Ea1DRE9pwSbkoXQCcWL";
export const pcVault = "5HzjvGS6jGj5Kohay9xMorknESEKq3eJ4wUwk7TbPB7j";
export const coinMint = "yizBbmRepVx2w4jHuP8d2GvZp3briAy3aJMGX4m9Muq";
export const pcMint = "C36sWephdcvvMtUYXYvjqiJXiNdkB5NrKXoUEAA21GTc";
export const bidsPda = "9gbMrKBARG7nzLXZ7rSfs4EMZERKNL3yZSFDRwZjtCoj";
export const asksPda = "47kMpaxsSE1P1YVHTwSdYacLHBzmUGpzk6r3NYsLxwin";
export const reqQPda = "Ac67znErDgQPZs9f18bgrrpiiP2oiV2oQMNcecfmhp2A";
export const eventQPda = "B9L9YmwvcSWbhwEUKP6mEkEVeSXbVMJ42zpGzUqn2yYP";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
