// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "5jzNyBCwZjwe3MEieB9WoVLRxvB4rKvHxduFtFRd8mc6";
export const coinVault = "8GcEcDmH2EyYCadkBMvsqRwbXSyKbATPiRhBhdkT8owf";
export const pcVault = "4HyqnMUuULXRaAUGzKicPQuunycQj3ex5pmRJ16Nuvcp";
export const coinMint = "3agFYNfGy3bnr2tqhmKVRYa1VeQkvMf2kBeu4af3rMCj";
export const pcMint = "9RqANQeMiH8nqEecvz3VHCy1B51wX9J2MfyR8PYjEjSn";
export const bidsPda = "APSjpeJt8XudNDRFNLFqtB6S3rCrzSVKQYUjgDpjPv6v";
export const asksPda = "CZ99sNuxXTqGrUBv6YoFWkRtz57Us8aqSmB8oCHAPYuM";
export const reqQPda = "5R6k5D7PZPZywKASa6J24z3Jj1ASSpZ8qhJzxxadWkhY";
export const eventQPda = "4fr8deR3aW11aGudLxYgi6wkL37zARzWFrBTGe8verHn";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
