// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "7fbD8kP31G1R9RMjTGeTDEpfvnqiNM5z3E5br9qqXFsE";
export const coinVault = "FcyJqm9cTfgG1ZPwZoS6gezGQiFPwQMZuvo3UvCGhtp8";
export const pcVault = "CRb2JGm3xMgbUD6NVCJq1YNCaQK9JjakdRkapBZqBJU1";
export const coinMint = "EvZZQh1TxWudRUDnp5WtTUjPtx1ZYBCQEiMdayNrWfMq";
export const pcMint = "6SVZtKdrfLNU3tqJLXnr6Yz5ETScfCw6hGs8Bmd6wjaE";
export const bidsPda = "HV4EdUmB3LT66XBoTAD8ck1T4KEnfbAyfJapGLmFW3jo";
export const asksPda = "21ruCJ7J2jFZVYJ3tSPzNcAeV1mTgiJPqCanW3oXdqow";
export const reqQPda = "4yitCtaEfoxfCuUupqg9Q1ViT5rZiDkWPUY9dgn2HDx3";
export const eventQPda = "HCBxv8gGxMdAwUzFfPbEmaWNwLanfpz2yT1Vg2TkWiTC";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
