// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "FTh7x1o18dbhMBF2KUxdJ3hkGykHVJ6ptBTqbTR2nWa3";
export const coinVault = "3F9fiFFQPChzMvVAxRFkRGVaMg6peJzT19X1VQtRCNtr";
export const pcVault = "3aPe3RYoUuL6y1TgmP1QeXr6vveeFqPiAZV4bs7fyRF7";
export const coinMint = "8QhxBCzp9FM6hWwF16f4YcQATaaMtZ1HasEBsbQQxAX8";
export const pcMint = "3uQuqHzBDwRcmRMFunFjGUN5BM8YDx6gudTNMavQMJwz";
export const bidsPda = "AGaG2UpkdSqYPzM6jAjQ3WpWvQuVGJUuwFGgVU3KYVXZ";
export const asksPda = "A3i3uPDs7Q8Ks79nHbXSvvqnwTahfk7RcJk1hvbXxs4u";
export const reqQPda = "Bii4bWLY9meLVNGrdQTaobePyjTbmqJej9pYt1sCcEUC";
export const eventQPda = "C71jm9N4EF7nPBU2udpDFvGd1HK1wVkxcHStVe9X1n6m";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
