// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "DpVxBP6DvvTdzTcS4fcWmYTzUdyGc3Wnt9K2EacMaEdH";
export const coinVault = "HjH92Bq18tY7kP8p7BR6SVPRsG5HY8Mr9Bpxq5DWMTmw";
export const pcVault = "2QyxeKcpYzrNxV2JDqAHNJwdVthevp8GRPWq9w95g6i8";
export const coinMint = "FbWjeQWVPDSEPx2jRG17oMogYmZcYzkk2n1w5Rj7NahS";
export const pcMint = "83GXhwo6mxmWTCrHm4qXpeoVjpMHAm8WzFKcq5mhSN7u";
export const bidsPda = "F6PDzbPoeTYLTm6bxyp23PBad2WjBFX5qMfgxDp7Qzuw";
export const asksPda = "4nxzCWEEZ89V7piEqAq96L7rBnHwmaLhLjoUShCkKNRd";
export const reqQPda = "61JMwvHjt1DytyspnPufy9uLgbd2PWxLdH8c6yN7YG5X";
export const eventQPda = "9HzMKhxUheaxdz4H2vMyQjzjHYiLdgzCx2Dy1vWJ8R7D";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
