// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "APAzJ7BBuqpJf3u8uDHjcXhGxhUv7J2fWv8GASkBR4kh";
export const coinVault = "4nQ2n6RnGUXZ3W9ZcffwboGUbjmsgXVrywPnUrMw2BTT";
export const pcVault = "39EXf367UoTecWTiavPn1q4sRQkD37BfXG1PkCdTW2sy";
export const coinMint = "5psPjMNAZnq3yn6icQDemKT69QnnQqdKCezqAUHpTxFF";
export const pcMint = "23D15dFpZhQvUZyhKZawjcXqrpZ3h98YwNTiKLoVus8i";
export const bidsPda = "7BHWjPx73VmrTjMXBDyHxjaSMQkhrPqZaac1hfChFiWt";
export const asksPda = "G1ot1kgCyUb8qChG7vRhPVd1NaX86fGF4TDPbakatrVr";
export const reqQPda = "JRSkCNLpXbL2u5XNZs63bFzrUDjHCEUqGELMKKR3uWv";
export const eventQPda = "4KGBt2TtMuW5CoeVC8br3npfy4cfT6LZMm9FbKhfkRZU";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
