// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "Fs8RaABETmT4W66iRujJhCSzdMXcsVHUwtHtvEXCuzay";
export const coinVault = "CvwuBRnR5JxCJpLc3hF46ngTRXrXp1nLdFnre8U5uDag";
export const pcVault = "4j49faTF2vsaNWeVBdq7LVTnUUUZwp43LaXZUPZar5cV";
export const coinMint = "7LZ5XMjhKdPGFJaDYtiAD1XGYvSDtjawh9ikWVYahXbo";
export const pcMint = "D4mMWxSK3n8dMqfQdE2tYcDBsxX7QvCkD9Spj4eNkYA5";
export const bidsPda = "BVYg5jYrfKvTegVwKubXMYnBGfwJRBcYMmJcGiuNDWNf";
export const asksPda = "9jLekGG87hhG86tyzzpBCiBnLQxpdDzqQhsv33AQDThk";
export const reqQPda = "JDuBeGjbsiZw4xvK6ZEwhzewz1rjVExeaHbv3faNNTbD";
export const eventQPda = "HeVqx6DBLscz37zUeuPHhsrceCmhNhWi1TTu2oRHvL16";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
