// This file was generated by a script
export const programId = "Ba6zUQjRRWzN43BLc4sUVS9oj4KFYwzcmHdxQiigRnCY";
export const marketPda = "DDxDw8fXzKqYCUso4EjJRtwQ3nUJVJQenAQLJjxbpCS9";
export const coinVault = "DV6p7XcbvSy1WrhR6tEuWBMJt5ocFC5FdWKkzkr5zTbr";
export const pcVault = "66x5mYEMc4idahAevk6cvByfthyv5zEnXJWpZxRXuPbY";
export const coinMint = "BimP94mRjhkhtoXRHr8KeZUu7kzhyrvmFw33RAZtCAQm";
export const pcMint = "Bw2iUp2JjYjMaK2nWYeEqL8snJ6Wm8bnSA6YLidjuXaP";
export const bidsPda = "94mjvFypxwLsTbDCPj3auTgwACp9ZCvdv8t1Q9dn8wxX";
export const asksPda = "6t2seb4FbaR5DypijjkVQ6aQJhs3xYUwvH6yPMPbq1hw";
export const reqQPda = "3A9aNKnfgfmkDt9gWNMHohrvUXzk4FpiXGdxewR8aQjg";
export const eventQPda = "6HjDMM36paT3otUyfhz32QKUgzasdCGpGmWM3CZ3jN9K";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
