// This file was generated by a script
    export const programId = "ASrtYDNReHLYmv9F72WVJ94v21cJNa2WKo3f2tGoAH7C";
export const marketPda = "53FfwssTmJmgjtkcVocc8S12WU7mo8SoDZPVXXG6a899";
export const coinVault = "DQeXU9mTqgzsxbY5mpgizX9bhZ84vRVhG86ZuQioQXvN";
export const pcVault = "4n61HFLggayjkdCSXWTpa9srLQV8RpWAkQSBegD8rkDt";
export const coinMint = "anggUCoHxhRkaAHSLEvotEmgGQoG8neohzgkNgN7pqi";
export const pcMint = "GXRwHMWe7TmPeo3NXDdVDv8SKPm6brMtcitBCAwvaNnp";
export const bidsPda = "EWh8ybs1nqJUADyxVGMNTtHJmgirv7FNyLqvuprbBnpR";
export const asksPda = "87aqhRewwaSuguUpHGYwDqtSfHq5wLn8r1rWv3s1367w";
export const reqQPda = "4dxfDyQGgpCNMfW5jAcU1YKAto6pSrKMcNonJWCr7yDi";
export const eventQPda = "DogCYzWqfXNLE4RSGAD9rFnytzRG6K3v9MQtUwLhFH9a";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
    