// This file was generated by a script
export const programId = "8yskqQf58n63JFYLPHhp2dtC98gNYYsjEp15XmBJV8u5";
export const marketPda = "DZz3Qes1t9iYT7mjiLVHPyrffWfov123mDCC6XDE5RjF";
export const coinVault = "Eb7WfNvV5psgTtDMTc7sc3aWkzmstxbvgMPMeBf8MSit";
export const pcVault = "8FavVRgmUEnwA3Tra29RUxrjFP57BcVMiqR3RPWJhf1s";
export const coinMint = "FaKB5tHAx5FCnDpTTFLgKCTHZ3KkWucGim7tpV3gcU7w";
export const pcMint = "7exUWdgpBu5oDdU3RUzS7SVoq7QKeY6k7cssSos4t3ff";
export const bidsPda = "2xzBfCyZyMGcAD76Ft3mFXymPTR3gMMRti9USA4BRt82";
export const asksPda = "3T4EytGuDCREoeMpDW5KBbSoLvbrSxuLvjJfBENeDaj5";
export const reqQPda = "9FJnvNeg4WXjFyD2hE6ZwJRPsWygVeqm5e8LuxySic2p";
export const eventQPda = "5rDRc397zaqsXjHFNZzB3g9J8AajHU35cR54r7qg3QUS";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
