// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "8wzWCWwTTZY88TVWXQunDagNjhJWo35fHNDJ3NnT7E7r";
export const coinVault = "H1hcopZ2J2JL9xQx4jVdGNxUEdG2bpMLKMxLgKBeezvW";
export const pcVault = "49zKpEjH3HafiUVQPtehsmQuh6WijAmLLMkxKS5BdHRS";
export const coinMint = "3gZUHFPjbKXnhXFkyJdHpPZ35arXVWHe17EpxKuB2vcY";
export const pcMint = "ETtZeekzzSHTgbTfPwe4en5947DixUm1LqMPnW3wbKFD";
export const bidsPda = "EWjmPxaw4kfRgorYFCGVFtm4MFxsxpbWmgm62wZqg92U";
export const asksPda = "7HdT6cA5GRJ9C9V9VJ82ZYptUmRQgDh3VYfikmgrDG4k";
export const reqQPda = "2CJ3TDRNNN8KMPBNt5EDSpMGKdQz2nL5svPD5XrYpjjr";
export const eventQPda = "3a4J25YwLhvDumoaCpt4n7vHfqt1xwfVZjdJ5dWrLkri";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
