// This file was generated by a script
export const programId = "ASrtYDNReHLYmv9F72WVJ94v21cJNa2WKo3f2tGoAH7C";
export const marketPda = "Hr1CpRPTVZRBqKjThBGjAQhDJAHr9ZPfi7gQLjspYU7J";
export const coinVault = "3pDNj9hsy49CYHaCKi2Q8BEp8F4TAGmCJuDPziK7Yga3";
export const pcVault = "6xL4sbPcHmGEY7NQSDcEu2et4dfJXcUPwbrQY4CVtHFu";
export const coinMint = "BUaUYECfKpumKncrBk1bXT5ARjP7T3ebQc4trotLsD4S";
export const pcMint = "HwCJMgJhK9etrnx57DZZYpTWybjVFMLt968vW7jMb5dX";
export const bidsPda = "GMRTgvShFVZjyxyfCP9A1pDZEPfyuRC4yXxXNoDzEHnL";
export const asksPda = "BFn5PPQD75ZzGBdoJiNG7HPfYCVjcD1JQHrJHACF5wmN";
export const reqQPda = "GC1z4Wzv2NkBhwiJ6bnYEuZkyTFgPktPy5kaT3C6kFec";
export const eventQPda = "7sjW8LA1mFK29WPCxBbh5tFwTKc2stLNnh4iomTu8qDV";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
    