// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "7WcJzdUrgDCrbgGi6PvQ5acCGX6gUeFxMM2GCfcikjYW";
export const coinVault = "FBMVasVthK1pm69WLK2YZuxiBRBKoUn7qRRsV6BFzGk4";
export const pcVault = "5dkHvdj2wfpit4c2DS56dsnxXX14ueAWuZgGM2q6bnpr";
export const coinMint = "AtE6q3qeyjjMWCb6dkQmzg2NRtpyP72doXc5rjQgxyqX";
export const pcMint = "3dqeDU3AaDpmjr4rRxzgGB4WDrDbE2QKxyekigNRHi33";
export const bidsPda = "BFTtVHBjKvwvg9YdVkYLt6nVWnManMZtiMvnEJyCun2B";
export const asksPda = "2SbYNspBU59La7LMspg66qfwYDXMESAgjAcSUMpvU7jk";
export const reqQPda = "G63nW7DhTCZZSp27C88HH5iTkzn3u53cVRjvqeScdquK";
export const eventQPda = "GhcekAi4WZMPuWf733GHetAzfpoFibci4S9zaUbw11EC";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
