// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "9nNS2T744DzwQMqF1RjGEKz13r5Udcgcjvjm7CFiCfjz";
export const coinVault = "Awddwp9Zi6oEBg6CmYbYFRe44wW1jHk1Q83Hf6Lm6tT2";
export const pcVault = "5voFqowZq1Wzg3cdEopCpsRx2YCsEUHxUDdw6eqS1eKs";
export const coinMint = "7Lp1qACBN2GttTBfzwapXTQm4pnAHBjJDC68re9MJgyA";
export const pcMint = "8abRrvuZqRzXXeCiFjJymBQFCcZfoFba6imHTJC7ykZo";
export const bidsPda = "3Lb5pLMEpDZK7PY6mt5jPSCyf1sKiLrvKS898kjNrsFE";
export const asksPda = "5Db1gJFgn3LW23y6qU5QGc3zWR7kgQ2moBSSi1YM6fzK";
export const reqQPda = "6P8su4dc2ekGhwbzMTUL4Ce3uDAEuFvaFHdSaXtLhtoE";
export const eventQPda = "J9kfLwLMWFjjkX8Er2zSADxLFwFhjKCrQWVzYxwSUjKd";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
