// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "3WYCzSLW8B4k4To1Lx4haFcH6jzHEHUPy7rubhqHiX4g";
export const coinVault = "72A1UkndrgndUSsDuHeq7QA9PNMFwE7fLMvLJMz4HG7S";
export const pcVault = "HcbRJFQtA5WBSMendwdh3Fo4vQtqDsWNtptThkNhCLZy";
export const coinMint = "5mtts2FuJsCikuyDPvpEx31oHUzcFpA6khZhTcCtwKet";
export const pcMint = "75AyfqBb3KEwWELhFPzhd5cAVDFK5BFBUZPqiut7NAbn";
export const bidsPda = "Z2kmM8ingzHYnHKYLiZJHVdDztDPz1HoMDzGUTwhYw8";
export const asksPda = "J3vJqUtFWXSqh5x6b8m58ddUk3yPbiDMUDvjw1o6nnmP";
export const reqQPda = "DXgDTKv7SQJhC4TZywFytvevkBh6a3K6DZb2F5YpowXW";
export const eventQPda = "4eSjUrog7vSPUPGvcqKdg3C3TtVirUxtQWzXs9E6NqWh";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
