// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "ALhYzUMZjUk2HdiWU938Qgd8eUWkW2kqxuagkdopx1MM";
export const coinVault = "HURatEiLeE5GsPytnz8uCaEqcPiZspkewYsJiTo6QD7S";
export const pcVault = "38mHGSo68PTJcWjPGrkrjN4owMrC2zwwL4tBhrUxj36f";
export const coinMint = "tNrCRjewT9BDgzENyCuW4wZnwnGuFM9Ewf1iBuobLHk";
export const pcMint = "A2y64G9XUvGgjKPE1pDqGqMnHh4QmvPMcH6K7tHNEie1";
export const bidsPda = "BqfGG1Xoiqhd8hx9AQpEKi752xsAqVhWL3C4cUgMx34v";
export const asksPda = "CJjKmPgnG3Vw7N2xw9M8mAu5iQPdJVEgXRgFhGRJfD5r";
export const reqQPda = "6uqeuRCStgSKssq6ChZh4DREUHha1Epn4Vp5AfWZ4kSf";
export const eventQPda = "qY985ZBxRtuJaCg2MDgtc4XdJjWE9EB9gy5pZv1DGd4";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
