// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "BnHu7QFBB7yT9usp4egEH4K4nCp1KBcFjQHq1dErvvzq";
export const coinVault = "58xnQVGWGEef6qZ3oQPao6XQ71iiuApsDBtyWfSeP2iM";
export const pcVault = "4a7pxTbM5njgsQD4fdJeCFRdZqQE5n3AcrzRtpEeRFxE";
export const coinMint = "A7zQjq8sBsxR8jaPYHQSET31v2ii1S4Ck7xwkMTrkgPK";
export const pcMint = "DDx72EXKKfYKd9iZBqfX8auwkTPocyt5bQPhKXRWZXVL";
export const bidsPda = "7BnhAe2WF9RA9h5kLqqS3amhkhrhhPyFwp5bvqgVZub6";
export const asksPda = "A9BqmVtV6jTNZLcba3NMhrBmMcTPBRCsi2tYEbcNQtgg";
export const reqQPda = "2AzxKzR97z4XEdtaHZD1FFUVdgU5a3ULSTWXk5SmRHMQ";
export const eventQPda = "CLWvpR4eSWBGzZUTUYcKdNkPJJMWZ8CjtAviiiDpnkHw";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
