// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "C166yo4m3Vdf7a3RCEwXfp4ZqiPPQAVcT1mXmkJyrrEt";
export const coinVault = "BLMwQWyZdDKfZLwqT8dPTuWzBmwWVWH59aarCx5734Ho";
export const pcVault = "DygitKpsofBSct4Pe1MKYQzTiWKdZLhZYHUHMpxEFXA3";
export const coinMint = "YfoAZSdb3p3z7yeiguQ9cHA6QYHnW8QWTduyiznKodR";
export const pcMint = "86fhnG5riea8gR86JzB791fLVAFtDA9jpCh3GWacBcce";
export const bidsPda = "BuHUa7seUTsTntrCdgXHNTrH6Sr97Tprdq5yYEAsZGyJ";
export const asksPda = "Bkkd2NrLxXNx3ZK1TDwNu3o4poZ5PcL6xinoskM44JNJ";
export const reqQPda = "HXozHz8QC2f5fjVvJUjaCHZQvVoc9kz3SzHezU3VG7e2";
export const eventQPda = "HAXaZCtBpvYGKre1sFyHdqm5jdNfpkLTwMFLxv5389ax";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
