// This file was generated by a script
export const programId = "3Ek56WB263s9WH7bhGtjpNkFk8V2UDXmvsKxDJ9RzmGR";
export const marketPda = "GXhvsqZb8ji1kNbsVjLvBEn3JL9NML4fqV5mQtuP9GfD";
export const coinVault = "Ai4RxGRyPJ7wiBhzjdsHZhN9ruMsi3cwPeeb7cFavq4p";
export const pcVault = "DsdHxugELtfCPaS4WcFHiZqURSMomoD59HpLUZfbmiqY";
export const coinMint = "8NPkD4jEQKm157NMWX1ASiPozne2jrHtGPrR2AXFvLLk";
export const pcMint = "2UY5yxqFfsmsB9sivG8JyiGtfRMyn3hMAMMmNryWBRrW";
export const bidsPda = "e7qfs9oyRY42v8ZjXYJURSENwX8Z9yF3Sik8j7F2NbQ";
export const asksPda = "6a3tx7SxAUDfisEoT1m2KokciUhQhwgEQGJD8LRhJhr8";
export const reqQPda = "EnjPjyKEtfjD5g6Cjn8RBUmK8L8CQxLNT3Wjo1eBBZF2";
export const eventQPda = "G5dEVc3JRKXJP5LbVs1uGXUmkrUB9v37wjxhrjY5Ftze";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
