// This file was generated by a script
export const programId = "Htx8mCBRUF18a9wgAr7DQE16CUXejthVXasdQYRtRTKe";
export const marketPda = "3uSxCcUQq2Q9VBWhANxErdDuLXpx9VgZvchdyxEHFvan";
export const coinVault = "NhqYRN4DkqQkMNmGRw4ZS7fjCrSrxor2926NviBtCrZ";
export const pcVault = "AznRDVYKw1CrztBF2dyzjZozF17yq1RDGD4Qtrgb68zZ";
export const coinMint = "46RdpV5cs97WsLr9V4auFf29LM3EaDbfwUMb26duzZGk";
export const pcMint = "54Nf1jXJNeT4DuS51Zdbw5LoyfKK8fXrza4W5hqFxq4q";
export const bidsPda = "ENGiypp5oWYnwr8gPyF9UY5oKn2m8u5KHur6RRr6uCxz";
export const asksPda = "8dXx3HXiHnuL8DbEe5DiVZ6o2ri4mudWDD661hUHaAHv";
export const reqQPda = "C8zPS1HR67dTH6y7fV4bnGwjmvtPMYoQrMJ11emoTqzh";
export const eventQPda = "BZ4KDzRP5dbX7an2qebxUqrrtiDowyTjXQR2LGUa1vcq";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
