// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "GHKdkvSnK8hmQg2NYCcuJddMy7zb2zZduDv6J6AdbfZP";
export const coinVault = "8fVq27K4SV9NWLMUfFtLWjZV22SiWS2iGLT87MRM7cJR";
export const pcVault = "6LuSSiXo9SrHqcodk79XDrKmyefYyCiA4QgM8kheUcv4";
export const coinMint = "4V1rktEzt7vEGyRfSZV2FJcLTdDLn3jnh6RkxAuet4yX";
export const pcMint = "AzAYEwWsM4dmpfNiZYYe45FZWNHjCCZXCnzdcYwQMQqF";
export const bidsPda = "6tmLDWd1wxSNfS7LydKxDd2cxwSp5sKa2gNRz9eTjnzU";
export const asksPda = "2qKtbiCT1P7HMYWwXMRcBZD8mhSKDPUEq1TPK8PMJQHz";
export const reqQPda = "tsYEMTXmBd2sTF8K2qasmCXh6qfT9iqkWxS7a6p31e3";
export const eventQPda = "9jZ2Kd98yBpJRSPYHXmUBdDf1mwRmfmPRoV8MPvs4zwC";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
