// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "ARnxEYPnGYsi6Et3DHwjN7JpPxVVmfdmZ7rzmmxzU5Uw";
export const coinVault = "8wxB6xzuEz6sw7AxPi1vkcZuBK73m9Cm967Sh3gBPEcW";
export const pcVault = "9AHiAeVb3LcRu8gmPwLXfh9WDUuCmEg1dvdY7em9akTR";
export const coinMint = "3ZEAARuDFueC5bWuTJWVX63Ua4MvkBapBNCfLzhb7tok";
export const pcMint = "6HYrNdojofmeU8okFKaBG1V8Ut6ZQCSD2Ww4KNnpxSnJ";
export const bidsPda = "5xugZbDBXoj9AnbkTaGp4voEoMnAzxJYtLGokDVCcGnq";
export const asksPda = "HjubFZhH9kijdcEpYvcELsgiqvDXPSRBDkzBKaNk7iD2";
export const reqQPda = "BJEDkzHrjg82yQ3EoYBRNVexApfWRNiU5i2aKYk23nm7";
export const eventQPda = "DCSWmxchm34Kuj9vvz5LGDfwCkrHziweSX3mjVL5icxb";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
