// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "AMQV3LJKB1uyTcia5X8jLqHGgJK8hDxSK6XqftM4vSR1";
export const coinVault = "6nuNm5TBNGLALozXL7aox2qZ3b7Q3Q5JG8UxLSCjpMPz";
export const pcVault = "9u8jJBLkRsSLiD3cATHKdqj1EWB9wWxA6wKsPwgBX99B";
export const coinMint = "FFk7rqBHuGgNYmMhKgWqSJtGQj6ovRFu6FEXCF5vBnZF";
export const pcMint = "ZyHV8DLiDrwZbckT7PKKBvhJQ8VQQebP1YRJKadrWL2";
export const bidsPda = "6nPd2WXgivtbciv2HPLwMpigBJV757uAg9BH35AHeP9A";
export const asksPda = "9HRgXTkRKFbEMFQpe6VAwtWWx1ajmDB3nnz5oHuwfTkq";
export const reqQPda = "CHEGU9KU3geaa2WeqsiNqeR4wQrET4X4k5YKYtxoSJjN";
export const eventQPda = "5jodvHuMdBbzuPbuftAQ6fTUs7chbZEKjb8A2ae1amov";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
