// This file was generated by a script
export const programId = "VGwPEHBUjxa1ZQyvCAJ166TsKPYCWKafJoDeqdXqvdJ";
export const marketPda = "A6KgDZZjTb3pcCKRC4DDxQvLiPv84QtXCr7cjkXFEBgL";
export const coinVault = "FaaUYDEQmuGcdhhp4vRF9v522EDLbGjGBqyGmNZCRoqP";
export const pcVault = "7hNS2YsLudtrW6TJmm8xsnjfuDCmy1TnGYBykk6WY5wJ";
export const coinMint = "HPqmfpB5NDf1MpKCA3A5spQpKuk3XxBpioaMG76q4BAY";
export const pcMint = "D5CUAJRioX1XMZXTew8f6wHhxKWwpPuikuQEM9AfAQgB";
export const bidsPda = "B1X4iu7xtTQApN7gCGJQJ2soArvU3EDp7peJqAhio6nv";
export const asksPda = "2gQ66R7tXoL2poG7C3sRM3pK1iqQLHtFrz8GPthbnVwu";
export const reqQPda = "BtdsSC8JvHnUKPLGFQhusnkD1JxGQyPbmRG6M6VEn5cD";
export const eventQPda = "59vLkuWhbugLaKuq6dLJqJocjfPux9khqRqUznZPKNRC";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
