// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "AAwnEdAQrxyV43ES5RfSyTwe9PoMMsxU9Xwv1ExCq24U";
export const coinVault = "4BYhCcXwWTdY7Cn6xvJeBCbtbQCBjc9rZJXYjPaikonW";
export const pcVault = "2Df3GXLKzaHws5EcDp3MXw5Gjsx7yZnEVbAHadwJbt2v";
export const coinMint = "853Lk944KFYAWrC93ouK7Y4GMVwEvwYz1VwveLQE653J";
export const pcMint = "15PebbMDgTBeutGnf43qNDZxB21tnCgNGid71AGaCwn";
export const bidsPda = "3wHUokmr2EDv33ABrg74dN3ByCeTq7ySkh5yVaymXjLr";
export const asksPda = "Cp9PHcuqdNJTGncRdXrCtcYc1gUn6ec6YoXvKCNyWAmF";
export const reqQPda = "5K8vfVLJsTGxastCTTNU1dLig5D4eFFJeZK4pbLsbqiM";
export const eventQPda = "FY5TmA4Zis4gjNkt6kWHCwHqivB4hWUEipMCQSS4RnWY";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
