// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "AAj9eWvstnywdYnP1ReJU3Yh9pjGy1uafz1cRi57pHUM";
export const coinVault = "FBT3KsHuLzDdUfdafu928Zh8ipPHd48MzZrSqAEWiv1";
export const pcVault = "48uvxgiGXxpSwQRAi7cwpGsnj1E53coa9dkGcNpMozGA";
export const coinMint = "3bB2dH4WUqyG7XAdprGtBB4366r9cerziFqiSzq2Ag6r";
export const pcMint = "2eZEkj53z9DCTDtTgzzphcph1uH8yZk9nbi4cLW3m7C9";
export const bidsPda = "CTvHhfxwcYykoPDCTBYDz9VwCv9PqfvjsE4fUVJ4pbuT";
export const asksPda = "9jcj7yw4zzJCQBMsrAzcimTJo3SDuzFuR7kMftRuq2wc";
export const reqQPda = "3rFzf5XHXpW1XWpqxEzw7iejdquHFJMAqTgS5RRnoRPk";
export const eventQPda = "6aC4no9dYeLVqCqDcZF1Tow1wFrLi1Dt997LB9j7GwG2";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
