// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "4vd4KArVEW9bxA9Zxs4spyksHpWQVH5AcWxwd7cF18uY";
export const coinVault = "3swgrF4vvGfW8j6JYfFe2cMBw75N9wpo67N7We2mBpYT";
export const pcVault = "Dv8LjumovnXKvE4ficu7ZgrqJm9nCb6osAX1zkwDTxnj";
export const coinMint = "7KDy82w8HfLqJeVNk7PZ48G1Hk1BgFkn5XXqi2hRNz4H";
export const pcMint = "12FRpodqT7cTq3qsSboLvXbHDVV3SqrYUdHtBZUXFkv4";
export const bidsPda = "88qyfcukgbHQjFrTeLbZiu1TiiAVfVViTurXoGyMbqdE";
export const asksPda = "6pe14jkiMsRq1PtkkjHB59jH6pGqZAY4wedtpFAAESJq";
export const reqQPda = "D9sdjEvgBRo6zZQtqoRsqbnXCXvT3oFwCt688cVH6GC9";
export const eventQPda = "4dSDG69W2GNaXbZAM12QKcDoPd8sjqRm3p84xXTjPLRQ";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
