// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "7ByCM3wY5X6joctkxZ4zTzF7Lb3HuzWwxYHqLMx8Q5Ko";
export const coinVault = "CY3GY8iWAJMJzNfTVGcddq6gqg7vhCGVbjAoVMg9ySku";
export const pcVault = "B1ssq2LjV6tGBJE2xVxic3ESnMgk2SJ741k1CXAWZLWf";
export const coinMint = "8bASTGBR33zgtBsS6Yk6FzbkVPWBvA3dC8sveWai2S4J";
export const pcMint = "FLHKtyqzNTFjKkqwxAmnHpa9toGfy5Jx22KsApHJzcNT";
export const bidsPda = "GNPkttXnDrd5mojfVT6agfxg9U4TndjykKYXtjKBahNt";
export const asksPda = "GPK1AfqYVi5GTLtRYfk4nTD9hW7WJVDUMjaQJLauk2UB";
export const reqQPda = "CQ6iWtMfNjWtDY3GBpPu9vyWr31CNs2BxqAuPGE5XGwb";
export const eventQPda = "2vR8sAKEiwuAx3QiEHe3CPBRjW8HSGhioW5Rzb93ZrGq";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
