// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "FC6PqJsKaUpEXqeqC9SPvBg6AAcw9HKPAwk572SaJ8CX";
export const coinVault = "2imRwXJCEFrGw8q3tYcBhvFSLr674ipdacSYczXBrHiA";
export const pcVault = "5FS3AyD5XfeGqYJWrwM4tf49YBdhevNJ3SW8dErjD7U9";
export const coinMint = "5Us41facEzTX3sJvHmgdqcmnhdpSnyeqcSMJGgLuGai";
export const pcMint = "CXTwfBHKAFu9X68UEjjnnDkkByzPitMDFqfndjc6xb3Y";
export const bidsPda = "GQdbYRyenJ2MCJEctkSXZdwAkZ8o85A3Nq33qebp5AYy";
export const asksPda = "AqFzaQssv6yaxfT1Nu8gJxzq3zrjBmoZbwPzwGsvWCq2";
export const reqQPda = "DBBT1DkNTKmzc3ttJYnt87HoX6yt5cLLg7PKJmuqSQ2t";
export const eventQPda = "AN4izj7VxSt57JcN3Ge7zN15Tuq7NrUAKKhoK5oDMqGy";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
