// This file was generated by a script
export const programId = "3Ek56WB263s9WH7bhGtjpNkFk8V2UDXmvsKxDJ9RzmGR";
export const marketPda = "3avQ3UzXhchSk7sLWvBQuoiXerMPRUvKJSxCUWj6ZQqx";
export const coinVault = "48Xs4FGSneDccsSNGd4nT8xE3N4AEGfcVNpa3xnqbMox";
export const pcVault = "JxyEwfBwhEWLPGwo6Te6iU9ZEwLm4j2aX341u2HYQ2f";
export const coinMint = "kKCPWyP6NoK2FzfReavuWzkukkWcit5txRoV14Huiz6";
export const pcMint = "Aow3DqumnqB9innbrJ3AKABhddvQHVsPm6eWyJtDcAVs";
export const bidsPda = "8KJb77kWzYqUwX64WnppHEUndMRZTWASb6dW7ZhvKgR4";
export const asksPda = "4fz1f13u8ZwkJdL5NKnArf1ABrZHxHES8jkRqZ6R4c6Z";
export const reqQPda = "FMLvc2ksfvjX6tA9jHSpw1K8r9eyATpkFR7tuG2vszE4";
export const eventQPda = "ZgE6fzk6Pe6pzs59kJjF9Z7dfPYMDBgh29kWxKcTbXL";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
