// This file was generated by a script
export const programId = "7gBWbsfnwLfrYkeHYpr2EKyBm8Q5B9odKzHb951BztE6";
export const marketPda = "BViV6kDPkUZ7EmoWnpT1CZNBWceovzTrQNSw5BdoN81D";
export const coinVault = "CYSzPcTAQGNpUi9s4ySuZnaW3LWMy3UnHnCYVxVvtRu5";
export const pcVault = "2yPZY9oQokvaP45641fdTStP74nKN5fHX9YrDiTQjyGk";
export const coinMint = "Hfoy4S3cMeGUyK5u5Bsgs4LCXguA6Xf3dCHeLXe4Xjc3";
export const pcMint = "GUEtCvJLDCsQvda9C5JDkGfqCRpEL4QG1VkLQ7ddwyVD";
export const bidsPda = "G3exhwXPZzC3voRqTRCabkbuNrjoWB4x6u8jBSKXxKX7";
export const asksPda = "CqoaXCA6uL1jrHNwVD5sZVcSXqPHqmjTPzgeoAnSLCfH";
export const reqQPda = "7HPdcfteFhKCX9Wc8T1zHw9d86HizLCYxzs3VAD1TCsw";
export const eventQPda = "C51abmx4jV3MJqhDYNeLfw58FpUuURNMmE7tbCA4AKsi";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
