// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "Fx42pUPS7C1hKN6CtoniUeGSt8LN3WpLmm6BMFNAzTwF";
export const coinVault = "GyQQq1AncnLkn3zvPDAHWHTXGBWya6yXSWtKaHUSmpxM";
export const pcVault = "4YMVYUzZpiiCXzJgQL2iqow2Pg24WE522U3W3EwxtF3q";
export const coinMint = "FARboNfqbFFZeBh9Xprf28kjg7ho1z3TKgUGfT9iXNx3";
export const pcMint = "BSssDJeFSAdaucHoewYcVqWhGSGnfLrVF6Hts8M5ud7E";
export const bidsPda = "FYXzkf7x5izochcZdnNy7in8dVBvuieuP1J65ucQDmZo";
export const asksPda = "7WwnceVt4yAahakDAj2Ynfg4XamZXmbmnqF3hELsw9Lh";
export const reqQPda = "3phdhUHGA1PLjbySHWdJjguWKqgFJPXjiY2N7My82mHA";
export const eventQPda = "4gYHyWdWMNnn7EKK3DUxiahGcWiQiiQvLFLT3MHZyJL4";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
