// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "AgTSoacMxHBsrAZNS7tyiMJP5foWWQPAbSCraVwe3XVh";
export const coinVault = "FrhAaVVide3qUB7yUn5CExahyfEdNzmSDDy4PrsAte3B";
export const pcVault = "6HMmLJse6XoGdZ4XswPzQFdPzJ4wRavtXZVwFiXteWCt";
export const coinMint = "5xqeESaKQnyu85QQxV3BTdJjWTroM3BDcoxPS5VuiRQR";
export const pcMint = "CY1j29FpHjfDUtyaXtnep7yPLi2VKKitZmLtpuwj1851";
export const bidsPda = "5qx51mQvUsmMmiGpEFanZSZCdesBGqVvjfTcy2FhzKvM";
export const asksPda = "ArzXUQvCotv3gakK4tGAjmybqKvU1RVdHTgXk3iYqjaY";
export const reqQPda = "GSHPSyaUi2w5A5L4XopN1n4jo8v7Kfn6LTXUDFYDV6ZT";
export const eventQPda = "4nzJq8WeESmtCLZHgrZbgEvZaRcbxGfZRUyfKL8tvuCK";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
