// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "8Yj8PuALUuBrjiEFr5yTgvWuEHvD39Ddmw89Duodh8Zi";
export const coinVault = "3rvruCvGBH85DtQekyYBKJjM2dMwnUh1PueVBgY1xgaw";
export const pcVault = "B4JixypZsKHnB23YNma5heFJL2N7LYU78H91wDXrqjgh";
export const coinMint = "5wwuT9sM3dW1d2ufBLg6vYNSTgwoXHw45eWQsPugssMh";
export const pcMint = "CEJhVzkL4G4wSdxzFftk7Djx7Lcdebd1dgA38xaGru4R";
export const bidsPda = "B3gXCGQPnRzWCCkTTWJoTsuwwLj123g3BRX3VTA4NwkA";
export const asksPda = "B3zU8KQXLNXQDzPdGNaUfz7BWPn8jHZAq2qFZYZbnTBm";
export const reqQPda = "H993XnSWqVFcgjqLA5jX47Z3hXXwrYZdmqgWsRE18EUa";
export const eventQPda = "7HejKWqU5tZZob83RzUvjXADE8j4xbJgqP3sifRbrhh";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
