// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "5dFZqR7RY4ijSKkcm66i5yY24tDR729XxsLbokHxkohM";
export const coinVault = "8epP4cuuT9cm5u48PUXxUWaszhT2pEBFGfFGZuWsKKMN";
export const pcVault = "AT8XpNuYwvqmioj73TUEtnCgZdRdPnxhDtQ3zFQGn3ry";
export const coinMint = "2Ee2wEF7T5d1HRcfpDXofNHRTFEzgtPT1M37gYtxdhWf";
export const pcMint = "232RYJQQemzhF2KvuM58kSRMFfr1iswZKi6ifrFYidtY";
export const bidsPda = "HcmcZ8gKoJUBCzrSj1E8F8uSFZr6tdymtRrduosagHj3";
export const asksPda = "566eomdYxx9Vp55mhXLH28Fqb6m7cKatbTgva7Qz3aeo";
export const reqQPda = "4K1S2F6t1Adjd8D1pThY9u8QkzmnFejFpvawh113Pmkf";
export const eventQPda = "ES5khjvNCgB5iPQftJ4RjCDhS8s1m43Ax3fiDvB83uNf";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
