// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "99FdF6hQ5QGqpNZ87BoS4XTi5AJSvQSctgWZxgSELhyh";
export const coinVault = "8ugwogp4etVYNxPpduEEyhbFwzXUwTaGheEJ4A9mJs1F";
export const pcVault = "5Xg6Zz5YYsi31uZPjDdX65nfUMNjP6vvejWpdq2zGzdu";
export const coinMint = "DwZNk7NE1jCztSpUP5ah47CpZVsYiDXSj2vRipETwK45";
export const pcMint = "2HBL9d9jbvZWUsHuC2D3sbx3kZhpaGvJ7MdXK7pFA7Xc";
export const bidsPda = "2N9cFtqF2CSaJuxs269UKodqLVmfUEYniJHbiJbjK2xj";
export const asksPda = "8C7HdhcVPQXbZBc6TjyYC46EL7tTRkDby7oHBetJb4Ja";
export const reqQPda = "CdkKGA6uzm3WZYDopYqqqkwv7yNMdiuuwL5rRWHADq3Z";
export const eventQPda = "86Yt5HZ51BCejJfHQMWHzZKEcLLNmqswWJqHQdHozZhH";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
