// This file was generated by a script
export const programId = "Bk7e6ygLwT1FoMu19HRoe99BSE5yf3WATXUVzvQGj8Un";
export const marketPda = "4Bsi9TcJkPs3gusj8adg112HwzAoFwhcfEmk2kbB6qf9";
export const coinVault = "CTBxgv4TSiV3zNYajLNDiawhDa1WW5sS9Hh5BWeH4s36";
export const pcVault = "ex1pnvdzmMF9Zh6wUbDUd4JqSLA147S2fDGjPW5WBPK";
export const coinMint = "7FsZtuvi6QLruPDdybaCs2mGbx9Nk1fVj5QgwLEoUto6";
export const pcMint = "7eaE8WLXCkEeg6cxndigSpqUcmSGntpDXghddMh7dVPA";
export const bidsPda = "DPqE9D77eY2zs4VKXPTkXWkuytMfwYNmhx7JLqz3ne4P";
export const asksPda = "685YveCoJ1CEYmpotSEP48xwjrbQy4T3tezuBT5utn5b";
export const reqQPda = "EnAMnovfWm9Xpa1SrAEVX4iAsYizu7QRcMnvy39WWzVd";
export const eventQPda = "J3XTBnXHoHthT5egbnreCixY73NagXcDEpWTuUCSaiM1";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
