// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "FbDg2qytdRRU3n24S96sr9jQYoXDny6t4zCcfiVRX9oc";
export const coinVault = "yj5Bq2eyTzZLzAvjHxwn8kVyk5dcsv5C3fToWYBqgF6";
export const pcVault = "6UETTQcxePcK7XH3opv3SFdKh5ppx4n7v1NUNsdjRAi7";
export const coinMint = "DJPAqJP8gTHbjAMVW6fdbYbToKTtkENsjtLmAUuLvB2B";
export const pcMint = "8Xf5Ppex3A66awRZZM2dhmfpHUzSj8fgYFzN7grgVHCM";
export const bidsPda = "8yrLhFM1fukUDTxK2UMeMk7uVCBDstsZkEcYdtddymRZ";
export const asksPda = "DhQ5gWUrNbX6cNfts9mU1P7p7L5U2tmQ28ujAw9YqRtW";
export const reqQPda = "CnDZP4EeEuFoMgXXBv7dRKCbx31RK8g8WZ7LZ6ypRPLs";
export const eventQPda = "GHzXvuivani2xe2M7i21GNmUJfyM52PMzhNLDPEuYu8V";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
