// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "4dc57ahasjKNFWmsosv6McMjqifbtiFMd6o3H1bzaY49";
export const coinVault = "ACvzNqjeTmH3S25mrdNgyrCDTcvMtcJZyBwBTQMKNovZ";
export const pcVault = "8vRdATuhmNJSRpU8qcwYrTEiy44mdDepTdopxBALpRrY";
export const coinMint = "DpYYrkuxWKTYVVurWcBx4Tfei25re4oHRE5VarMJhnP2";
export const pcMint = "4L1wJYzukNanBhM8dDg53GrBmRHZyYWc8d8kWNitg5Vr";
export const bidsPda = "8YiHEr2QMt3onfkvKs1LBBQtyReaMGJHDBUA7jGLPwEP";
export const asksPda = "7BKmXBJgmPyBwTWuzruymHdhw4c5Fxg5hVtkuUm5c4zu";
export const reqQPda = "6jDfJQ1d6LYeJWjM8wzXzQEjRfeswFeygs5pi7z6gTLE";
export const eventQPda = "754H5SqgM2KxNTMiqcimctQQHrxJL1MkypzbZCWVD3RY";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
