// This file was generated by a script
export const programId = "Bk7e6ygLwT1FoMu19HRoe99BSE5yf3WATXUVzvQGj8Un";
export const marketPda = "GmzY4KFmr2d3f7Db9oUFSsSvoRNtqnkDr9hjnhc5iRtN";
export const coinVault = "7PdcivNL22uiQYs9uHd5CfJzJ6u1gDEXCpDjBUAbScis";
export const pcVault = "3s1rMJM5wjKiyJwLFBqXExzNg3mKfKXNTPAaFSSa59gL";
export const coinMint = "CMzLceyZPar1eTvhFtbo5RVZdv5RT4UR57qz1oeirWmE";
export const pcMint = "Boeb3p2X7UhKHk4DjMu5QfnUjGdBVKgS8JEY9qSiYRTH";
export const bidsPda = "4VENzs8vGDLrRiU7PSzB4LTjswwRbnVgyRsiPiwAYw1r";
export const asksPda = "FPotbJp8FADXbU2Hv29NpRx7ZmHhyt9NmYyHYU1GSPe3";
export const reqQPda = "7sQNFZM1Vp2zKnKfeimmFZpCxxEeSP6aXq9F1fT4Y6td";
export const eventQPda = "H7hrczTcHYedoaMyHc9r2t43ENgXLA2ZcCHpF3ewduDg";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
