// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "Furu4aGQVY6vdWwFyo5SngeRp8NLAdsmugBP1nCqbR2q";
export const coinVault = "5qX8zMiVm4PADaiqyBM9Ku4RA8ccMreL5VwAYnNvKxeg";
export const pcVault = "8JW1C7cBh6TA2aRqWwfEUzHGGp9gHCN5uHLUFLHUgpjf";
export const coinMint = "14eRbpi1EnhD99ru8545f6n176jW23U6QW9wn6gGGbdv";
export const pcMint = "HcohwzDssPjkjfDVpk4TnQ5UeJb6H4SBtcXYRfLzH7ov";
export const bidsPda = "6Gsjqtz7KqLX6qg519Fw8bxwXxwPQWtDKJsYu9GHyLYL";
export const asksPda = "AMTFUFk7NEcfyNBjY4vpRZsATahHWTqRysHNtpHKueFm";
export const reqQPda = "6LhSpSEjFtaMYkwBvk4bGb1Dc4t4PYo49Zy8x7DvzTXu";
export const eventQPda = "3yc7jp3rqu8EYQTMANEWGRPHWEK48pm3XQHavW7vFd5f";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
