// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "8MpThmESy2GtQGNpJWxXqKbWJbf6RP6EKi9yn6ZRXNze";
export const coinVault = "AYCC8hjuxNMViNUzKZWd8bkjfCpaZDUy4pY271B3qr6c";
export const pcVault = "HVYZSJCfGU3RdnRRkpSK9FUydzSwiGFg5Dx65X4Puowi";
export const coinMint = "9f3tcxiwnjjHyttqZrWgJLRPy24c3FEdweWmJ8tVs2KT";
export const pcMint = "BxUFaBBEfYrBBTX4529pWWEoRJdcMFQ9R6finS2FC3XZ";
export const bidsPda = "Ek82rikcBBGrW84bcPtZiZWmVRi4J1VMvNy2xQdy45Yx";
export const asksPda = "9m2tN7DV18iXpmqvgsoBYA52KQV2dY2aGFY33KiqqsWS";
export const reqQPda = "FC3SubpjGTBKDs4CiBQxXkQBLF8X8FHaWwz1UvCg3B9S";
export const eventQPda = "4aLX6w4SYY3FNSqAhGuUgEL8m39DqCJNYJ5dyy3hUch1";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
