// This file was generated by a script
export const programId = "Aodrp8JRS1tCywT97x5ytaoJYczv44JYtyBHDJGLCx5m";
export const market = "2MDepwVopJKZxpsA2aFgdn223nfDBdzPk32Bxf83LTfW";
export const coinVault = "G4TkBiSjyU3JFsv1aNz4gLbBcV4Ai5qEffbjpA68GTdP";
export const pcVault = "ATsb8ft7zAPRF2Fse5vNc9uxinVEXm7w5qm8X9DT33L3";
export const coinMint = "AArupc8B4b3WmmnL3GKp2xdWN6uk3ZcjJUwb4UM4xcmg";
export const pcMint = "GjBJFSQdagQRc3jXbvJP93Vk6o5bGY7s4Pqc6kWirGhT";
export const bids = "81sg3uBE29MzzUkz4tvi872q9JHtNHNZswqJ7SwRQjcG";
export const asks = "E2MAvnyvhTCcDgcoaB9LEEEwvCHWFm1JyeSEQyWAEEu8";
export const reqQ = "916zJHc3HQPU1m5B7P1Ve9PvZN981hgQxFHhVRHYMiGv";
export const eventQ = "9UuwZKaGwQKfnHoLAGguHGYvJRGT6uei9xxXVcnShdap";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
