// This file was generated by a script
export const programId = "3Ek56WB263s9WH7bhGtjpNkFk8V2UDXmvsKxDJ9RzmGR";
export const marketPda = "FUjqNj2wofCmKr5KNPErtx6D8gYTWu7DcxZfeUaN7F29";
export const coinVault = "4z6qUJe4VvuCV1mrUtzMcEGHcANosiYWTvKFsfqqvCqM";
export const pcVault = "8gRVJiFJ1sSoAikkadmumiNbko7kbgff1G4B9mMkWGCD";
export const coinMint = "2E17rtDvxmeyR2z8Td6CJrFRgPCSNP5gCDJ4AjBKfQG6";
export const pcMint = "zur3T4e6GWzdwhdSc65GsLQdupRmoQRZzHa5SLabidz";
export const bidsPda = "SByXgdX9ouer13VAanPc8yJiLZu6Z7X4bDUkGXEumq4";
export const asksPda = "dnsqVQSrqX6We5iMZHGqQWrQjNTSxxGHpd71FHwwVso";
export const reqQPda = "AcqRxfsqSdFjmszQZZNGbeViYNy56XUHNiSTvwzLDapq";
export const eventQPda = "5vR6GTZEhidfWNyMyQg5RG3Xo8oNGgzSYiDa1sVm4TeC";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
