// This file was generated by a script
export const programId = "VGwPEHBUjxa1ZQyvCAJ166TsKPYCWKafJoDeqdXqvdJ";
export const marketPda = "FpHKi6Q2932q1GDQ3dVRzbgsmY3AyTvn63cdRHeYesWr";
export const coinVault = "BRJaSMeXbRL755vqYmGE3VgEbwM5fG3tFbN8GrwgMvXd";
export const pcVault = "DGuAPHoPqNCxGra8UDNa9CniK7qFURZzHCdHw17qCdvc";
export const coinMint = "wDLSF2UcNeD1pVChyNBJptaXWwFxu3FQtk4UTMGS2BF";
export const pcMint = "4PRvynfBAcs3ZjwqCDzHRQRthDcEMgoL6cW96KL9HVf6";
export const bidsPda = "Dbr7DyTtNhJG3eYmwxUukAkM4HTd7DCHFeozSrZnARQk";
export const asksPda = "Cfw67AEHnYSNu37sSz3zZYJ8U8zsYJSUoS6nmkTAvtRy";
export const reqQPda = "CHosi91SH7Yt3PgX4ia34n4Yjesqi6e6B4HCfr4bzyjK";
export const eventQPda = "7zHVZwkjBpcirTBS6HjzQpos8kFXwrgxkWB91R54XxH8";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
