// This file was generated by a script
export const programId = "4jde1a6MyoiwLVqB6UH5mBJp3gbpk1wcth8TZJfnf1V9";
export const marketPda = "GKM9bTGjS1ZL6W6DDWXycjWCSp9zxcfiNVrHr6BMJkaH";
export const coinVault = "DhcEEMuUhGvBVfVZwLnEEVYspHAa7YHLMJM1ARPKXkAT";
export const pcVault = "9KBF9XQp78rbzvtz3Cpb5SC9MXVSJWDiGWL5diBoMHDf";
export const coinMint = "8a6dRk9dBQ79r7SQQ15HSGWqosCcUJGKKVaiVYZXWnc3";
export const pcMint = "44QyQHK25RotjAu1cwCBEs9kdPTb8SNvNi4nftWD3aUH";
export const bidsPda = "9jsXkRWsvdTg2esQYF3QDaAUHXn46HA6sfA9do4bBqWv";
export const asksPda = "AxP4FE6axoyyrStevQRKxPz7wPkqaLWJjbWmPkLsYNTc";
export const reqQPda = "48uTyLtLZx2fEzezvKjx2pzKwQj1d9QH7PnbJeuavQWi";
export const eventQPda = "BmbLgKCT7y1jXEqc2ZH4XHaDCZQxiKhjv1XHwh7iGyTG";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
