// This file was generated by a script
export const programId = "Chj3MAzW3aXv1WJQStaoqrCC71TYQVC5WQGURM4F2HwV";
export const marketPda = "G8raQ124qrk1GDMFhpu2AGgFCEcQ5shXYHEZsKNnECLB";
export const coinVault = "DA7pxTDgodctYQCZ6oaGdvJ6CWa1TgMuZ8XJvXx48KY7";
export const pcVault = "4jyPRKAj3vSy9Fg5rbZgs918cea5y7edXH9NubHSTbGE";
export const coinMint = "GBugwzaRxiKFco9PHNsFfYTuXmZdVqCTNrdYnBXZTkfy";
export const pcMint = "7dLs9vXBMTBEX1dVbZf3ZPe7MNomsAWn4xJsptfprVvY";
export const bidsPda = "A9hUFZtAQMbCS3CfNzcroZpjSxhixSyuii89J7iLsga7";
export const asksPda = "2pnqauorHvdbWhoRdK7GYRHeVSiEqok1yGrjybt6QwCZ";
export const reqQPda = "QVDJ5AZ6DRFK9ypKozXn97x57u9UfphbynQvY1Hf6ku";
export const eventQPda = "Q5qWgGHk2hFVL5REpSy362A8RvH92wt9h4P6DnoZ7mq";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
