// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "48mpcwLiDji4ZYDWha5ofLD4KJDu8BaETc3vNdN2HF2U";
export const coinVault = "3VdKyzK1jfZi5BGEHyStiaXEcjF2iZTbR5DNvg3CCYxG";
export const pcVault = "9dEFghGmhYiX8iH6r7A47NpNvfheourHXwjNKdnFSbcP";
export const coinMint = "FH7n4XYKrsELBZC5GiwyFJzJ2qL83QXqaoHoziwbPVbo";
export const pcMint = "AFJHqHU6tMJgE43ZR3WdKtijSdx6x1dNQDbtLNiRxEWq";
export const bidsPda = "B9157bp3frHQQcRLrBPWcUJzi28e5gUPm1ZVsjZAecKW";
export const asksPda = "DZXMU9rjGgTQwcHRPv2Lgke6qr7LFH3x4ktMmoWKBhEL";
export const reqQPda = "AhRNdi7JsmyxKnUhbTyYXVpzsoZwJg5GYGwhuSPbuAJT";
export const eventQPda = "7idhc7iRrb7e7YZgzrYPkPFFYeYUgpRMRR8X7w9hmnbx";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
