// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "AHnRiQKJh1fMh7upaLhi33oMTai86v8ZTDD2Agtn6nch";
export const coinVault = "HzrrM4Z1RQDkCHovYdkXMHQdJdgtdgSaXzhp3eEbtG1M";
export const pcVault = "EAWyM6Z31qbc42YJFdB1iSwJ4XMuELxAQbt1i2SLrjHL";
export const coinMint = "4hwPkiHqJd7EVHnkjoNnhq13Y8EqpBPqYB4ZjLoBuywS";
export const pcMint = "EhqWzuSHTpXX2bAtEp8orb7ZB7J8XoGT4aR3YZJgd6kA";
export const bidsPda = "BePXWkVf7VuktzLhGouUSAvV2QLuF6dkwUZxicg2fmbg";
export const asksPda = "2rzBwy3kxLPLruzQKfMNDsBKuPZZwMmvNrwDtghW1N7B";
export const reqQPda = "DK2BWT7x2mQSh4mTZmtzGc1mvd5BiZfof9uuWnucU1Pv";
export const eventQPda = "A4Zk9yjkd3QqkirEdAqRZk8p4TQYozEpqhetrUH7VexH";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
