// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "FmCz9NShnDfGkeYaVwo56hyY8pD9zVT6hf16FqG99Xmr";
export const coinVault = "7i6AMfhuKyw8J2U2u5WUJm5iKxvC3RaQzobvu7JKJ7tR";
export const pcVault = "HEZoCZ9di5j1uuihtxfRsWjdimhy9cciSkuyAZv42prg";
export const coinMint = "3K7S6b1fLBYGoLpb2kvhQ7co2ief8Tg5WiQnipHbCWU8";
export const pcMint = "31F1ewhtZ2JZBz9KuZ9zCP8J7UTNv9uWaN25pLstBak7";
export const bidsPda = "BCiNVztpD1Mae9WmfWjhoTH9LAyxGx99b7DEe1Yo4a4D";
export const asksPda = "9dEFJK7fhWoQWk5d2EjYARZuoM7V6aCy6FC1RbTfqrWT";
export const reqQPda = "6F6ru1hN5ZyKc7PNbK9fmT7SSPEq5kb1prbcRLC4ZXTP";
export const eventQPda = "2rBFN7fKaoDZJDAvXpUPbVGLtT5bxJMqwrmNgSwux882";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
