// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "9GHEThHGk4ve1q2jAXgJtd6hnJJ4VAadEA267BgyF57t";
export const coinVault = "53diVxqU6rzemhZJBWfqTC1tXzQ2p38DjQrAUyryc2fU";
export const pcVault = "Gkca6Lr2zgykkSWzmY7qELM8vCREpgFLfvqMvoSt2yHj";
export const coinMint = "4rynQwHAk5Ev1bmyGn1kyawYm4QDCQCCp8iTjsD1tHaa";
export const pcMint = "2KRpXsZSz37KAduApBstyawGmwRVmPjLKaa6mGXEbfLj";
export const bidsPda = "8F7KJKC7yCkstQAwYgZ9agdfDbXfhfAoT7covbVgyBmP";
export const asksPda = "CJ8cjRDdVABFi3QS8LjAcpJVEzo7rDdAHtNKdFNKfhE3";
export const reqQPda = "3vCoWXhfjxnCqRDmE8abshHYACH6DQ8rr6TKVF8goUhs";
export const eventQPda = "9gP4MdjgXXhAGjAB5q6q8pW5bQg6jzvKjyYQyJzmo3jB";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
