// This file was generated by a script
export const programId = "4jnBbnBjuJB4Qpv7YzBdqb56wEDgC4cVB6uzUzEGMsiH";
export const marketPda = "5yuS43Nx7YUDmUGt7N7BAkPrEGLdq8dSAKbTMrUBUbry";
export const coinVault = "WLDibwLFqFtYtTbnPCMmgNwYhBGShz9ivfgTM4SxbL9";
export const pcVault = "5bw35TR3qwNiacfkX9dn7xCsUdi8hykur3aLrS31WSbS";
export const coinMint = "GDyLMdcXU8e64kcAgjmeDb6bJF4PojiD7ddXqQG9ZyVo";
export const pcMint = "6wqvcgamKwnbk3pNGBcp2qufp6Gy5NbAaepwastkVVYG";
export const bidsPda = "9mxsT8RnaFXNnBYpW9TY86bCtTZqnzhKueL91QExHtC5";
export const asksPda = "D9D2A7JiBq5B2VgY7yM6KEKbDeCd2BaTQk6tgpmkNtwG";
export const reqQPda = "26DcezEnEskXK3Hmnrqf4v4VbSQYPLRL6vBAZgBYv2tX";
export const eventQPda = "HRx3AKowPZEx7rNHwKmcqQR7PV9XQT7EhuBadE93fRnh";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
