// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "kWoHkqJKu7eGU5a7CP86aZbuGXze2Ft4ohDakK12ddb";
export const coinVault = "DFTMyV1Xn3XQ4KivBRParC2MByg9vvSHwoFB4NkRg5Tb";
export const pcVault = "H3rgk9LdgkRCYwiAiQKeqwuYFYqgPrF7u1nQQQBzMLYk";
export const coinMint = "5LvFo71ocagSuVa9soc87T2DZmctUM8riJd96DZ4vKSm";
export const pcMint = "G8418JcnUkqLr69zwuHGE3TThuHiBara98bxG6PTPT3B";
export const bidsPda = "7vjxA6NTirsfeBV79FeoipkxbrWsP2SnsD2PWwvz1Xzc";
export const asksPda = "3RpfqzdeoqyE9VWvH2ijgDDwXSLaiAVMvHVopkYxuUiE";
export const reqQPda = "FSK7hiAkAw6oivo78PGcPQNpvzdeqdTLEefv6dFw3QZ5";
export const eventQPda = "8rJMKzZbiB9H8JuXq2qvsbvFRwXwGbjoE6AuNF17v16";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
