// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "D8DZGKBGZMYBvHg3VsWHwCP9PYTAXv98LWaGJyNg8Whw";
export const coinVault = "2KjMMNCYucW9DRLo5ei32TPj8jrxF4xwMx8XU3bUxGC8";
export const pcVault = "9QgGv7Wc9GNDM9iLdV59rGCZHXRhPuFGxRVzq9xNmbwk";
export const coinMint = "GwYkCqHUNkmsmyBicauZm6KvC3hAcHz21pzxhWcgRPAe";
export const pcMint = "GCYN577DZU1trqZQqadv4SAGBx12BSgcyYn5NUtPy7tN";
export const bidsPda = "9J6S85ofNMrr1X618rBZt9XDRgT8eaLWBcn42FCmi5wo";
export const asksPda = "CQwxb8afN9W5YwwM7mkbYfMy6R8jppXTxTEUUxMGuwyL";
export const reqQPda = "CVeHwhqoQV1PHV5uaN2gjdvTAQb35xu9cJkL5pCwGVsF";
export const eventQPda = "jycMym3iLPNgWuMe4dfbQstxLqNJweRKXXpX1LR1cbJ";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
