// This file was generated by a script
export const programId = "Bk7e6ygLwT1FoMu19HRoe99BSE5yf3WATXUVzvQGj8Un";
export const marketPda = "H2VeTe5f5waJjswG769VoPT5Xnq8nb6Ehg3a7DnnXkHZ";
export const coinVault = "4kstNndFDuhapRpR3qkGURuWdm8sZHt857sBP7BkgPXU";
export const pcVault = "DPRuuBvRUqxirnPZMqyvXTo8N2JG6HrrMCjWoUubS6uQ";
export const coinMint = "Bn6CqJau5AC8km51LPDfd9bwJXGiYxewXXMGacGbZeN6";
export const pcMint = "7PF6BJCuoQFj3vJatU6nRxTvJWhktC3H4a26aW5wmcLv";
export const bidsPda = "Ec87uKnMbFvzTzjzrjSDaYt51HEV2WrejGTGByvGPkeX";
export const asksPda = "HUc5BkBGfnK8LuwqwTWKS7CqN7VuzXj8qiLXhJd4BG9T";
export const reqQPda = "96yDV7Mf1qW6rJP8iuwN3PmuK7iouyb9AD4WWUTEqTok";
export const eventQPda = "E5WTGW6gWtVs3weHNUEn483AkS59Yrq9avBTnSoqfA4S";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
