// This file was generated by a script
export const programId = "HViUPBVkNo9v9y24N7qForgibiGGT3vQgbHjJnaScBMW";
export const marketPda = "JEJ7wfwprrPx1QuwY95jnF2Utsj1i6zuX6DYsmW54XLM";
export const coinVault = "9LG9dncjR1ZVZDcEWvBbGMbx1ifSoGF7Ly3XSeJ11P2F";
export const pcVault = "3SLi4yUiopEKzJbe39QY39PyayZ9pK1qxr6UiPSoSRTX";
export const coinMint = "AMN37WkMcgvnC2rUxWD9e56f659g9GeRp2GjQz4oXbXq";
export const pcMint = "Fd3DxRby6s1nmtEYVCboGHRKrNAW7auoc9VAiws4Xepk";
export const bidsPda = "oADrzerFbmCYGacdrkQoSkKKh5YFzGN62iqCqmgCLzM";
export const asksPda = "4T4fd6KPGHq2nioBxqJ7tjuBv4qBemTBh5qQ9fp4gQMH";
export const reqQPda = "EguMsKMEFmbRtDCfQaZbCej1rPFVwSoBTfyMZS4fiH5a";
export const eventQPda = "6sZLTiszrS36fUksWrAsgat9DAo2bV8xt53ctbmoyFBR";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
