// This file was generated by a script
export const programId = "Aodrp8JRS1tCywT97x5ytaoJYczv44JYtyBHDJGLCx5m";
export const marketPda = "YTHJvfP4jnxpUDTcHMaducQpah2EKN5BgE8kv4yJvAY";
export const coinVault = "F97E1bAf9fdJd7aUdTs7gAv9Yzr1kYnqkbVxTtQBF9ns";
export const pcVault = "GFDuT8SGTZbFTearAJxjfcXZUZTuuK5qr5vT715aoAQd";
export const coinMint = "4rp9iMTu4hjWrf5t43Mj6N52MZJdxqTXC5Hkji3HYnqB";
export const pcMint = "HtnZJ2jGfj4mHHH5oKWCC2AvyteXmq2mok6bsJF6ehmq";
export const bidsPda = "GMxaFrGfqPivKQR22iCcLZBoj4EdoWgGVvvwX5vnfob6";
export const asksPda = "47kZZsr7AmPFbocQKaaWco1C5VnNnygMycY8gf4LiTmo";
export const reqQPda = "BmbHn8VS4vyN7SVo7mG3qMNCbkRzN1VUmAdxK2PJA9nU";
export const eventQPda = "9yqwppsfA3L8APA7KJEQhGAEimsGgZvR18Cmou7wN4ci";
export const authority = "DCEp8dRr3TeLTcFADbEfHs2iHx6usXE6JhJwzu46M12W";
